# AutoPhot Learning

In [ ]:
#Pre-Processing
import glob, os
from astropy.io import fits
FITS_DIR = "/home/liangrd/optical_data/EP260131a/NTT/"
FITS_DIR = 
bands = ['u','g','r']

TELESCOP = 'NTT'
INSTRUME = 'ultracam'

for band in bands:
    flist = glob.glob(os.path.join(FITS_DIR,f'**_{band}_**.fits'))
    for f in flist:
        hdul = fits.open(f)
        header = hdul[0].header
        
        if not header.get('TELESCOP',None):
            header['TELESCOP'] = TELESCOP
        
        if not header.get('INSTRUME',None):
            header['INSTRUME'] = INSTRUME
            
        if not header.get('FILTER',None):
            header['FILTER'] = band
            
        if not header.get('GAIN',None):
            header['GAIN'] = 1.0
        
        hdul[0].header = header
        
        hdul.writeto(f,overwrite=True)

In [1]:
import photutils
print(photutils.__version__)

2.3.0

In [1]:
from autophot import AutomatedPhotometry

# Load default configuration
config = AutomatedPhotometry.load()

# Set basic parameters
config["outdir_name"] = "REDUCED"
config["wdir"] = "/home/liangrd/optical_data/EP260131a/NTT/"
config["fits_dir"] = "/home/liangrd/optical_data/EP260131a/NTT/"
config["target_ra"] = 149.9025
config["target_dec"] = -3.3073
config["template_subtraction"]["do_subtraction"] = False
config["catalog"]["use_catalog"] = {
    "griz": "panstarrs",
    "u": "skymapper", 
    "UBVRI": "apass",
}
config['catalog']

# config["cosmic_rays"]["remove_cmrays"] = False
config["wcs"]["redo_wcs"] = False
# config[""]OK




# Run photometry
output_file = AutomatedPhotometry.run_photometry(default_input=config)
print(f"Results saved to: {output_file}")

/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
09:34:46 - INFO - Ignoring unsupported/non-photometric catalog keys: B_err, DEC, DEC_err, RA, RA_err, V_err, Y_err, g_err, i_err, name, r_err, usky_err, vsky_err,
  w_err, z_err
09:34:46 - INFO - Skipping TNS query because target_ra/target_dec are already provided (149.902500, -3.307300).
09:34:46 - INFO - Restart = True -> reprocess all files (ignore existing OUTPUT_{base}.csv)
09:34:46 - INFO - Scanned 12 FITS file(s): 0 completed (OUTPUT present), 12 pending.
09:34:46 - INFO - Initialized: 12 files
09:34:46 - INFO -
— File check: 12 FITS —

09:34:46 - INFO -
— Headers (basic) —

— Default input: /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/databases/default_input.yml —

Configuration loaded in 0.023 seconds.



— AutoPhOT photometry run —

Available filters: ['g', 'r', 'i', 'z', 'Y', 'w', 'usky', 'vsky', 'V', 'B']



— TNS check —

[WARNING] TNS lookup skipped; using target_ra/target_dec values from the configuration.

100%|██████████| 12/12 [00:00<00:00, 230.90it/s]
09:34:46 - INFO - Telescopes discovered in headers: NTT
100%|██████████| 1/1 [00:00<00:00, 26886.56it/s]
09:34:46 - INFO -
— Filters: 12 files —

100%|██████████| 12/12 [00:00<00:00, 241.79it/s]
09:34:46 - INFO - Header check complete: 12/12 files OK.
09:34:46 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:34:46 - INFO -
— Filter check —

09:34:46 - INFO - Checking 12 image(s). Catalog bands: B, V, Y, g, i, r, usky, vsky, w, z

09:34:47 - INFO - Progress completed: 12/12 item(s).
09:34:47 - INFO -   Retained: 12 file(s) with filters: g, r, u

[WARNING] SIMBAD variable-source enrichment skipped:



— Reduce/calibrate science files —

Processing:   0%|          | 0/12 [00:00<?, ?file/s]/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/arviz/__init__.py:50: FutureWarning:
ArviZ is undergoing a major refactor to improve flexibility and extensibility while maintaining a user-friendly interface.
Some upcoming changes may be backward incompatible.
For details and migration guidance, visit: https://python.arviz.org/en/latest/user_guide/migration_guide.html
  warn(
09:34:49 - INFO -
— File: EP260131a_u_wcs_ultracam_20260222_APT.fits —

09:34:49 - INFO - Full path: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_u_wcs_ultracam_20260222/EP260131a_u_wcs_ultracam_20260222_APT.fits
09:34:49 - INFO - Start time: 2026-05-18 09:34:49.199842
09:34:49 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:34:49 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:34:49 - INFO - Exposure time: 31.159 s (header keyword EXPTIME)
09:34:49 - INFO - Pixel scale from WCS: 0.355 arcsec/pixel
09:34:49 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:34:49 - INFO - Telescope: NTT
09:34:49 - INFO - Instrument: ULTRACAM
09:34:49 - INFO - Filter: u
09:34:49 - INFO - MJD: 61178.399
09:34:49 - INFO - Read noise: 0.000 e/pixel
09:34:49 - INFO - Saturation level: inf ADU
09:34:49 - INFO - Pixel scale: 0.355 arcsec/pixel
09:34:49 - INFO - Date of observation: 2026-05-18
09:34:49 - INFO -
-------------------
Image preprocessing
-------------------

09:34:49 - INFO - Target position for NaN trimming: (744.9, 526.4)
09:34:49 - INFO - NaN boundary trimming: image shape (1024, 1024)
09:34:49 - INFO - NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
09:34:49 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:34:49 - INFO - Target pixel coordinates refreshed after trimming: (744.9, 526.4)
09:34:49 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:34:49 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:34:49 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260222_APT.fits (default) —

09:34:49 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:34:49 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:34:49 - INFO - Initial source count: 82
09:34:49 - INFO - Estimated FWHM: 4.19 pixels (sigma = 2.49 pixels)
09:34:49 - INFO - Rejected 8 sources with FLAGS > 2
09:34:49 - INFO - Filtering completed in 0.003 s (retained 74 of 82 initial sources)
09:34:49 - INFO - Filtered from 82 to 74 point sources
09:34:49 - INFO - Found 74 point sources, robust FWHM 4.10 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:34:49 - INFO -
------------------------
Background: initial pass
------------------------

09:34:49 - INFO -
— Background: sky & RMS —

09:34:49 - INFO - NaN pixels: 0 (0.00%)
09:34:49 - INFO - Background regime=sparse  bright_frac=0.003  large_scale_ratio=0.085
09:34:49 - INFO - Background mesh: fwhm=4.10 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:34:50 - INFO - Source mask contains 34319 pixels (3.27% of the image) after 2 iteration(s)
09:34:50 - INFO - Masked fraction (total): 3.27%
09:34:50 - INFO - box_size=(65, 65)  filter_size=3
09:34:50 - INFO - Global stats - mean -1.803e-03  median -4.426e-03  std 1.006e+00
09:34:50 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:34:50 - INFO - Background median -6.176e-03  RMS mean 1.010e+00
09:34:50 - INFO - Preliminary FWHM: 4.1 pixels
09:34:50 - INFO - Undersampled mode: False (FWHM=4.10 px, threshold=2.50 px)
09:34:50 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:34:50 - INFO - Pre-existing WCS found in header
09:34:50 - INFO - No variable sources found in input_yaml.
09:34:50 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:34:50 - INFO -
— TNS check: Transient —

09:34:50 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:34:50 - INFO - Expected pixel position: (744.90, 526.38)
09:34:50 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:34:50 - INFO -
— Background: sky & RMS —

09:34:50 - INFO - NaN pixels: 0 (0.00%)
09:34:51 - INFO - Background regime=sparse  bright_frac=0.003  large_scale_ratio=0.085
09:34:51 - INFO - Background mesh: fwhm=4.10 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:34:51 - INFO - Source mask contains 34319 pixels (3.27% of the image) after 2 iteration(s)
09:34:51 - INFO - Masked fraction (total): 3.27%
09:34:51 - INFO - box_size=(65, 65)  filter_size=3
09:34:51 - INFO - Global stats - mean -1.803e-03  median -4.426e-03  std 1.006e+00
09:34:53 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:34:53 - INFO - Background median -6.176e-03  RMS mean 1.010e+00
09:34:55 - INFO -
---------------
Target position
---------------

09:34:55 - INFO -
— 149.9025 -3.3073 —

09:34:55 - INFO - Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (744.90, 526.38)
  Offset from image center: dx=+233.40 px, dy=+14.88 px
  Bounds: within bounds (min edge margin 278.10 px)
09:34:55 - INFO -
— 149.9025 -3.3073 —

09:34:55 - INFO -
— 149.9025 -3.3073 —

09:34:55 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:34:55 - INFO - Reusing cached background results (fpath unchanged)
09:34:55 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:34:55 - INFO -
— Catalog: sequence sources in field —

09:34:55 - INFO - Existing SKYMAPPER catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/skymapper/transient/Transient_r_10.0arcmins_skymapper_target_ra_149.902500_dec_-3.307300.csv
09:34:55 - INFO - Cleaning 263 sources
09:34:55 - WARNING - Filter column 'u' not found in output catalog; available columns: ['RA', 'DEC', 'x_pix', 'y_pix', 'g', 'g_err', 'i', 'i_err', 'r', 'r_err', 'z',
  'z_err']
09:34:55 - INFO - 263 sources in output catalog
09:34:55 - INFO - Border filtering: removed 233 sources outside border, 30 sources remaining
09:34:55 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:34:55 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260222_APT.fits (default) —

09:34:55 - INFO - Using FWHM = 4.1 pixels to construct the SExtractor convolution kernel
09:34:55 - INFO - Creating convolution kernel with FWHM: 4.1 pixels
09:34:55 - INFO - Initial source count: 56
09:34:55 - INFO - Estimated FWHM: 4.22 pixels (sigma = 2.63 pixels)
09:34:55 - INFO - Rejected 5 sources with FLAGS > 2
09:34:55 - INFO - Filtering completed in 0.002 s (retained 51 of 56 initial sources)
09:34:55 - INFO - Filtered from 56 to 51 point sources
09:34:55 - INFO - Found 51 point sources, robust FWHM 4.19 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:34:55 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260222_APT.fits (default) —

09:34:55 - INFO - Using FWHM = 4.2 pixels to construct the SExtractor convolution kernel
09:34:55 - INFO - Creating convolution kernel with FWHM: 4.2 pixels
09:34:55 - INFO - Initial source count: 55
09:34:55 - INFO - Estimated FWHM: 4.19 pixels (sigma = 2.62 pixels)
09:34:55 - INFO - Rejected 5 sources with FLAGS > 2
09:34:55 - INFO - Filtering completed in 0.002 s (retained 50 of 55 initial sources)
09:34:55 - INFO - Filtered from 55 to 50 point sources
09:34:55 - INFO - Found 50 point sources, robust FWHM 4.15 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:34:55 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:34:55 - INFO - Cleaned 50 sources to 50 with isolation distance [15]
09:34:55 - INFO -
— Recentering 50 sources —

09:34:55 - INFO - Boxsize: 15 px, Border: 19 px (annulus outer=18.5, undersampled=False)
09:34:55 - INFO - Recentering 48 sources within border
09:34:55 - INFO - 48 sources have valid cutouts
09:34:55 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:34:55 - INFO - Median pixel correction: 0.0 px
09:34:55 - INFO - Recentered 48 sources
09:34:56 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:34:56 - INFO - Excluded 11 sources based on quality cuts (kept 37/48).
09:34:56 - INFO - Number of sources: 24
09:34:56 - INFO -
— Optimum aperture: 24 sources —

09:34:56 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:34:56 - INFO - Using 24 sources with stable profiles for optimum-radius and PSF selection.
09:34:56 - INFO - Returning 12 sources, optimum radius: 1.20 * FWHM, scale: 14.5
09:34:56 - INFO - Aperture radius: 5.00 [pixels] (optimum_radius=1.20 FWHM)
09:34:56 - INFO - Computing aperture correction using 12 isolated sources at radius 5.00 pixels
09:34:56 - INFO - Aperture correction: -0.086 +/- 0.008
09:34:56 - INFO - Aperture correction (AP to total): -0.086 +/- 0.008 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:34:56 - INFO - Found 30 sources in field
09:34:56 - INFO -
— Recentering 30 sources —

09:34:56 - INFO - Boxsize: 7 px, Border: 17 px (annulus outer=16.4, undersampled=False)
09:34:56 - INFO - Recentering 28 sources within border
09:34:56 - INFO - 28 sources have valid cutouts
09:34:56 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:34:56 - INFO - Median pixel correction: 0.0 px
09:34:56 - INFO - Recentered 28 sources
09:34:56 - INFO -
— Aperture photometry: 28 field sources —

09:34:56 - INFO - Instrumental magnitude of 27 sources measured
09:34:56 - INFO - Downsampling skipped: 28 sources (<= 300 target).
09:34:56 - INFO - Building ePSF from 12 sources
09:34:56 - INFO - Small PSF-candidate pool (12): relaxed cuts to saturate_frac=0.97
09:34:56 - INFO - FWHM=3.69 pix  recenter=centroid_com  oversample=1x
09:34:56 - INFO - Initial sources: 12
09:34:56 - INFO - Sources after cuts: 12
09:34:56 - INFO - Using 12/12 PSF candidates after spatial downselection
09:34:56 - INFO - [robust_extract_stars] Extracted 12 cutouts
09:34:56 - INFO - Rejected 2 PSF stars via FFT outlier filtering
09:34:56 - INFO - PSF build FWHM: input=4.15 px, used=3.69 px; normalisation radius=5.00 px (same as photometry aperture_radius); oversample=x1
09:34:56 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=12, after_cuts=12, used_after_uniform=12
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.97
  geometry: fwhm_input=4.15px, fwhm_used=3.69px, fwhm_arcsec=1.31", pixel_scale=0.355 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=9px, fit_box=9px, cutout=37px
  normalization: aperture_radius=5.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:34:56 - INFO - PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 9 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 37 px, sigma_clip=4.00
  (15 iters)
09:34:56 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=4.66677 px, size=37x37
09:34:58 - INFO - PSF sources roundness: 0.06 +/- 0.03
09:34:58 - INFO -
— PSF photometry: 28 sources —

09:34:58 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.355 arcsec/px
    base_xy_bounds=5.64 px
    effective per tier (bright/faint/very-faint)=5.4/4.5/4.5 px
09:34:58 - INFO - Fit shapes:
    bright=(13, 13)
    faint=(11, 11)
    very-faint=(11, 11)
    xy_bounds=5.64 px
    undersampled=False
09:34:58 - INFO - Fitting 18 bright sources (LSQ)
09:34:58 - INFO - Fitting 8 faint sources (LSQ)
09:34:58 - INFO - Fitting 2 very faint sources (LSQ)
09:34:58 - INFO - LSQ retry for 1/2 problematic fits (fit_shape (11, 11) -> (13, 13), xy_bounds 4.50 -> 3.15).
09:34:58 - INFO - Fitted 28 sources in 0.20s
09:34:58 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:34:58 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:34:58 - INFO -
— Zeropoint: clean sequence stars —

09:34:58 - WARNING - Filter column 'u' not found in sources; skipping magnitude/colour clean.
09:34:58 - INFO -
— Linearity: saturation check (28 sources) —

09:34:58 - ERROR - Error in build_psf: <class 'KeyError'> in catalog.py at line 2036: "Missing required columns in catalog: ['u', 'u_err']"
09:34:58 - WARNING - Catalog linearity check failed: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types
  according to the casting rule ''safe'', proceeding with all sources
09:34:58 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:34:58 - INFO - fit_color_term: using polynomial order 1 (linear)
09:34:58 - ERROR - fit_color_term failed: KeyError in zeropoint.py:2259: 'u_err'
09:34:58 - INFO - Estimating zeropoint via sigma clipping.
09:34:58 - WARNING - AP zeropoint is not finite; writing 'unknown' to header.
09:34:58 - WARNING - PSF zeropoint is not finite; writing 'unknown' to header.
09:34:58 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:34:58 - INFO - Background mesh: fwhm=4.15 px  mesh_scale=4.00  box_size=(17, 17)  filter_size=3
09:34:58 - INFO - Local background: box_size=(17, 17)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:34:58 - INFO - Source mask contains 246 pixels (0.58% of the image) after 2 iteration(s)
09:34:58 - INFO - Local background: adding a bias of +2.07657 to the local cutout residual (and -2.07657 to the local background surface) to enforce median >= 2.07739.
  Annulus_std=1.0387, annulus_k=2.
09:34:58 - INFO - Local background: subtracted cutout median=0.000818073; raised cutout by 2.07657 so median >= 2.07739 on 42190 pixels.
09:34:59 - INFO - Source mask contains 63989 pixels (6.10% of the image) after 2 iteration(s)
09:34:59 - INFO - Background mesh: fwhm=4.15 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:34:59 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:34:59 - INFO - Target cutout: keeping uniform bias level 2.07657 in measurement image (shifted mean enabled).
09:34:59 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:34:59 - INFO - Transient's expected location: x = 744.896 pixels, y = 526.383 pixels
09:34:59 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:34:59 - INFO - Target PSF fitting bound: 2.000 arcsec (5.64 px at 0.355 arcsec/px)
09:34:59 - INFO -
— PSF photometry: 1 sources —

09:34:59 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.355 arcsec/px
    base_xy_bounds=5.64 px
    effective per tier (bright/faint/very-faint)=5.64/5.64/5.64 px
09:34:59 - INFO - Fit shapes:
    bright=(19, 19)
    faint=(17, 17)
    very-faint=(17, 17)
    xy_bounds=5.64 px
    undersampled=False
09:34:59 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.355 arcsec/px
09:34:59 - INFO - Target PSF: after bootstrap - flux_all[0]=-4.37, x_all[0]=28, y_all[0]=27, valid=True
09:34:59 - INFO - Target PSF: using aperture-matched local background annulus (r_in=9.00 px, r_out=18.00 px, estimator=median).
09:34:59 - INFO - Fitting 1 very faint sources (LSQ)
09:34:59 - INFO - LSQ retry for 1/1 problematic fits (fit_shape (17, 17) -> (19, 19), xy_bounds 5.64 -> 3.95).
09:34:59 - INFO - Fitted 1 sources in 0.04s
09:35:00 - INFO - Target background debug: sky_bkg_total=170.897  noiseSky=0.0346154
09:35:00 - INFO - Converting cutout-local to full-image: cutout_x0=716.90, cutout_y0=499.38
09:35:00 - INFO -   x_pix: 28.000 -> 744.896
09:35:00 - INFO -   y_pix: 27.000 -> 526.383
09:35:00 - INFO -   x_fit: 29.720 -> 746.616
09:35:00 - INFO -   y_fit: 28.980 -> 528.363
09:35:00 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 5159, in run_photometry
    from photutils.psf import decode_psf_flags
ImportError: cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Processing:   8%|▊         | 1/12 [00:13<02:28, 13.46s/file]

[1/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_u_wcs_ultracam_20260222.fits

09:35:02 - INFO -
— File: EP260131a_u_wcs_ultracam_20260220_APT.fits —

09:35:02 - INFO - Full path: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_u_wcs_ultracam_20260220/EP260131a_u_wcs_ultracam_20260220_APT.fits
09:35:02 - INFO - Start time: 2026-05-18 09:35:02.645518
09:35:02 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:35:02 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:35:02 - INFO - Exposure time: 25.001 s (header keyword EXPTIME)
09:35:02 - INFO - Pixel scale from WCS: 0.710 arcsec/pixel
09:35:02 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:35:02 - INFO - Telescope: NTT
09:35:02 - INFO - Instrument: ULTRACAM
09:35:02 - INFO - Filter: u
09:35:02 - INFO - MJD: 61178.399
09:35:02 - INFO - Read noise: 0.000 e/pixel
09:35:02 - INFO - Saturation level: inf ADU
09:35:02 - INFO - Pixel scale: 0.710 arcsec/pixel
09:35:02 - INFO - Date of observation: 2026-05-18
09:35:02 - INFO -
-------------------
Image preprocessing
-------------------

09:35:02 - INFO - Target position for NaN trimming: (366.9, 261.5)
09:35:02 - INFO - NaN boundary trimming: image shape (512, 512)
09:35:02 - INFO - NaN boundary trimming: 0/262144 pixels are NaN (0.0%)
09:35:02 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:35:02 - INFO - Target pixel coordinates refreshed after trimming: (366.9, 261.5)
09:35:02 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:35:02 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:35:02 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260220_APT.fits (default) —

09:35:02 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:35:02 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:35:02 - INFO - Initial source count: 56
09:35:02 - INFO - Rejected 8 sources outside FWHM range [1.1, 100.0]
09:35:02 - INFO - Estimated FWHM: 2.70 pixels (sigma = 1.49 pixels)
09:35:02 - INFO - Rejected 1 sources with FLAGS > 2
09:35:02 - INFO - Filtering completed in 0.003 s (retained 47 of 56 initial sources)
09:35:02 - INFO - Filtered from 56 to 47 point sources
09:35:02 - INFO - Found 47 point sources, robust FWHM 2.74 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:02 - INFO -
------------------------
Background: initial pass
------------------------

09:35:02 - INFO -
— Background: sky & RMS —

09:35:02 - INFO - NaN pixels: 0 (0.00%)
09:35:02 - INFO - Background regime=sparse  bright_frac=0.003  large_scale_ratio=0.101
09:35:02 - INFO - Background mesh: fwhm=2.74 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:03 - INFO - Source mask contains 6911 pixels (2.64% of the image) after 2 iteration(s)
09:35:03 - INFO - Masked fraction (total): 2.64%
09:35:03 - INFO - box_size=(65, 65)  filter_size=3
09:35:03 - INFO - Global stats - mean 1.163e+02  median 1.161e+02  std 3.755e+00
09:35:03 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:03 - INFO - Background median 1.157e+02  RMS mean 2.592e+00
09:35:03 - INFO - Preliminary FWHM: 2.7 pixels
09:35:03 - INFO - Undersampled mode: False (FWHM=2.74 px, threshold=2.50 px)
09:35:03 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:35:03 - INFO - Pre-existing WCS found in header
09:35:03 - INFO - No variable sources found in input_yaml.
09:35:03 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:35:03 - INFO -
— TNS check: Transient —

09:35:03 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:35:03 - INFO - Expected pixel position: (366.91, 261.54)
09:35:03 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:35:03 - INFO -
— Background: sky & RMS —

09:35:03 - INFO - NaN pixels: 0 (0.00%)
09:35:03 - INFO - Background regime=sparse  bright_frac=0.003  large_scale_ratio=0.101
09:35:03 - INFO - Background mesh: fwhm=2.74 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:03 - INFO - Source mask contains 6911 pixels (2.64% of the image) after 2 iteration(s)
09:35:03 - INFO - Masked fraction (total): 2.64%
09:35:03 - INFO - box_size=(65, 65)  filter_size=3
09:35:03 - INFO - Global stats - mean 1.163e+02  median 1.161e+02  std 3.755e+00
09:35:03 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:03 - INFO - Background median 1.157e+02  RMS mean 2.592e+00
09:35:04 - INFO -
---------------
Target position
---------------

09:35:04 - INFO -
— 149.9025 -3.3073 —

09:35:04 - INFO - Target summary:
  Name: Transient
  Image size: 512 x 512 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (366.91, 261.54)
  Offset from image center: dx=+111.41 px, dy=+6.04 px
  Bounds: within bounds (min edge margin 144.09 px)
09:35:04 - INFO -
— 149.9025 -3.3073 —

09:35:04 - INFO -
— 149.9025 -3.3073 —

09:35:04 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:35:04 - INFO - Reusing cached background results (fpath unchanged)
09:35:04 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:35:04 - INFO -
— Catalog: sequence sources in field —

09:35:04 - INFO - Existing SKYMAPPER catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/skymapper/transient/Transient_r_10.0arcmins_skymapper_target_ra_149.902500_dec_-3.307300.csv
09:35:04 - INFO - Cleaning 263 sources
09:35:04 - WARNING - Filter column 'u' not found in output catalog; available columns: ['RA', 'DEC', 'x_pix', 'y_pix', 'g', 'g_err', 'i', 'i_err', 'r', 'r_err', 'z',
  'z_err']
09:35:04 - INFO - 263 sources in output catalog
09:35:04 - INFO - Border filtering: removed 234 sources outside border, 29 sources remaining
09:35:04 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:35:04 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260220_APT.fits (default) —

09:35:04 - INFO - Using FWHM = 2.7 pixels to construct the SExtractor convolution kernel
09:35:04 - INFO - Creating convolution kernel with FWHM: 2.7 pixels
09:35:04 - INFO - Initial source count: 54
09:35:04 - INFO - Rejected 7 sources outside FWHM range [1.1, 100.0]
09:35:04 - INFO - Estimated FWHM: 2.67 pixels (sigma = 1.46 pixels)
09:35:04 - INFO - Rejected 1 sources with FLAGS > 2
09:35:04 - INFO - Filtering completed in 0.002 s (retained 46 of 54 initial sources)
09:35:04 - INFO - Filtered from 54 to 46 point sources
09:35:04 - INFO - Found 46 point sources, robust FWHM 2.71 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:04 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260220_APT.fits (default) —

09:35:04 - INFO - Using FWHM = 2.7 pixels to construct the SExtractor convolution kernel
09:35:04 - INFO - Creating convolution kernel with FWHM: 2.7 pixels
09:35:04 - INFO - Initial source count: 54
09:35:04 - INFO - Rejected 7 sources outside FWHM range [1.1, 100.0]
09:35:04 - INFO - Estimated FWHM: 2.67 pixels (sigma = 1.46 pixels)
09:35:04 - INFO - Rejected 1 sources with FLAGS > 2
09:35:04 - INFO - Filtering completed in 0.002 s (retained 46 of 54 initial sources)
09:35:04 - INFO - Filtered from 54 to 46 point sources
09:35:04 - INFO - Found 46 point sources, robust FWHM 2.71 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:04 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:35:04 - INFO - Cleaned 46 sources to 41 with isolation distance [15]
09:35:04 - INFO -
— Recentering 41 sources —

09:35:04 - INFO - Boxsize: 15 px, Border: 15 px (annulus outer=12.0, undersampled=False)
09:35:04 - INFO - Recentering 40 sources within border
09:35:04 - INFO - 40 sources have valid cutouts
09:35:04 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:04 - INFO - Median pixel correction: 0.0 px
09:35:04 - INFO - Recentered 40 sources
09:35:04 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:35:04 - INFO - Excluded 12 sources based on quality cuts (kept 28/40).
09:35:04 - INFO - Number of sources: 14
09:35:04 - INFO -
— Optimum aperture: 14 sources —

09:35:04 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:35:04 - INFO - Using 14 sources with stable profiles for optimum-radius and PSF selection.
09:35:04 - INFO - Final tail screen was over-restrictive; rescued to 8 sources.
09:35:04 - INFO - Returning 8 sources, optimum radius: 1.03 * FWHM, scale: 12.5
09:35:04 - INFO - Aperture radius: 3.00 [pixels] (optimum_radius=1.03 FWHM)
09:35:04 - INFO - Computing aperture correction using 8 isolated sources at radius 3.00 pixels
09:35:04 - INFO - Aperture correction: -0.075 +/- 0.017
09:35:04 - INFO - Aperture correction (AP to total): -0.075 +/- 0.017 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:35:04 - INFO - Found 29 sources in field
09:35:04 - INFO -
— Recentering 29 sources —

09:35:04 - INFO - Boxsize: 7 px, Border: 11 px (annulus outer=10.4, undersampled=False)
09:35:04 - INFO - Recentering 29 sources within border
09:35:04 - INFO - 29 sources have valid cutouts
09:35:04 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:04 - INFO - Median pixel correction: 0.0 px
09:35:04 - INFO - Recentered 29 sources
09:35:04 - INFO -
— Aperture photometry: 29 field sources —

09:35:04 - INFO - Instrumental magnitude of 29 sources measured
09:35:04 - INFO - Downsampling skipped: 28 sources (<= 300 target).
09:35:04 - INFO - Building ePSF from 8 sources
09:35:04 - INFO - Small PSF-candidate pool (8): relaxed cuts to saturate_frac=0.97
09:35:04 - INFO - Image appears undersampled (FWHM=2.00 pix) and psf_oversample=1; consider increasing psf_oversample in the config if enough PSF stars are available.
09:35:04 - INFO - Undersampled regime (FWHM <= 2.50 px): disabling strict threshold/SNR candidate cuts for PSF build.
09:35:04 - INFO - FWHM=2.00 pix  recenter=centroid_2dg  oversample=1x
09:35:04 - INFO - Initial sources: 8
09:35:04 - INFO - Sources after cuts: 8
09:35:04 - INFO - Using 8/8 PSF candidates after spatial downselection
09:35:04 - INFO - [robust_extract_stars] Extracted 8 cutouts
09:35:04 - INFO - FFT outlier rejection would leave too few stars (5/8); keeping original set.
09:35:04 - INFO - PSF build FWHM: input=2.71 px, used=2.00 px; normalisation radius=3.00 px (same as photometry aperture_radius); oversample=x1
09:35:04 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=8, after_cuts=8, used_after_uniform=8
  selection cuts: min_candidates=8, threshold_limit=nan, SNR_limit=[0.0, 1000000000000.0], min_keep_frac_after_cut=0.30, saturate_frac=0.97
  geometry: fwhm_input=2.71px, fwhm_used=2.00px, fwhm_arcsec=1.42", pixel_scale=0.710 arcsec/px, build_sampling_boost=1.20, oversample=x1,
    recenter=centroid_2dg, cen_box=7px, fit_box=5px, cutout=27px
  normalization: aperture_radius=3.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:35:04 - INFO - PSF build windows: fit_box=3.00*FWHM (base 2.50, min 2.50 arcsec) -> 5 px, cutout=12.00*FWHM (base 10.00, min 9.00 arcsec) -> 27 px, sigma_clip=4.00
  (15 iters)
09:35:04 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=2.52464 px, size=27x27
09:35:05 - INFO - PSF sources roundness: 0.02 +/- 0.01
09:35:05 - INFO -
— PSF photometry: 28 sources —

09:35:05 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.71 arcsec/px
    base_xy_bounds=2.82 px
    effective per tier (bright/faint/very-faint)=2.82/2.7/2.7 px
09:35:05 - INFO - Fit shapes:
    bright=(9, 9)
    faint=(7, 7)
    very-faint=(7, 7)
    xy_bounds=2.82 px
    undersampled=False
09:35:05 - INFO - Fitting 18 bright sources (LSQ)
09:35:06 - INFO - Fitting 1 faint sources (LSQ)
09:35:06 - INFO - Fitting 9 very faint sources (LSQ)
09:35:06 - INFO - Fitted 28 sources in 0.21s
09:35:06 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:35:06 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:35:06 - INFO -
— Zeropoint: clean sequence stars —

09:35:06 - WARNING - Filter column 'u' not found in sources; skipping magnitude/colour clean.
09:35:06 - INFO -
— Linearity: saturation check (28 sources) —

09:35:06 - ERROR - Error in build_psf: <class 'KeyError'> in catalog.py at line 2036: "Missing required columns in catalog: ['u', 'u_err']"
09:35:06 - WARNING - Catalog linearity check failed: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types
  according to the casting rule ''safe'', proceeding with all sources
09:35:06 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:35:06 - INFO - fit_color_term: using polynomial order 1 (linear)
09:35:06 - ERROR - fit_color_term failed: KeyError in zeropoint.py:2259: 'u_err'
09:35:06 - INFO - Estimating zeropoint via sigma clipping.
09:35:06 - WARNING - AP zeropoint is not finite; writing 'unknown' to header.
09:35:06 - WARNING - PSF zeropoint is not finite; writing 'unknown' to header.
09:35:06 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:35:06 - INFO - Background mesh: fwhm=2.71 px  mesh_scale=4.00  box_size=(11, 11)  filter_size=3
09:35:06 - INFO - Local background: box_size=(11, 11)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:35:06 - INFO - Source mask contains 0 pixels (0.00% of the image) after 1 iteration(s)
09:35:06 - INFO - Local background: adding a bias of +4.92342 to the local cutout residual (and -4.92342 to the local background surface) to enforce median >= 4.92693.
  Annulus_std=2.46347, annulus_k=2.
09:35:06 - INFO - Local background: subtracted cutout median=0.00351147; raised cutout by 4.92342 so median >= 4.92693 on 17956 pixels.
09:35:06 - INFO - Source mask contains 12895 pixels (4.92% of the image) after 2 iteration(s)
09:35:06 - INFO - Background mesh: fwhm=2.71 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:06 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:06 - INFO - Target cutout: keeping uniform bias level 4.92342 in measurement image (shifted mean enabled).
09:35:06 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:35:06 - INFO - Transient's expected location: x = 366.908 pixels, y = 261.540 pixels
09:35:06 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:35:06 - INFO - Target PSF fitting bound: 2.000 arcsec (2.82 px at 0.710 arcsec/px)
09:35:06 - INFO -
— PSF photometry: 1 sources —

09:35:06 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.71 arcsec/px
    base_xy_bounds=2.82 px
    effective per tier (bright/faint/very-faint)=2.82/2.82/2.82 px
09:35:06 - INFO - Fit shapes:
    bright=(13, 13)
    faint=(11, 11)
    very-faint=(11, 11)
    xy_bounds=2.82 px
    undersampled=False
09:35:06 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.710 arcsec/px
09:35:06 - INFO - Target PSF: after bootstrap - flux_all[0]=53.2, x_all[0]=22, y_all[0]=22, valid=True
09:35:06 - INFO - Target PSF: using aperture-matched local background annulus (r_in=6.00 px, r_out=12.00 px, estimator=median).
09:35:06 - INFO - Fitting 1 very faint sources (LSQ)
09:35:06 - INFO - LSQ retry for 1/1 problematic fits (fit_shape (11, 11) -> (13, 13), xy_bounds 2.82 -> 1.97).
09:35:06 - INFO - Fitted 1 sources in 0.10s
09:35:07 - INFO - Target background debug: sky_bkg_total=145.044  noiseSky=0.0907189
09:35:07 - INFO - Converting cutout-local to full-image: cutout_x0=344.91, cutout_y0=239.54
09:35:07 - INFO -   x_pix: 22.000 -> 366.908
09:35:07 - INFO -   y_pix: 22.000 -> 261.540
09:35:07 - INFO -   x_fit: 22.976 -> 367.884
09:35:07 - INFO -   y_fit: 20.029 -> 259.569
09:35:07 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 5159, in run_photometry
    from photutils.psf import decode_psf_flags
ImportError: cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Processing:  17%|█▋        | 2/12 [00:20<01:37,  9.70s/file]

[2/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_u_wcs_ultracam_20260220.fits

09:35:09 - INFO -
— File: EP260131a_u_wcs_ultracam_20260219_APT.fits —

09:35:09 - INFO - Full path: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_u_wcs_ultracam_20260219/EP260131a_u_wcs_ultracam_20260219_APT.fits
09:35:09 - INFO - Start time: 2026-05-18 09:35:09.702829
09:35:09 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:35:09 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:35:09 - INFO - Exposure time: 31.159 s (header keyword EXPTIME)
09:35:09 - INFO - Pixel scale from WCS: 0.354 arcsec/pixel
09:35:09 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:35:09 - INFO - Telescope: NTT
09:35:09 - INFO - Instrument: ULTRACAM
09:35:09 - INFO - Filter: u
09:35:09 - INFO - MJD: 61178.399
09:35:09 - INFO - Read noise: 0.000 e/pixel
09:35:09 - INFO - Saturation level: inf ADU
09:35:09 - INFO - Pixel scale: 0.354 arcsec/pixel
09:35:09 - INFO - Date of observation: 2026-05-18
09:35:09 - INFO -
-------------------
Image preprocessing
-------------------

09:35:10 - INFO - Target position for NaN trimming: (731.1, 529.8)
09:35:10 - INFO - NaN boundary trimming: image shape (1024, 1024)
09:35:10 - INFO - NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
09:35:10 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:35:10 - INFO - Target pixel coordinates refreshed after trimming: (731.1, 529.8)
09:35:10 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:35:10 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:35:10 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260219_APT.fits (default) —

09:35:10 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:35:10 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:35:10 - INFO - Initial source count: 76
09:35:10 - INFO - Rejected 5 sources outside FWHM range [1.1, 100.0]
09:35:10 - INFO - Estimated FWHM: 4.77 pixels (sigma = 3.32 pixels)
09:35:10 - INFO - Rejected 4 sources with FLAGS > 2
09:35:10 - INFO - Filtering completed in 0.003 s (retained 67 of 76 initial sources)
09:35:10 - INFO - Filtered from 76 to 67 point sources
09:35:10 - INFO - Found 67 point sources, robust FWHM 4.77 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:10 - INFO -
------------------------
Background: initial pass
------------------------

09:35:10 - INFO -
— Background: sky & RMS —

09:35:10 - INFO - NaN pixels: 2 (0.00%)
09:35:10 - INFO - Background regime=sparse  bright_frac=0.003  large_scale_ratio=0.097
09:35:10 - INFO - Background mesh: fwhm=4.77 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:11 - INFO - Source mask contains 38903 pixels (3.71% of the image) after 2 iteration(s)
09:35:11 - INFO - Masked fraction (total): 3.71%
09:35:11 - INFO - box_size=(65, 65)  filter_size=3
09:35:11 - INFO - Global stats - mean 5.243e-04  median -2.661e-03  std 1.038e+00
09:35:11 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:11 - INFO - Background median -2.969e-03  RMS mean 1.041e+00
09:35:11 - INFO - Preliminary FWHM: 4.8 pixels
09:35:11 - INFO - Undersampled mode: False (FWHM=4.77 px, threshold=2.50 px)
09:35:11 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:35:11 - INFO - Pre-existing WCS found in header
09:35:11 - INFO - No variable sources found in input_yaml.
09:35:11 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:35:11 - INFO -
— TNS check: Transient —

09:35:11 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:35:11 - INFO - Expected pixel position: (731.08, 529.85)
09:35:11 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:35:11 - INFO -
— Background: sky & RMS —

09:35:11 - INFO - NaN pixels: 2 (0.00%)
09:35:12 - INFO - Background regime=sparse  bright_frac=0.003  large_scale_ratio=0.097
09:35:12 - INFO - Background mesh: fwhm=4.77 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:12 - INFO - Source mask contains 38903 pixels (3.71% of the image) after 2 iteration(s)
09:35:12 - INFO - Masked fraction (total): 3.71%
09:35:12 - INFO - box_size=(65, 65)  filter_size=3
09:35:12 - INFO - Global stats - mean 5.243e-04  median -2.661e-03  std 1.038e+00
09:35:12 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:12 - INFO - Background median -2.969e-03  RMS mean 1.041e+00
09:35:14 - INFO -
---------------
Target position
---------------

09:35:14 - INFO -
— 149.9025 -3.3073 —

09:35:14 - INFO - Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (731.08, 529.85)
  Offset from image center: dx=+219.58 px, dy=+18.35 px
  Bounds: within bounds (min edge margin 291.92 px)
09:35:14 - INFO -
— 149.9025 -3.3073 —

09:35:14 - INFO -
— 149.9025 -3.3073 —

09:35:14 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:35:14 - INFO - Reusing cached background results (fpath unchanged)
09:35:14 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:35:14 - INFO -
— Catalog: sequence sources in field —

09:35:14 - INFO - Existing SKYMAPPER catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/skymapper/transient/Transient_r_10.0arcmins_skymapper_target_ra_149.902500_dec_-3.307300.csv
09:35:14 - INFO - Cleaning 263 sources
09:35:14 - WARNING - Filter column 'u' not found in output catalog; available columns: ['RA', 'DEC', 'x_pix', 'y_pix', 'g', 'g_err', 'i', 'i_err', 'r', 'r_err', 'z',
  'z_err']
09:35:14 - INFO - 263 sources in output catalog
09:35:14 - INFO - Border filtering: removed 234 sources outside border, 29 sources remaining
09:35:14 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:35:14 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260219_APT.fits (default) —

09:35:14 - INFO - Using FWHM = 4.8 pixels to construct the SExtractor convolution kernel
09:35:14 - INFO - Creating convolution kernel with FWHM: 4.8 pixels
09:35:14 - INFO - Initial source count: 51
09:35:14 - INFO - Rejected 3 sources outside FWHM range [1.1, 100.0]
09:35:14 - INFO - Estimated FWHM: 4.83 pixels (sigma = 3.00 pixels)
09:35:14 - INFO - Rejected 3 sources with FLAGS > 2
09:35:14 - INFO - Filtering completed in 0.002 s (retained 45 of 51 initial sources)
09:35:14 - INFO - Filtered from 51 to 45 point sources
09:35:14 - INFO - Found 45 point sources, robust FWHM 4.82 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:14 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260219_APT.fits (default) —

09:35:14 - INFO - Using FWHM = 4.8 pixels to construct the SExtractor convolution kernel
09:35:14 - INFO - Creating convolution kernel with FWHM: 4.8 pixels
09:35:14 - INFO - Initial source count: 51
09:35:14 - INFO - Rejected 2 sources outside FWHM range [1.1, 100.0]
09:35:14 - INFO - Estimated FWHM: 4.91 pixels (sigma = 2.98 pixels)
09:35:14 - INFO - Rejected 3 sources with FLAGS > 2
09:35:14 - INFO - Filtering completed in 0.002 s (retained 46 of 51 initial sources)
09:35:14 - INFO - Filtered from 51 to 46 point sources
09:35:14 - INFO - Found 46 point sources, robust FWHM 4.88 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:14 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:35:14 - INFO - Cleaned 46 sources to 46 with isolation distance [15]
09:35:14 - INFO -
— Recentering 46 sources —

09:35:14 - INFO - Boxsize: 15 px, Border: 22 px (annulus outer=21.7, undersampled=False)
09:35:14 - INFO - Recentering 45 sources within border
09:35:14 - INFO - 45 sources have valid cutouts
09:35:14 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:14 - INFO - Median pixel correction: 0.0 px
09:35:14 - INFO - Recentered 45 sources
09:35:15 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:35:15 - INFO - Excluded 8 sources based on quality cuts (kept 37/45).
09:35:15 - INFO - Number of sources: 30
09:35:15 - INFO -
— Optimum aperture: 30 sources —

09:35:15 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:35:15 - INFO - Concentration gate rejected 1 broad sources (enc_flux(1.70*FWHM) < 0.50).
09:35:15 - INFO - Using 28 sources with stable profiles for optimum-radius and PSF selection.
09:35:15 - INFO - Returning 14 sources, optimum radius: 1.22 * FWHM, scale: 16.5
09:35:15 - INFO - Aperture radius: 7.00 [pixels] (optimum_radius=1.22 FWHM)
09:35:15 - INFO - Computing aperture correction using 14 isolated sources at radius 7.00 pixels
09:35:15 - INFO - Aperture correction: -0.055 +/- 0.014
09:35:15 - INFO - Aperture correction (AP to total): -0.055 +/- 0.014 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:35:15 - INFO - Found 29 sources in field
09:35:15 - INFO -
— Recentering 29 sources —

09:35:15 - INFO - Boxsize: 9 px, Border: 21 px (annulus outer=20.4, undersampled=False)
09:35:15 - INFO - Recentering 29 sources within border
09:35:15 - INFO - 29 sources have valid cutouts
09:35:15 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:15 - INFO - Median pixel correction: 0.0 px
09:35:15 - INFO - Recentered 29 sources
09:35:15 - INFO -
— Aperture photometry: 29 field sources —

09:35:16 - INFO - Instrumental magnitude of 28 sources measured
09:35:16 - INFO - Downsampling skipped: 29 sources (<= 300 target).
09:35:16 - INFO - Building ePSF from 14 sources
09:35:16 - INFO - Small PSF-candidate pool (14): relaxed cuts to saturate_frac=0.97
09:35:16 - INFO - FWHM=4.63 pix  recenter=centroid_com  oversample=1x
09:35:16 - INFO - Initial sources: 14
09:35:16 - INFO - Sources after cuts: 14
09:35:16 - INFO - Using 14/14 PSF candidates after spatial downselection
09:35:16 - INFO - [robust_extract_stars] Extracted 14 cutouts
09:35:16 - INFO - Rejected 1 PSF stars via FFT outlier filtering
09:35:16 - INFO - PSF build FWHM: input=4.88 px, used=4.63 px; normalisation radius=7.00 px (same as photometry aperture_radius); oversample=x1
09:35:16 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=14, after_cuts=14, used_after_uniform=14
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.97
  geometry: fwhm_input=4.88px, fwhm_used=4.63px, fwhm_arcsec=1.64", pixel_scale=0.354 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=11px, fit_box=11px, cutout=47px
  normalization: aperture_radius=7.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:35:16 - INFO - PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 11 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 47 px, sigma_clip=4.00
  (15 iters)
09:35:16 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=5.85461 px, size=47x47
09:35:17 - INFO - PSF sources roundness: 0.03 +/- 0.02
09:35:17 - INFO -
— PSF photometry: 29 sources —

09:35:17 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.354 arcsec/px
    base_xy_bounds=5.65 px
    effective per tier (bright/faint/very-faint)=5.65/5.4/5.4 px
09:35:17 - INFO - Fit shapes:
    bright=(15, 15)
    faint=(13, 13)
    very-faint=(13, 13)
    xy_bounds=5.65 px
    undersampled=False
09:35:17 - INFO - Fitting 19 bright sources (LSQ)
09:35:17 - INFO - Fitting 6 faint sources (LSQ)
09:35:18 - INFO - Fitting 4 very faint sources (LSQ)
09:35:18 - INFO - LSQ retry for 2/4 problematic fits (fit_shape (13, 13) -> (15, 15), xy_bounds 5.40 -> 3.78).
09:35:18 - INFO - Fitted 29 sources in 0.27s
09:35:18 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:35:18 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:35:18 - INFO -
— Zeropoint: clean sequence stars —

09:35:18 - WARNING - Filter column 'u' not found in sources; skipping magnitude/colour clean.
09:35:18 - INFO -
— Linearity: saturation check (29 sources) —

09:35:18 - ERROR - Error in build_psf: <class 'KeyError'> in catalog.py at line 2036: "Missing required columns in catalog: ['u', 'u_err']"
09:35:18 - WARNING - Catalog linearity check failed: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types
  according to the casting rule ''safe'', proceeding with all sources
09:35:18 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:35:18 - INFO - fit_color_term: using polynomial order 1 (linear)
09:35:18 - ERROR - fit_color_term failed: KeyError in zeropoint.py:2259: 'u_err'
09:35:18 - INFO - Estimating zeropoint via sigma clipping.
09:35:18 - WARNING - AP zeropoint is not finite; writing 'unknown' to header.
09:35:18 - WARNING - PSF zeropoint is not finite; writing 'unknown' to header.
09:35:18 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:35:18 - INFO - Background mesh: fwhm=4.88 px  mesh_scale=4.00  box_size=(19, 19)  filter_size=3
09:35:18 - INFO - Local background: box_size=(19, 19)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:35:18 - INFO - Source mask contains 0 pixels (0.00% of the image) after 1 iteration(s)
09:35:18 - INFO - Local background: adding a bias of +1.97986 to the local cutout residual (and -1.97986 to the local background surface) to enforce median >= 1.97626.
  Annulus_std=0.988128, annulus_k=2.
09:35:18 - INFO - Local background: subtracted cutout median=-0.00360524; raised cutout by 1.97986 so median >= 1.97626 on 58564 pixels.
09:35:18 - INFO - Source mask contains 60132 pixels (5.73% of the image) after 2 iteration(s)
09:35:18 - INFO - Background mesh: fwhm=4.88 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:19 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:19 - INFO - Target cutout: keeping uniform bias level 1.97986 in measurement image (shifted mean enabled).
09:35:19 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:35:19 - INFO - Transient's expected location: x = 731.079 pixels, y = 529.846 pixels
09:35:19 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:35:19 - INFO - Target PSF fitting bound: 2.000 arcsec (5.65 px at 0.354 arcsec/px)
09:35:19 - INFO -
— PSF photometry: 1 sources —

09:35:19 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.354 arcsec/px
    base_xy_bounds=5.65 px
    effective per tier (bright/faint/very-faint)=5.65/5.65/5.65 px
09:35:19 - INFO - Fit shapes:
    bright=(23, 23)
    faint=(19, 19)
    very-faint=(19, 19)
    xy_bounds=5.65 px
    undersampled=False
09:35:19 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.354 arcsec/px
09:35:19 - INFO - Target PSF: after bootstrap - flux_all[0]=98.9, x_all[0]=31, y_all[0]=32, valid=True
09:35:19 - INFO - Target PSF: using aperture-matched local background annulus (r_in=11.00 px, r_out=21.00 px, estimator=median).
09:35:19 - INFO - Fitting 1 faint sources (LSQ)
09:35:19 - INFO - Fitted 1 sources in 0.02s
09:35:19 - INFO - Target background debug: sky_bkg_total=294.876  noiseSky=0.0347237
09:35:19 - INFO - Converting cutout-local to full-image: cutout_x0=700.08, cutout_y0=497.85
09:35:19 - INFO -   x_pix: 31.000 -> 731.079
09:35:19 - INFO -   y_pix: 32.000 -> 529.846
09:35:19 - INFO -   x_fit: 28.532 -> 728.611
09:35:19 - INFO -   y_fit: 37.649 -> 535.495
09:35:19 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 5159, in run_photometry
    from photutils.psf import decode_psf_flags
ImportError: cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Processing:  25%|██▌       | 3/12 [00:33<01:39, 11.05s/file]

[3/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_u_wcs_ultracam_20260219.fits

09:35:22 - INFO -
— File: EP260131a_u_wcs_ultracam_20260215_bkg_sub_APT.fits —

09:35:22 - INFO - Full path:
  /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_u_wcs_ultracam_20260215_bkg_sub/EP260131a_u_wcs_ultracam_20260215_bkg_sub_APT.fits
09:35:22 - INFO - Start time: 2026-05-18 09:35:22.363691
09:35:22 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:35:22 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:35:22 - INFO - Exposure time: 25.001 s (header keyword EXPTIME)
09:35:22 - INFO - Pixel scale from WCS: 0.355 arcsec/pixel
09:35:22 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:35:22 - INFO - Telescope: NTT
09:35:22 - INFO - Instrument: ULTRACAM
09:35:22 - INFO - Filter: u
09:35:22 - INFO - MJD: 61178.400
09:35:22 - INFO - Read noise: 0.000 e/pixel
09:35:22 - INFO - Saturation level: inf ADU
09:35:22 - INFO - Pixel scale: 0.355 arcsec/pixel
09:35:22 - INFO - Date of observation: 2026-05-18
09:35:22 - INFO -
-------------------
Image preprocessing
-------------------

09:35:22 - INFO - Target position for NaN trimming: (706.1, 521.4)
09:35:22 - INFO - NaN boundary trimming: image shape (1024, 1024)
09:35:22 - INFO - NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
09:35:22 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:35:22 - INFO - Target pixel coordinates refreshed after trimming: (706.1, 521.4)
09:35:22 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:35:22 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:35:22 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260215_bkg_sub_APT.fits (default) —

09:35:22 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:35:22 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:35:22 - INFO - Initial source count: 135
09:35:22 - INFO - Rejected 50 sources outside FWHM range [1.1, 100.0]
09:35:22 - INFO - Estimated FWHM: 4.96 pixels (sigma = 1.78 pixels)
09:35:22 - INFO - Rejected 3 sources with FLAGS > 2
09:35:22 - INFO - Filtering completed in 0.003 s (retained 82 of 135 initial sources)
09:35:22 - INFO - Filtered from 135 to 82 point sources
09:35:22 - INFO - Found 82 point sources, robust FWHM 4.96 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:22 - INFO -
------------------------
Background: initial pass
------------------------

09:35:22 - INFO -
— Background: sky & RMS —

09:35:22 - INFO - NaN pixels: 0 (0.00%)
09:35:23 - INFO - Background regime=sparse  bright_frac=0.002  large_scale_ratio=0.089
09:35:23 - INFO - Background mesh: fwhm=4.96 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:23 - INFO - Source mask contains 18790 pixels (1.79% of the image) after 2 iteration(s)
09:35:23 - INFO - Masked fraction (total): 1.79%
09:35:23 - INFO - box_size=(65, 65)  filter_size=3
09:35:23 - INFO - Global stats - mean -1.716e-02  median -1.345e-02  std 3.158e+00
09:35:24 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:24 - INFO - Background median -5.781e-03  RMS mean 3.177e+00
09:35:24 - INFO - Preliminary FWHM: 5.0 pixels
09:35:24 - INFO - Undersampled mode: False (FWHM=4.96 px, threshold=2.50 px)
09:35:24 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:35:24 - INFO - Pre-existing WCS found in header
09:35:24 - INFO - No variable sources found in input_yaml.
09:35:24 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:35:24 - INFO -
— TNS check: Transient —

09:35:24 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:35:24 - INFO - Expected pixel position: (706.14, 521.44)
09:35:24 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:35:24 - INFO -
— Background: sky & RMS —

09:35:24 - INFO - NaN pixels: 0 (0.00%)
09:35:24 - INFO - Background regime=sparse  bright_frac=0.002  large_scale_ratio=0.089
09:35:24 - INFO - Background mesh: fwhm=4.96 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:25 - INFO - Source mask contains 18790 pixels (1.79% of the image) after 2 iteration(s)
09:35:25 - INFO - Masked fraction (total): 1.79%
09:35:25 - INFO - box_size=(65, 65)  filter_size=3
09:35:25 - INFO - Global stats - mean -1.716e-02  median -1.345e-02  std 3.158e+00
09:35:25 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:25 - INFO - Background median -5.781e-03  RMS mean 3.177e+00
09:35:27 - INFO -
---------------
Target position
---------------

09:35:27 - INFO -
— 149.9025 -3.3073 —

09:35:27 - INFO - Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (706.14, 521.44)
  Offset from image center: dx=+194.64 px, dy=+9.94 px
  Bounds: within bounds (min edge margin 316.86 px)
09:35:27 - INFO -
— 149.9025 -3.3073 —

09:35:27 - INFO -
— 149.9025 -3.3073 —

09:35:27 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:35:27 - INFO - Reusing cached background results (fpath unchanged)
09:35:27 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:35:27 - INFO -
— Catalog: sequence sources in field —

09:35:27 - INFO - Existing SKYMAPPER catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/skymapper/transient/Transient_r_10.0arcmins_skymapper_target_ra_149.902500_dec_-3.307300.csv
09:35:27 - INFO - Cleaning 263 sources
09:35:27 - WARNING - Filter column 'u' not found in output catalog; available columns: ['RA', 'DEC', 'x_pix', 'y_pix', 'g', 'g_err', 'i', 'i_err', 'r', 'r_err', 'z',
  'z_err']
09:35:27 - INFO - 263 sources in output catalog
09:35:27 - INFO - Border filtering: removed 233 sources outside border, 30 sources remaining
09:35:27 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:35:27 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260215_bkg_sub_APT.fits (default) —

09:35:27 - INFO - Using FWHM = 5.0 pixels to construct the SExtractor convolution kernel
09:35:27 - INFO - Creating convolution kernel with FWHM: 5.0 pixels
09:35:27 - INFO - Initial source count: 61
09:35:27 - INFO - Rejected 16 sources outside FWHM range [1.1, 100.0]
09:35:27 - INFO - Estimated FWHM: 5.63 pixels (sigma = 1.96 pixels)
09:35:27 - INFO - Rejected 1 sources with FLAGS > 2
09:35:27 - INFO - Filtering completed in 0.002 s (retained 44 of 61 initial sources)
09:35:27 - INFO - Filtered from 61 to 44 point sources
09:35:27 - INFO - Found 44 point sources, robust FWHM 5.73 px; scale = 17.0 (FWHM x 3.00 from source_detection / config)
09:35:27 - INFO -
— SExtractor: EP260131a_u_wcs_ultracam_20260215_bkg_sub_APT.fits (default) —

09:35:27 - INFO - Using FWHM = 5.7 pixels to construct the SExtractor convolution kernel
09:35:27 - INFO - Creating convolution kernel with FWHM: 5.7 pixels
09:35:27 - INFO - Initial source count: 47
09:35:27 - INFO - Rejected 10 sources outside FWHM range [1.1, 100.0]
09:35:27 - INFO - Estimated FWHM: 5.84 pixels (sigma = 2.30 pixels)
09:35:27 - INFO - Filtering completed in 0.003 s (retained 37 of 47 initial sources)
09:35:27 - INFO - Filtered from 47 to 37 point sources
09:35:27 - INFO - Found 37 point sources, robust FWHM 5.84 px; scale = 18.0 (FWHM x 3.00 from source_detection / config)
09:35:27 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:35:27 - INFO - Cleaned 37 sources to 37 with isolation distance [18]
09:35:27 - INFO -
— Recentering 37 sources —

09:35:27 - INFO - Boxsize: 19 px, Border: 26 px (annulus outer=26.0, undersampled=False)
09:35:27 - INFO - Recentering 32 sources within border
09:35:27 - INFO - 32 sources have valid cutouts
09:35:27 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:27 - INFO - Median pixel correction: 0.0 px
09:35:27 - INFO - Recentered 32 sources
09:35:28 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:35:28 - INFO - Excluded 7 sources based on quality cuts (kept 25/32).
09:35:28 - INFO - Number of sources: 17
09:35:28 - INFO -
— Optimum aperture: 17 sources —

09:35:28 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:35:28 - INFO - Using 16 sources with stable profiles for optimum-radius and PSF selection.
09:35:28 - INFO - Final tail screen was over-restrictive; rescued to 8 sources.
09:35:28 - INFO - Returning 8 sources, optimum radius: 1.13 * FWHM, scale: 19.5
09:35:28 - INFO - Aperture radius: 7.00 [pixels] (optimum_radius=1.13 FWHM)
09:35:28 - INFO - Computing aperture correction using 8 isolated sources at radius 7.00 pixels
09:35:28 - INFO - Aperture correction: -0.075 +/- 0.009
09:35:28 - INFO - Aperture correction (AP to total): -0.075 +/- 0.009 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:35:28 - INFO - Found 30 sources in field
09:35:28 - INFO -
— Recentering 30 sources —

09:35:28 - INFO - Boxsize: 9 px, Border: 24 px (annulus outer=23.1, undersampled=False)
09:35:28 - INFO - Recentering 28 sources within border
09:35:28 - INFO - 28 sources have valid cutouts
09:35:28 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:28 - INFO - Median pixel correction: 0.0 px
09:35:28 - INFO - Recentered 28 sources
09:35:28 - INFO -
— Aperture photometry: 28 field sources —

09:35:29 - INFO - Instrumental magnitude of 27 sources measured
09:35:29 - INFO - Downsampling skipped: 28 sources (<= 300 target).
09:35:29 - INFO - Building ePSF from 8 sources
09:35:29 - INFO - Small PSF-candidate pool (8): relaxed cuts to saturate_frac=0.97
09:35:29 - INFO - FWHM=5.37 pix  recenter=centroid_com  oversample=1x
09:35:29 - INFO - Initial sources: 8
09:35:29 - INFO - Sources after cuts: 8
09:35:29 - INFO - Using 8/8 PSF candidates after spatial downselection
09:35:29 - INFO - [robust_extract_stars] Extracted 8 cutouts
09:35:29 - INFO - FFT outlier rejection would leave too few stars (7/8); keeping original set.
09:35:29 - INFO - PSF build FWHM: input=5.84 px, used=5.37 px; normalisation radius=7.00 px (same as photometry aperture_radius); oversample=x1
09:35:29 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=8, after_cuts=8, used_after_uniform=8
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.97
  geometry: fwhm_input=5.84px, fwhm_used=5.37px, fwhm_arcsec=1.91", pixel_scale=0.355 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=11px, fit_box=13px, cutout=53px
  normalization: aperture_radius=7.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:35:29 - INFO - PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 13 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 53 px, sigma_clip=4.00
  (15 iters)
09:35:29 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=6.78969 px, size=53x53
09:35:30 - INFO - PSF sources roundness: 0.08 +/- 0.01
09:35:30 - INFO -
— PSF photometry: 28 sources —

09:35:30 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.355 arcsec/px
    base_xy_bounds=5.64 px
    effective per tier (bright/faint/very-faint)=5.64/5.64/5.64 px
09:35:30 - INFO - Fit shapes:
    bright=(17, 17)
    faint=(15, 15)
    very-faint=(15, 15)
    xy_bounds=5.64 px
    undersampled=False
09:35:30 - INFO - Fitting 17 bright sources (LSQ)
09:35:30 - INFO - Fitting 2 faint sources (LSQ)
09:35:30 - INFO - Fitting 9 very faint sources (LSQ)
09:35:31 - INFO - LSQ retry for 2/9 problematic fits (fit_shape (15, 15) -> (17, 17), xy_bounds 5.64 -> 3.95).
09:35:31 - INFO - Fitted 28 sources in 0.38s
09:35:31 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:35:31 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:35:31 - INFO -
— Zeropoint: clean sequence stars —

09:35:31 - WARNING - Filter column 'u' not found in sources; skipping magnitude/colour clean.
09:35:31 - INFO -
— Linearity: saturation check (28 sources) —

09:35:31 - ERROR - Error in build_psf: <class 'KeyError'> in catalog.py at line 2036: "Missing required columns in catalog: ['u', 'u_err']"
09:35:31 - WARNING - Catalog linearity check failed: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types
  according to the casting rule ''safe'', proceeding with all sources
09:35:31 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:35:31 - INFO - fit_color_term: using polynomial order 1 (linear)
09:35:31 - ERROR - fit_color_term failed: KeyError in zeropoint.py:2259: 'u_err'
09:35:31 - INFO - Estimating zeropoint via sigma clipping.
09:35:31 - WARNING - AP zeropoint is not finite; writing 'unknown' to header.
09:35:31 - WARNING - PSF zeropoint is not finite; writing 'unknown' to header.
09:35:31 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:35:31 - INFO - Background mesh: fwhm=5.84 px  mesh_scale=4.00  box_size=(23, 23)  filter_size=3
09:35:31 - INFO - Local background: box_size=(23, 23)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:35:31 - INFO - Source mask contains 0 pixels (0.00% of the image) after 1 iteration(s)
09:35:31 - INFO - Local background: adding a bias of +6.84345 to the local cutout residual (and -6.84345 to the local background surface) to enforce median >= 6.84086.
  Annulus_std=3.42043, annulus_k=2.
09:35:31 - INFO - Local background: subtracted cutout median=-0.00259577; raised cutout by 6.84345 so median >= 6.84086 on 84100 pixels.
09:35:31 - INFO - Source mask contains 35291 pixels (3.37% of the image) after 2 iteration(s)
09:35:31 - INFO - Background mesh: fwhm=5.84 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:32 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:32 - INFO - Target cutout: keeping uniform bias level 6.84345 in measurement image (shifted mean enabled).
09:35:32 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:35:32 - INFO - Transient's expected location: x = 706.136 pixels, y = 521.439 pixels
09:35:32 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:35:32 - INFO - Target PSF fitting bound: 2.000 arcsec (5.64 px at 0.355 arcsec/px)
09:35:32 - INFO -
— PSF photometry: 1 sources —

09:35:32 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.355 arcsec/px
    base_xy_bounds=5.64 px
    effective per tier (bright/faint/very-faint)=5.64/5.64/5.64 px
09:35:32 - INFO - Fit shapes:
    bright=(25, 25)
    faint=(23, 23)
    very-faint=(23, 23)
    xy_bounds=5.64 px
    undersampled=False
09:35:32 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.355 arcsec/px
09:35:32 - INFO - Target PSF: after bootstrap - flux_all[0]=94.4, x_all[0]=36, y_all[0]=36, valid=True
09:35:32 - INFO - Target PSF: using aperture-matched local background annulus (r_in=12.00 px, r_out=24.00 px, estimator=median).
09:35:32 - INFO - Fitting 1 very faint sources (LSQ)
09:35:32 - INFO - LSQ retry for 1/1 problematic fits (fit_shape (23, 23) -> (25, 25), xy_bounds 5.64 -> 3.95).
09:35:32 - INFO - Fitted 1 sources in 0.25s
09:35:32 - INFO - Target background debug: sky_bkg_total=1035.58  noiseSky=0.139718
09:35:32 - INFO - Converting cutout-local to full-image: cutout_x0=670.14, cutout_y0=485.44
09:35:32 - INFO -   x_pix: 36.000 -> 706.136
09:35:32 - INFO -   y_pix: 36.000 -> 521.439
09:35:32 - INFO -   x_fit: 33.514 -> 703.650
09:35:32 - INFO -   y_fit: 32.778 -> 518.217
09:35:33 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 5159, in run_photometry
    from photutils.psf import decode_psf_flags
ImportError: cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Processing:  33%|███▎      | 4/12 [00:46<01:35, 11.91s/file]

[4/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_u_wcs_ultracam_20260215_bkg_sub.fits

09:35:35 - INFO -
— File: EP260131a_r_wcs_ultracam_20260222_APT.fits —

09:35:35 - INFO - Full path: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_r_wcs_ultracam_20260222/EP260131a_r_wcs_ultracam_20260222_APT.fits
09:35:35 - INFO - Start time: 2026-05-18 09:35:35.592809
09:35:35 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:35:35 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:35:35 - INFO - Exposure time: 31.159 s (header keyword EXPTIME)
09:35:35 - INFO - Pixel scale from WCS: 0.357 arcsec/pixel
09:35:35 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:35:35 - INFO - Telescope: NTT
09:35:35 - INFO - Instrument: ULTRACAM
09:35:35 - INFO - Filter: r
09:35:35 - INFO - MJD: 61178.400
09:35:35 - INFO - Read noise: 0.000 e/pixel
09:35:35 - INFO - Saturation level: inf ADU
09:35:35 - INFO - Pixel scale: 0.357 arcsec/pixel
09:35:35 - INFO - Date of observation: 2026-05-18
09:35:35 - INFO -
-------------------
Image preprocessing
-------------------

09:35:35 - INFO - Target position for NaN trimming: (744.8, 524.3)
09:35:35 - INFO - NaN boundary trimming: image shape (1024, 1024)
09:35:35 - INFO - NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
09:35:35 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:35:35 - INFO - Target pixel coordinates refreshed after trimming: (744.8, 524.3)
09:35:35 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:35:35 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:35:35 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260222_APT.fits (default) —

09:35:35 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:35:35 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:35:36 - INFO - Initial source count: 525
09:35:36 - INFO - Rejected 1 sources outside FWHM range [1.1, 100.0]
09:35:36 - INFO - Rejected 1 low-SNR sources (SNR < 3.0)
09:35:36 - INFO - Estimated FWHM: 4.91 pixels (sigma = 2.57 pixels)
09:35:36 - INFO - Rejected 67 sources with FLAGS > 2
09:35:36 - INFO - Filtering completed in 0.003 s (retained 456 of 525 initial sources)
09:35:36 - INFO - Filtered from 525 to 456 point sources
09:35:36 - INFO - Found 456 point sources, robust FWHM 4.83 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:36 - INFO -
------------------------
Background: initial pass
------------------------

09:35:36 - INFO -
— Background: sky & RMS —

09:35:36 - INFO - NaN pixels: 0 (0.00%)
09:35:36 - INFO - Background regime=sparse  bright_frac=0.023  large_scale_ratio=0.082
09:35:36 - INFO - Background mesh: fwhm=4.83 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:36 - INFO - Source mask contains 295588 pixels (28.19% of the image) after 2 iteration(s)
09:35:36 - INFO - Masked fraction (total): 28.19%
09:35:36 - INFO - box_size=(65, 65)  filter_size=3
09:35:36 - INFO - Global stats - mean -9.137e-02  median -8.426e-02  std 1.215e+00
09:35:37 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:37 - INFO - Background median -4.074e-02  RMS mean 1.189e+00
09:35:37 - INFO - Preliminary FWHM: 4.8 pixels
09:35:37 - INFO - Undersampled mode: False (FWHM=4.83 px, threshold=2.50 px)
09:35:37 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:35:37 - INFO - Pre-existing WCS found in header
09:35:37 - INFO - No variable sources found in input_yaml.
09:35:37 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:35:37 - INFO -
— TNS check: Transient —

09:35:37 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:35:37 - INFO - Expected pixel position: (744.78, 524.31)
09:35:37 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:35:37 - INFO -
— Background: sky & RMS —

09:35:37 - INFO - NaN pixels: 0 (0.00%)
09:35:37 - INFO - Background regime=sparse  bright_frac=0.023  large_scale_ratio=0.082
09:35:37 - INFO - Background mesh: fwhm=4.83 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:38 - INFO - Source mask contains 295588 pixels (28.19% of the image) after 2 iteration(s)
09:35:38 - INFO - Masked fraction (total): 28.19%
09:35:38 - INFO - box_size=(65, 65)  filter_size=3
09:35:38 - INFO - Global stats - mean -9.137e-02  median -8.426e-02  std 1.215e+00
09:35:38 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:38 - INFO - Background median -4.074e-02  RMS mean 1.189e+00
09:35:42 - INFO -
---------------
Target position
---------------

09:35:42 - INFO -
— 149.9025 -3.3073 —

09:35:42 - INFO - Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (744.78, 524.31)
  Offset from image center: dx=+233.28 px, dy=+12.81 px
  Bounds: within bounds (min edge margin 278.22 px)
09:35:42 - INFO -
— 149.9025 -3.3073 —

09:35:42 - INFO -
— 149.9025 -3.3073 —

09:35:42 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:35:42 - INFO - Reusing cached background results (fpath unchanged)
09:35:42 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:35:42 - INFO -
— Catalog: sequence sources in field —

09:35:42 - INFO - Existing PAN_STARRS catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/pan_starrs/transient/Transient_r_10.0arcmins_pan_starrs_target_ra_149.902500_dec_-3.307300.csv
09:35:42 - INFO - Cleaning 10000 sources
09:35:42 - INFO - Excluding 7502 sources with no r band information
09:35:42 - INFO - 2498 sources in output catalog
09:35:42 - INFO - Border filtering: removed 1794 sources outside border, 704 sources remaining
09:35:42 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:35:42 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260222_APT.fits (default) —

09:35:42 - INFO - Using FWHM = 4.8 pixels to construct the SExtractor convolution kernel
09:35:42 - INFO - Creating convolution kernel with FWHM: 4.8 pixels
09:35:43 - INFO - Initial source count: 381
09:35:43 - INFO - Estimated FWHM: 4.95 pixels (sigma = 5.21 pixels)
09:35:43 - INFO - Rejected 55 sources with FLAGS > 2
09:35:43 - INFO - Filtering completed in 0.002 s (retained 326 of 381 initial sources)
09:35:43 - INFO - Filtered from 381 to 326 point sources
09:35:43 - INFO - Found 326 point sources, robust FWHM 4.84 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:43 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260222_APT.fits (default) —

09:35:43 - INFO - Using FWHM = 4.8 pixels to construct the SExtractor convolution kernel
09:35:43 - INFO - Creating convolution kernel with FWHM: 4.8 pixels
09:35:43 - INFO - Initial source count: 381
09:35:43 - INFO - Estimated FWHM: 4.95 pixels (sigma = 5.22 pixels)
09:35:43 - INFO - Rejected 55 sources with FLAGS > 2
09:35:43 - INFO - Filtering completed in 0.002 s (retained 326 of 381 initial sources)
09:35:43 - INFO - Filtered from 381 to 326 point sources
09:35:43 - INFO - Found 326 point sources, robust FWHM 4.87 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:43 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:35:43 - INFO - Cleaned 326 sources to 292 with isolation distance [15]
09:35:43 - INFO -
— Recentering 292 sources —

09:35:43 - INFO - Boxsize: 15 px, Border: 22 px (annulus outer=21.7, undersampled=False)
09:35:43 - INFO - Recentering 279 sources within border
09:35:43 - INFO - 279 sources have valid cutouts
09:35:43 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:43 - INFO - Median pixel correction: 0.0 px
09:35:43 - INFO - Recentered 279 sources
09:35:43 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:35:43 - INFO - Excluded 44 sources based on quality cuts (kept 235/279).
09:35:43 - INFO - Number of sources: 75
09:35:43 - INFO -
— Optimum aperture: 75 sources —

09:35:43 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:35:44 - INFO - Concentration gate rejected 4 broad sources (enc_flux(1.70*FWHM) < 0.50).
09:35:44 - INFO - Using 55 sources with stable profiles for optimum-radius and PSF selection.
09:35:44 - INFO - Final tail screen was over-restrictive; rescued to 19 sources.
09:35:44 - INFO - Returning 19 sources, optimum radius: 1.05 * FWHM, scale: 15.5
09:35:44 - INFO - Aperture radius: 7.00 [pixels] (optimum_radius=1.05 FWHM)
09:35:44 - INFO - Computing aperture correction using 19 isolated sources at radius 7.00 pixels
09:35:44 - INFO - Aperture correction: -0.044 +/- 0.007
09:35:44 - INFO - Aperture correction (AP to total): -0.044 +/- 0.007 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:35:44 - INFO - Found 704 sources in field
09:35:44 - INFO -
— Recentering 704 sources —

09:35:44 - INFO - Boxsize: 7 px, Border: 21 px (annulus outer=20.4, undersampled=False)
09:35:44 - INFO - Recentering 672 sources within border
09:35:44 - INFO - 672 sources have valid cutouts
09:35:44 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:44 - INFO - Failed to recenter 4 sources - ignoring
09:35:44 - INFO - Median pixel correction: 0.0 px
09:35:44 - INFO - Recentered 668 sources
09:35:44 - INFO -
— Aperture photometry: 668 field sources —

09:35:45 - INFO - Instrumental magnitude of 417 sources measured
09:35:45 - INFO -
— Downsampling: 668 sources -> 300 max —

09:35:45 - INFO - Using 17x17 grid with ~1 sources per bin
09:35:45 - INFO - Processing spatial bins...
09:35:45 - INFO - Bin statistics: min=0, max=11, avg=2.3 sources per bin
09:35:45 - INFO - Selected 218 sources from spatial bins
09:35:45 - WARNING - Only 218 sources selected from bins, filling with top 82 remaining sources
09:35:45 - INFO - Added 82 additional sources from remaining pool
09:35:45 - INFO - Final selection: 300 sources
09:35:45 - INFO - Downsampling complete
09:35:45 - INFO - Building ePSF from 19 sources
09:35:45 - INFO - Small PSF-candidate pool (19): relaxed cuts to saturate_frac=0.97
09:35:45 - INFO - FWHM=3.88 pix  recenter=centroid_com  oversample=1x
09:35:45 - INFO - Initial sources: 19
09:35:45 - INFO - Sources after cuts: 19
09:35:45 - INFO - Using 19/19 PSF candidates after spatial downselection
09:35:45 - INFO - [robust_extract_stars] Extracted 19 cutouts
09:35:45 - INFO - Rejected 6 PSF stars via FFT outlier filtering
09:35:45 - INFO - PSF build FWHM: input=4.87 px, used=3.88 px; normalisation radius=7.00 px (same as photometry aperture_radius); oversample=x1
09:35:45 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=19, after_cuts=19, used_after_uniform=19
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.97
  geometry: fwhm_input=4.87px, fwhm_used=3.88px, fwhm_arcsec=1.38", pixel_scale=0.357 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=9px, fit_box=9px, cutout=39px
  normalization: aperture_radius=7.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:35:45 - INFO - PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 9 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 39 px, sigma_clip=4.00
  (15 iters)
09:35:45 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=4.90389 px, size=39x39
09:35:46 - INFO - PSF sources roundness: 0.05 +/- 0.03
09:35:46 - INFO -
— PSF photometry: 300 sources —

09:35:46 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.357 arcsec/px
    base_xy_bounds=5.61 px
    effective per tier (bright/faint/very-faint)=5.61/5.4/5.4 px
09:35:46 - INFO - Fit shapes:
    bright=(15, 15)
    faint=(13, 13)
    very-faint=(13, 13)
    xy_bounds=5.61 px
    undersampled=False
09:35:46 - INFO - Fitting 201 bright sources (LSQ)
09:35:48 - INFO - Fitting 15 faint sources (LSQ)
09:35:48 - INFO - LSQ retry for 2/15 problematic fits (fit_shape (13, 13) -> (15, 15), xy_bounds 5.40 -> 3.78).
09:35:48 - INFO - Fitting 84 very faint sources (LSQ)
09:35:49 - INFO - LSQ retry for 58/84 problematic fits (fit_shape (13, 13) -> (15, 15), xy_bounds 5.40 -> 3.78).
09:35:50 - INFO - Fitted 300 sources in 3.89s
09:35:50 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:35:50 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:35:50 - INFO -
— Zeropoint: clean sequence stars —

09:35:50 - INFO - Removing 55 sources with detection threshold < 3.0
09:35:50 - INFO - Removing 60 sources with FLAGS > 2 from zeropoint calibration.
09:35:50 - INFO - Removing 64 sources with |inst_AP - inst_PSF| > 0.50 mag from zeropoint calibration.
09:35:50 - INFO - 205 sources remaining after quality cuts
09:35:50 - INFO -
— Linearity: saturation check (205 sources) —

09:35:50 - INFO - Removing 8 sources with threshold < 5
09:35:50 - INFO - Selected 16 high S/N sources (SNR >= 100) for linearity fit
09:35:50 - INFO - Post-RANSAC sigma clipping removed 4 additional outliers
09:35:50 - INFO - Constrained fit results:  Zeropoint = 25.079 +/- 0.038
09:35:50 - INFO - Linearity range (0.5-95% flux percentiles): 721.0 - 9209.3
09:35:50 - INFO - Returning 12 linear sources
09:35:50 - INFO - Catalog linearity check: 12 linear sources, ZP=25.079 +/- 0.038
09:35:50 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:35:50 - INFO - fit_color_term: using polynomial order 1 (linear)
09:35:50 - INFO - fit_color_term: color distribution before filtering: min=0.307, max=1.202, median=0.551, n_sources=12
09:35:50 - INFO - fit_color_term: RANSAC found 12 inliers
09:35:50 - INFO - fit_color_term: fitted linear color term: slope=0.0179, intercept=25.0659, n_inliers=12, color_range=0.894 mag
09:35:50 - INFO - Estimating zeropoint via sigma clipping.
09:35:50 - INFO - [AP] Before color correction: ZP=25.079, std=0.010, color_term=0.0179
09:35:50 - INFO - [AP] Zeropoint: 25.069 +/- 0.003 mag
09:35:50 - INFO - [PSF] Before color correction: ZP=25.107, std=0.016, color_term=0.0179
09:35:50 - INFO - [PSF] Zeropoint: 25.098 +/- 0.010 mag
09:35:50 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:35:50 - INFO - Background mesh: fwhm=4.87 px  mesh_scale=4.00  box_size=(19, 19)  filter_size=3
09:35:50 - INFO - Local background: box_size=(19, 19)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:35:50 - INFO - Source mask contains 4387 pixels (7.49% of the image) after 2 iteration(s)
09:35:50 - INFO - Local background: adding a bias of +2.22314 to the local cutout residual (and -2.22314 to the local background surface) to enforce median >= 2.23049.
  Annulus_std=1.11525, annulus_k=2.
09:35:50 - INFO - Local background: subtracted cutout median=0.00735091; raised cutout by 2.22314 so median >= 2.23049 on 54177 pixels.
09:35:51 - INFO - Source mask contains 428601 pixels (40.87% of the image) after 2 iteration(s)
09:35:51 - INFO - Background mesh: fwhm=4.87 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:51 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:51 - INFO - Target cutout: keeping uniform bias level 2.22314 in measurement image (shifted mean enabled).
09:35:51 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:35:51 - INFO - Transient's expected location: x = 744.776 pixels, y = 524.309 pixels
09:35:51 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:35:51 - INFO - Target PSF fitting bound: 2.000 arcsec (5.61 px at 0.357 arcsec/px)
09:35:51 - INFO -
— PSF photometry: 1 sources —

09:35:51 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.357 arcsec/px
    base_xy_bounds=5.61 px
    effective per tier (bright/faint/very-faint)=5.61/5.61/5.61 px
09:35:51 - INFO - Fit shapes:
    bright=(23, 23)
    faint=(19, 19)
    very-faint=(19, 19)
    xy_bounds=5.61 px
    undersampled=False
09:35:51 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.357 arcsec/px
09:35:51 - INFO - Target PSF: after bootstrap - flux_all[0]=561, x_all[0]=30, y_all[0]=29, valid=True
09:35:52 - INFO - Target PSF: using aperture-matched local background annulus (r_in=11.00 px, r_out=21.00 px, estimator=median).
09:35:52 - INFO - Fitting 1 bright sources (LSQ)
09:35:52 - INFO - Fitted 1 sources in 0.05s
09:35:52 - INFO - Target background debug: sky_bkg_total=345.217  noiseSky=0.0376168
09:35:52 - INFO - Converting cutout-local to full-image: cutout_x0=714.78, cutout_y0=495.31
09:35:52 - INFO -   x_pix: 30.000 -> 744.776
09:35:52 - INFO -   y_pix: 29.000 -> 524.309
09:35:52 - INFO -   x_fit: 27.586 -> 742.362
09:35:52 - INFO -   y_fit: 34.608 -> 529.918
09:35:52 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 5159, in run_photometry
    from photutils.psf import decode_psf_flags
ImportError: cannot import name 'decode_psf_flags' from 'photutils.psf'

[5/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_r_wcs_ultracam_20260222.fits

09:35:54 - INFO -
— File: EP260131a_r_wcs_ultracam_20260220_APT.fits —

09:35:54 - INFO - Full path: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_r_wcs_ultracam_20260220/EP260131a_r_wcs_ultracam_20260220_APT.fits
09:35:54 - INFO - Start time: 2026-05-18 09:35:54.927706
09:35:54 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:35:54 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:35:54 - INFO - Exposure time: 25.001 s (header keyword EXPTIME)
09:35:55 - INFO - Pixel scale from WCS: 0.713 arcsec/pixel
09:35:55 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:35:55 - INFO - Telescope: NTT
09:35:55 - INFO - Instrument: ULTRACAM
09:35:55 - INFO - Filter: r
09:35:55 - INFO - MJD: 61178.400
09:35:55 - INFO - Read noise: 0.000 e/pixel
09:35:55 - INFO - Saturation level: inf ADU
09:35:55 - INFO - Pixel scale: 0.713 arcsec/pixel
09:35:55 - INFO - Date of observation: 2026-05-18
09:35:55 - INFO -
-------------------
Image preprocessing
-------------------

09:35:55 - INFO - Target position for NaN trimming: (366.9, 260.4)
09:35:55 - INFO - NaN boundary trimming: image shape (512, 512)
09:35:55 - INFO - NaN boundary trimming: 0/262144 pixels are NaN (0.0%)
09:35:55 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:35:55 - INFO - Target pixel coordinates refreshed after trimming: (366.9, 260.4)
09:35:55 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:35:55 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:35:55 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260220_APT.fits (default) —

09:35:55 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:35:55 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:35:55 - INFO - Initial source count: 177
09:35:55 - INFO - Rejected 1 sources outside FWHM range [1.1, 100.0]
09:35:55 - INFO - Estimated FWHM: 2.58 pixels (sigma = 2.81 pixels)
09:35:55 - INFO - Rejected 24 sources with FLAGS > 2
09:35:55 - INFO - Filtering completed in 0.003 s (retained 152 of 177 initial sources)
09:35:55 - INFO - Filtered from 177 to 152 point sources
09:35:55 - INFO - Found 152 point sources, robust FWHM 2.54 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:55 - INFO -
------------------------
Background: initial pass
------------------------

09:35:55 - INFO -
— Background: sky & RMS —

09:35:55 - INFO - NaN pixels: 0 (0.00%)
09:35:55 - INFO - Background regime=sparse  bright_frac=0.005  large_scale_ratio=0.074
09:35:55 - INFO - Background mesh: fwhm=2.54 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:55 - INFO - Source mask contains 15741 pixels (6.00% of the image) after 2 iteration(s)
09:35:55 - INFO - Masked fraction (total): 6.00%
09:35:55 - INFO - box_size=(65, 65)  filter_size=3
09:35:55 - INFO - Global stats - mean 6.582e+02  median 6.634e+02  std 2.119e+01
09:35:55 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:55 - INFO - Background median 6.628e+02  RMS mean 6.856e+00
09:35:55 - INFO - Preliminary FWHM: 2.5 pixels
09:35:55 - INFO - Undersampled mode: False (FWHM=2.54 px, threshold=2.50 px)
09:35:55 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:35:55 - INFO - Pre-existing WCS found in header
09:35:55 - INFO - No variable sources found in input_yaml.
09:35:55 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:35:55 - INFO -
— TNS check: Transient —

09:35:55 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:35:55 - INFO - Expected pixel position: (366.93, 260.44)
09:35:55 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:35:55 - INFO -
— Background: sky & RMS —

09:35:55 - INFO - NaN pixels: 0 (0.00%)
09:35:55 - INFO - Background regime=sparse  bright_frac=0.005  large_scale_ratio=0.074
09:35:55 - INFO - Background mesh: fwhm=2.54 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:35:55 - INFO - Source mask contains 15741 pixels (6.00% of the image) after 2 iteration(s)
09:35:55 - INFO - Masked fraction (total): 6.00%
09:35:55 - INFO - box_size=(65, 65)  filter_size=3
09:35:55 - INFO - Global stats - mean 6.582e+02  median 6.634e+02  std 2.119e+01
09:35:55 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:35:55 - INFO - Background median 6.628e+02  RMS mean 6.856e+00
09:35:56 - INFO -
---------------
Target position
---------------

09:35:56 - INFO -
— 149.9025 -3.3073 —

09:35:56 - INFO - Target summary:
  Name: Transient
  Image size: 512 x 512 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (366.93, 260.44)
  Offset from image center: dx=+111.43 px, dy=+4.94 px
  Bounds: within bounds (min edge margin 144.07 px)
09:35:56 - INFO -
— 149.9025 -3.3073 —

09:35:56 - INFO -
— 149.9025 -3.3073 —

09:35:56 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:35:56 - INFO - Reusing cached background results (fpath unchanged)
09:35:56 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:35:56 - INFO -
— Catalog: sequence sources in field —

09:35:56 - INFO - Existing PAN_STARRS catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/pan_starrs/transient/Transient_r_10.0arcmins_pan_starrs_target_ra_149.902500_dec_-3.307300.csv
09:35:56 - INFO - Cleaning 10000 sources
09:35:56 - INFO - Excluding 7502 sources with no r band information
09:35:56 - INFO - 2498 sources in output catalog
09:35:56 - INFO - Border filtering: removed 1833 sources outside border, 665 sources remaining
09:35:56 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:35:56 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260220_APT.fits (default) —

09:35:56 - INFO - Using FWHM = 2.5 pixels to construct the SExtractor convolution kernel
09:35:56 - INFO - Creating convolution kernel with FWHM: 2.5 pixels
09:35:56 - INFO - Initial source count: 180
09:35:56 - INFO - Estimated FWHM: 2.58 pixels (sigma = 3.28 pixels)
09:35:56 - INFO - Rejected 23 sources with FLAGS > 2
09:35:56 - INFO - Filtering completed in 0.002 s (retained 157 of 180 initial sources)
09:35:56 - INFO - Filtered from 180 to 157 point sources
09:35:56 - INFO - Found 157 point sources, robust FWHM 2.56 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:56 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260220_APT.fits (default) —

09:35:56 - INFO - Using FWHM = 2.6 pixels to construct the SExtractor convolution kernel
09:35:56 - INFO - Creating convolution kernel with FWHM: 2.6 pixels
09:35:56 - INFO - Initial source count: 180
09:35:56 - INFO - Estimated FWHM: 2.58 pixels (sigma = 3.28 pixels)
09:35:56 - INFO - Rejected 23 sources with FLAGS > 2
09:35:56 - INFO - Filtering completed in 0.002 s (retained 157 of 180 initial sources)
09:35:56 - INFO - Filtered from 180 to 157 point sources
09:35:56 - INFO - Found 157 point sources, robust FWHM 2.56 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:35:56 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:35:56 - INFO - Cleaned 157 sources to 113 with isolation distance [15]
09:35:56 - INFO -
— Recentering 113 sources —

09:35:56 - INFO - Boxsize: 15 px, Border: 15 px (annulus outer=11.4, undersampled=False)
09:35:56 - INFO - Recentering 109 sources within border
09:35:56 - INFO - 109 sources have valid cutouts
09:35:56 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:56 - INFO - Median pixel correction: 0.0 px
09:35:56 - INFO - Recentered 109 sources
09:35:56 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:35:56 - INFO - Excluded 28 sources based on quality cuts (kept 81/109).
09:35:56 - INFO - Number of sources: 43
09:35:56 - INFO -
— Optimum aperture: 43 sources —

09:35:56 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:35:57 - INFO - Concentration gate rejected 5 broad sources (enc_flux(1.70*FWHM) < 0.50).
09:35:57 - INFO - Using 34 sources with stable profiles for optimum-radius and PSF selection.
09:35:57 - INFO - Returning 15 sources, optimum radius: 1.09 * FWHM, scale: 12.5
09:35:57 - INFO - Aperture radius: 3.00 [pixels] (optimum_radius=1.09 FWHM)
09:35:57 - INFO - Computing aperture correction using 15 isolated sources at radius 3.00 pixels
09:35:57 - INFO - Aperture correction: -0.070 +/- 0.035
09:35:57 - INFO - Aperture correction (AP to total): -0.070 +/- 0.035 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:35:57 - INFO - Found 665 sources in field
09:35:57 - INFO -
— Recentering 665 sources —

09:35:57 - INFO - Boxsize: 7 px, Border: 11 px (annulus outer=10.0, undersampled=False)
09:35:57 - INFO - Recentering 665 sources within border
09:35:57 - INFO - 665 sources have valid cutouts
09:35:57 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:35:57 - INFO - Failed to recenter 8 sources - ignoring
09:35:57 - INFO - Median pixel correction: 0.0 px
09:35:57 - INFO - Recentered 657 sources
09:35:57 - INFO -
— Aperture photometry: 657 field sources —

09:35:57 - INFO - Instrumental magnitude of 422 sources measured
09:35:57 - INFO -
— Downsampling: 647 sources -> 300 max —

09:35:57 - INFO - Using 17x17 grid with ~1 sources per bin
09:35:57 - INFO - Processing spatial bins...
09:35:57 - INFO - Bin statistics: min=0, max=9, avg=2.2 sources per bin
09:35:57 - INFO - Selected 224 sources from spatial bins
09:35:57 - WARNING - Only 224 sources selected from bins, filling with top 76 remaining sources
09:35:57 - INFO - Added 76 additional sources from remaining pool
09:35:57 - INFO - Final selection: 300 sources
09:35:57 - INFO - Downsampling complete
09:35:57 - INFO - Building ePSF from 15 sources
09:35:57 - INFO - Small PSF-candidate pool (15): relaxed cuts to saturate_frac=0.97
09:35:57 - INFO - Image appears undersampled (FWHM=2.08 pix) and psf_oversample=1; consider increasing psf_oversample in the config if enough PSF stars are available.
09:35:57 - INFO - Undersampled regime (FWHM <= 2.50 px): disabling strict threshold/SNR candidate cuts for PSF build.
09:35:57 - INFO - FWHM=2.08 pix  recenter=centroid_2dg  oversample=1x
09:35:57 - INFO - Initial sources: 15
09:35:57 - INFO - Sources after cuts: 15
09:35:57 - INFO - Using 15/15 PSF candidates after spatial downselection
09:35:57 - INFO - [robust_extract_stars] Extracted 15 cutouts
09:35:57 - INFO - FFT outlier rejection would leave too few stars (9/15); keeping original set.
09:35:57 - INFO - PSF build FWHM: input=2.56 px, used=2.08 px; normalisation radius=3.00 px (same as photometry aperture_radius); oversample=x1
09:35:57 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=15, after_cuts=15, used_after_uniform=15
  selection cuts: min_candidates=8, threshold_limit=nan, SNR_limit=[0.0, 1000000000000.0], min_keep_frac_after_cut=0.30, saturate_frac=0.97
  geometry: fwhm_input=2.56px, fwhm_used=2.08px, fwhm_arcsec=1.48", pixel_scale=0.713 arcsec/px, build_sampling_boost=1.20, oversample=x1,
    recenter=centroid_2dg, cen_box=7px, fit_box=7px, cutout=27px
  normalization: aperture_radius=3.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:35:57 - INFO - PSF build windows: fit_box=3.00*FWHM (base 2.50, min 2.50 arcsec) -> 7 px, cutout=12.00*FWHM (base 10.00, min 9.00 arcsec) -> 27 px, sigma_clip=4.00
  (15 iters)
09:35:57 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=2.6271 px, size=27x27
09:35:59 - INFO - PSF sources roundness: 0.02 +/- 0.01
09:35:59 - INFO -
— PSF photometry: 300 sources —

09:35:59 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.713 arcsec/px
    base_xy_bounds=2.8 px
    effective per tier (bright/faint/very-faint)=2.7/2.7/2.7 px
09:35:59 - INFO - Fit shapes:
    bright=(7, 7)
    faint=(7, 7)
    very-faint=(7, 7)
    xy_bounds=2.8 px
    undersampled=False
09:35:59 - INFO - Fitting 170 bright sources (LSQ)
09:35:59 - INFO - Fitting 22 faint sources (LSQ)
09:36:00 - INFO - Fitting 108 very faint sources (LSQ)
09:36:01 - INFO - LSQ retry for 35/108 problematic fits (fit_shape (7, 7) -> (9, 9), xy_bounds 2.70 -> 1.89).
09:36:02 - INFO - Fitted 300 sources in 3.70s
09:36:02 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:36:02 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:36:02 - INFO -
— Zeropoint: clean sequence stars —

09:36:02 - INFO - Removing 95 sources with detection threshold < 3.0
09:36:02 - INFO - Removing 35 sources with FLAGS > 2 from zeropoint calibration.
09:36:02 - INFO - Removing 44 sources with |inst_AP - inst_PSF| > 0.50 mag from zeropoint calibration.
09:36:02 - INFO - 186 sources remaining after quality cuts
09:36:02 - INFO -
— Linearity: saturation check (186 sources) —

09:36:02 - INFO - Removing 11 sources with threshold < 5
09:36:02 - INFO - Selected 17 high S/N sources (SNR >= 75) for linearity fit
09:36:02 - INFO - Post-RANSAC sigma clipping removed 3 additional outliers
09:36:02 - INFO - Constrained fit results:  Zeropoint = 25.082 +/- 0.034
09:36:02 - INFO - Linearity range (0.5-95% flux percentiles): 279.9 - 9154.1
09:36:02 - INFO - Applying tight residual filter: removed 8 sources
09:36:02 - INFO - Returning 188 linear sources
09:36:02 - INFO - Catalog linearity check: 14 linear sources, ZP=25.082 +/- 0.034
09:36:02 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:36:02 - INFO - fit_color_term: using polynomial order 1 (linear)
09:36:02 - INFO - fit_color_term: color distribution before filtering: min=0.307, max=1.335, median=0.605, n_sources=188
09:36:02 - INFO - fit_color_term: RANSAC found 188 inliers
09:36:02 - INFO - fit_color_term: fitted linear color term: slope=0.0328, intercept=25.0600, n_inliers=188, color_range=1.027 mag
09:36:02 - INFO - Estimating zeropoint via sigma clipping.
09:36:02 - INFO - [AP] Before color correction: ZP=25.082, std=0.012, color_term=0.0328
09:36:02 - INFO - [AP] Zeropoint: 25.060 +/- 0.002 mag
09:36:02 - INFO - [PSF] Before color correction: ZP=25.165, std=0.010, color_term=0.0328
09:36:02 - INFO - [PSF] Zeropoint: 25.146 +/- 0.001 mag
09:36:03 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:36:03 - INFO - Background mesh: fwhm=2.56 px  mesh_scale=4.00  box_size=(11, 11)  filter_size=3
09:36:03 - INFO - Local background: box_size=(11, 11)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:36:03 - INFO - Source mask contains 823 pixels (5.02% of the image) after 2 iteration(s)
09:36:03 - INFO - Local background: adding a bias of +9.55501 to the local cutout residual (and -9.55501 to the local background surface) to enforce median >= 9.56822.
  Annulus_std=4.78411, annulus_k=2.
09:36:03 - INFO - Local background: subtracted cutout median=0.0132111; raised cutout by 9.55501 so median >= 9.56822 on 15561 pixels.
09:36:03 - INFO - Source mask contains 43291 pixels (16.51% of the image) after 2 iteration(s)
09:36:03 - INFO - Background mesh: fwhm=2.56 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:03 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:03 - INFO - Target cutout: keeping uniform bias level 9.55501 in measurement image (shifted mean enabled).
09:36:03 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:36:03 - INFO - Transient's expected location: x = 366.930 pixels, y = 260.444 pixels
09:36:03 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:36:03 - INFO - Target PSF fitting bound: 2.000 arcsec (2.80 px at 0.713 arcsec/px)
09:36:03 - INFO -
— PSF photometry: 1 sources —

09:36:03 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.713 arcsec/px
    base_xy_bounds=2.8 px
    effective per tier (bright/faint/very-faint)=2.8/2.8/2.8 px
09:36:03 - INFO - Fit shapes:
    bright=(11, 11)
    faint=(11, 11)
    very-faint=(11, 11)
    xy_bounds=2.8 px
    undersampled=False
09:36:03 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.713 arcsec/px
09:36:03 - INFO - Target PSF: after bootstrap - flux_all[0]=242, x_all[0]=21, y_all[0]=20, valid=True
09:36:03 - INFO - Target PSF: using aperture-matched local background annulus (r_in=5.00 px, r_out=11.00 px, estimator=median).
09:36:03 - INFO - Fitting 1 faint sources (LSQ)
09:36:03 - INFO - Fitted 1 sources in 0.02s
09:36:03 - INFO - Target background debug: sky_bkg_total=261.655  noiseSky=0.230205
09:36:03 - INFO - Converting cutout-local to full-image: cutout_x0=345.93, cutout_y0=240.44
09:36:03 - INFO -   x_pix: 21.000 -> 366.930
09:36:03 - INFO -   y_pix: 20.000 -> 260.444
09:36:03 - INFO -   x_fit: 21.386 -> 367.316
09:36:03 - INFO -   y_fit: 20.072 -> 260.516
09:36:03 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 5159, in run_photometry
    from photutils.psf import decode_psf_flags

[6/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_r_wcs_ultracam_20260220.fits

09:36:06 - INFO -
— File: EP260131a_r_wcs_ultracam_20260219_APT.fits —

09:36:06 - INFO - Full path: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_r_wcs_ultracam_20260219/EP260131a_r_wcs_ultracam_20260219_APT.fits
09:36:06 - INFO - Start time: 2026-05-18 09:36:06.564145
09:36:06 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:36:06 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:36:06 - INFO - Exposure time: 31.159 s (header keyword EXPTIME)
09:36:06 - INFO - Pixel scale from WCS: 0.357 arcsec/pixel
09:36:06 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:36:06 - INFO - Telescope: NTT
09:36:06 - INFO - Instrument: ULTRACAM
09:36:06 - INFO - Filter: r
09:36:06 - INFO - MJD: 61178.400
09:36:06 - INFO - Read noise: 0.000 e/pixel
09:36:06 - INFO - Saturation level: inf ADU
09:36:06 - INFO - Pixel scale: 0.357 arcsec/pixel
09:36:06 - INFO - Date of observation: 2026-05-18
09:36:06 - INFO -
-------------------
Image preprocessing
-------------------

09:36:06 - INFO - Target position for NaN trimming: (731.8, 527.7)
09:36:06 - INFO - NaN boundary trimming: image shape (1024, 1024)
09:36:06 - INFO - NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
09:36:06 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:36:06 - INFO - Target pixel coordinates refreshed after trimming: (731.8, 527.7)
09:36:06 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:36:06 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:36:06 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260219_APT.fits (default) —

09:36:06 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:36:06 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:36:06 - INFO - Initial source count: 413
09:36:06 - INFO - Rejected 2 sources outside FWHM range [1.1, 100.0]
09:36:06 - INFO - Rejected 2 low-SNR sources (SNR < 3.0)
09:36:06 - INFO - Estimated FWHM: 5.16 pixels (sigma = 3.98 pixels)
09:36:06 - INFO - Rejected 53 sources with FLAGS > 2
09:36:06 - INFO - Filtering completed in 0.003 s (retained 356 of 413 initial sources)
09:36:06 - INFO - Filtered from 413 to 356 point sources
09:36:06 - INFO - Found 356 point sources, robust FWHM 5.08 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:36:06 - INFO -
------------------------
Background: initial pass
------------------------

09:36:06 - INFO -
— Background: sky & RMS —

09:36:06 - INFO - NaN pixels: 0 (0.00%)
09:36:07 - INFO - Background regime=sparse  bright_frac=0.006  large_scale_ratio=0.098
09:36:07 - INFO - Background mesh: fwhm=5.08 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:07 - INFO - Source mask contains 82658 pixels (7.88% of the image) after 2 iteration(s)
09:36:07 - INFO - Masked fraction (total): 7.88%
09:36:07 - INFO - box_size=(65, 65)  filter_size=3
09:36:07 - INFO - Global stats - mean 2.374e+02  median 2.389e+02  std 5.528e+00
09:36:08 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:08 - INFO - Background median 2.382e+02  RMS mean 1.686e+00
09:36:08 - INFO - Preliminary FWHM: 5.1 pixels
09:36:08 - INFO - Undersampled mode: False (FWHM=5.08 px, threshold=2.50 px)
09:36:08 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:36:08 - INFO - Pre-existing WCS found in header
09:36:08 - INFO - No variable sources found in input_yaml.
09:36:08 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:36:08 - INFO -
— TNS check: Transient —

09:36:08 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:36:08 - INFO - Expected pixel position: (731.79, 527.69)
09:36:08 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:36:08 - INFO -
— Background: sky & RMS —

09:36:08 - INFO - NaN pixels: 0 (0.00%)
09:36:08 - INFO - Background regime=sparse  bright_frac=0.006  large_scale_ratio=0.098
09:36:08 - INFO - Background mesh: fwhm=5.08 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:09 - INFO - Source mask contains 82658 pixels (7.88% of the image) after 2 iteration(s)
09:36:09 - INFO - Masked fraction (total): 7.88%
09:36:09 - INFO - box_size=(65, 65)  filter_size=3
09:36:09 - INFO - Global stats - mean 2.374e+02  median 2.389e+02  std 5.528e+00
09:36:09 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:09 - INFO - Background median 2.382e+02  RMS mean 1.686e+00
09:36:11 - INFO -
---------------
Target position
---------------

09:36:11 - INFO -
— 149.9025 -3.3073 —

09:36:11 - INFO - Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (731.79, 527.69)
  Offset from image center: dx=+220.29 px, dy=+16.19 px
  Bounds: within bounds (min edge margin 291.21 px)
09:36:11 - INFO -
— 149.9025 -3.3073 —

09:36:11 - INFO -
— 149.9025 -3.3073 —

09:36:11 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:36:11 - INFO - Reusing cached background results (fpath unchanged)
09:36:11 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:36:11 - INFO -
— Catalog: sequence sources in field —

09:36:11 - INFO - Existing PAN_STARRS catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/pan_starrs/transient/Transient_r_10.0arcmins_pan_starrs_target_ra_149.902500_dec_-3.307300.csv
09:36:11 - INFO - Cleaning 10000 sources
09:36:11 - INFO - Excluding 7502 sources with no r band information
09:36:11 - INFO - 2498 sources in output catalog
09:36:11 - INFO - Border filtering: removed 1790 sources outside border, 708 sources remaining
09:36:11 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:36:11 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260219_APT.fits (default) —

09:36:11 - INFO - Using FWHM = 5.1 pixels to construct the SExtractor convolution kernel
09:36:11 - INFO - Creating convolution kernel with FWHM: 5.1 pixels
09:36:11 - INFO - Initial source count: 287
09:36:11 - INFO - Estimated FWHM: 5.27 pixels (sigma = 6.13 pixels)
09:36:11 - INFO - Rejected 40 sources with FLAGS > 2
09:36:11 - INFO - Filtering completed in 0.002 s (retained 247 of 287 initial sources)
09:36:11 - INFO - Filtered from 287 to 247 point sources
09:36:11 - INFO - Found 247 point sources, robust FWHM 5.14 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:36:11 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260219_APT.fits (default) —

09:36:11 - INFO - Using FWHM = 5.1 pixels to construct the SExtractor convolution kernel
09:36:11 - INFO - Creating convolution kernel with FWHM: 5.1 pixels
09:36:12 - INFO - Initial source count: 283
09:36:12 - INFO - Rejected 1 sources outside FWHM range [1.1, 100.0]
09:36:12 - INFO - Estimated FWHM: 5.27 pixels (sigma = 6.22 pixels)
09:36:12 - INFO - Rejected 37 sources with FLAGS > 2
09:36:12 - INFO - Filtering completed in 0.003 s (retained 245 of 283 initial sources)
09:36:12 - INFO - Filtered from 283 to 245 point sources
09:36:12 - INFO - Found 245 point sources, robust FWHM 5.17 px; scale = 16.0 (FWHM x 3.00 from source_detection / config)
09:36:12 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:36:12 - INFO - Cleaned 245 sources to 221 with isolation distance [16]
09:36:12 - INFO -
— Recentering 221 sources —

09:36:12 - INFO - Boxsize: 17 px, Border: 24 px (annulus outer=23.0, undersampled=False)
09:36:12 - INFO - Recentering 216 sources within border
09:36:12 - INFO - 216 sources have valid cutouts
09:36:12 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:36:12 - INFO - Median pixel correction: 0.0 px
09:36:12 - INFO - Recentered 216 sources
09:36:12 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:36:12 - INFO - Excluded 33 sources based on quality cuts (kept 183/216).
09:36:12 - INFO - Number of sources: 98
09:36:12 - INFO -
— Optimum aperture: 98 sources —

09:36:12 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:36:13 - INFO - Concentration gate rejected 4 broad sources (enc_flux(1.70*FWHM) < 0.50).
09:36:13 - INFO - Using 81 sources with stable profiles for optimum-radius and PSF selection.
09:36:13 - INFO - Returning 25 sources, optimum radius: 1.10 * FWHM, scale: 17.5
09:36:13 - INFO - Aperture radius: 7.00 [pixels] (optimum_radius=1.10 FWHM)
09:36:13 - INFO - Computing aperture correction using 25 isolated sources at radius 7.00 pixels
09:36:13 - INFO - Aperture correction: -0.063 +/- 0.012
09:36:13 - INFO - Aperture correction (AP to total): -0.063 +/- 0.012 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:36:13 - INFO - Found 708 sources in field
09:36:13 - INFO -
— Recentering 708 sources —

09:36:13 - INFO - Boxsize: 9 px, Border: 22 px (annulus outer=21.2, undersampled=False)
09:36:13 - INFO - Recentering 669 sources within border
09:36:13 - INFO - 669 sources have valid cutouts
09:36:13 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:36:13 - INFO - Median pixel correction: 0.0 px
09:36:13 - INFO - Recentered 669 sources
09:36:13 - INFO -
— Aperture photometry: 669 field sources —

09:36:13 - INFO - Instrumental magnitude of 397 sources measured
09:36:13 - INFO -
— Downsampling: 669 sources -> 300 max —

09:36:13 - INFO - Using 17x17 grid with ~1 sources per bin
09:36:13 - INFO - Processing spatial bins...
09:36:14 - INFO - Bin statistics: min=0, max=13, avg=2.3 sources per bin
09:36:14 - INFO - Selected 219 sources from spatial bins
09:36:14 - WARNING - Only 219 sources selected from bins, filling with top 81 remaining sources
09:36:14 - INFO - Added 81 additional sources from remaining pool
09:36:14 - INFO - Final selection: 300 sources
09:36:14 - INFO - Downsampling complete
09:36:14 - INFO - Building ePSF from 25 sources
09:36:14 - INFO - FWHM=4.12 pix  recenter=centroid_com  oversample=1x
09:36:14 - INFO - Initial sources: 25
09:36:14 - INFO - Sources after cuts: 25
09:36:14 - INFO - Using 25/25 PSF candidates after spatial downselection
09:36:14 - INFO - [robust_extract_stars] Extracted 25 cutouts
09:36:14 - INFO - Rejected 6 PSF stars via FFT outlier filtering
09:36:14 - INFO - PSF build FWHM: input=5.17 px, used=4.12 px; normalisation radius=7.00 px (same as photometry aperture_radius); oversample=x1
09:36:14 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=25, after_cuts=25, used_after_uniform=25
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.90
  geometry: fwhm_input=5.17px, fwhm_used=4.12px, fwhm_arcsec=1.47", pixel_scale=0.357 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=9px, fit_box=11px, cutout=41px
  normalization: aperture_radius=7.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:36:14 - INFO - PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 11 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 41 px, sigma_clip=4.00
  (15 iters)
09:36:14 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=5.20037 px, size=41x41
09:36:15 - INFO - PSF sources roundness: 0.02 +/- 0.01
09:36:15 - INFO -
— PSF photometry: 300 sources —

09:36:15 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.357 arcsec/px
    base_xy_bounds=5.61 px
    effective per tier (bright/faint/very-faint)=5.61/5.4/5.4 px
09:36:15 - INFO - Fit shapes:
    bright=(15, 15)
    faint=(13, 13)
    very-faint=(13, 13)
    xy_bounds=5.61 px
    undersampled=False
09:36:15 - INFO - Fitting 205 bright sources (LSQ)
09:36:17 - INFO - Fitting 13 faint sources (LSQ)
09:36:17 - INFO - LSQ retry for 1/13 problematic fits (fit_shape (13, 13) -> (15, 15), xy_bounds 5.40 -> 3.78).
09:36:17 - INFO - Fitting 82 very faint sources (LSQ)
09:36:19 - INFO - LSQ retry for 52/82 problematic fits (fit_shape (13, 13) -> (15, 15), xy_bounds 5.40 -> 3.78).
09:36:19 - INFO - Fitted 300 sources in 3.86s
09:36:19 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:36:19 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:36:19 - INFO -
— Zeropoint: clean sequence stars —

09:36:19 - INFO - Removing 60 sources with detection threshold < 3.0
09:36:19 - INFO - Removing 53 sources with FLAGS > 2 from zeropoint calibration.
09:36:19 - INFO - Removing 57 sources with |inst_AP - inst_PSF| > 0.50 mag from zeropoint calibration.
09:36:19 - INFO - 205 sources remaining after quality cuts
09:36:19 - INFO -
— Linearity: saturation check (205 sources) —

09:36:19 - INFO - Removing 11 sources with threshold < 5
09:36:19 - INFO - Selected 18 high S/N sources (SNR >= 100) for linearity fit
09:36:19 - INFO - Post-RANSAC sigma clipping removed 3 additional outliers
09:36:19 - INFO - Constrained fit results:  Zeropoint = 25.141 +/- 0.023
09:36:19 - INFO - Linearity range (0.5-95% flux percentiles): 765.6 - 20749.2
09:36:19 - INFO - Applying tight residual filter: removed 10 sources
09:36:19 - INFO - Returning 186 linear sources
09:36:19 - INFO - Catalog linearity check: 14 linear sources, ZP=25.141 +/- 0.023
09:36:19 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:36:19 - INFO - fit_color_term: using polynomial order 1 (linear)
09:36:19 - INFO - fit_color_term: color distribution before filtering: min=0.307, max=1.202, median=0.523, n_sources=186
09:36:19 - INFO - fit_color_term: removing 26 extreme color sources (beyond 2.5 sigma in color space)
09:36:19 - INFO - fit_color_term: RANSAC found 160 inliers
09:36:19 - INFO - fit_color_term: fitted linear color term: slope=0.0034, intercept=25.1404, n_inliers=160, color_range=0.570 mag
09:36:19 - INFO - fit_color_term: linear slope 0.0034 is negligible (< 0.01), returning 0 to avoid adding noise
09:36:19 - INFO - Estimating zeropoint via sigma clipping.
09:36:19 - INFO - [AP] Before color correction: ZP=25.144, std=0.008, color_term=0.0000
09:36:19 - INFO - [AP] Zeropoint: 25.144 +/- 0.001 mag
09:36:19 - INFO - [PSF] Before color correction: ZP=25.214, std=0.009, color_term=0.0000
09:36:19 - INFO - [PSF] Zeropoint: 25.214 +/- 0.001 mag
09:36:20 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:36:20 - INFO - Background mesh: fwhm=5.17 px  mesh_scale=4.00  box_size=(21, 21)  filter_size=3
09:36:20 - INFO - Local background: box_size=(21, 21)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:36:20 - INFO - Source mask contains 7048 pixels (10.59% of the image) after 2 iteration(s)
09:36:20 - INFO - Local background: adding a bias of +2.76012 to the local cutout residual (and -2.76012 to the local background surface) to enforce median >= 2.76802.
  Annulus_std=1.38401, annulus_k=2.
09:36:20 - INFO - Local background: subtracted cutout median=0.00790231; raised cutout by 2.76012 so median >= 2.76802 on 59516 pixels.
09:36:20 - INFO - Source mask contains 362147 pixels (34.54% of the image) after 2 iteration(s)
09:36:20 - INFO - Background mesh: fwhm=5.17 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:20 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:21 - INFO - Target cutout: keeping uniform bias level 2.76012 in measurement image (shifted mean enabled).
09:36:21 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:36:21 - INFO - Transient's expected location: x = 731.789 pixels, y = 527.691 pixels
09:36:21 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:36:21 - INFO - Target PSF fitting bound: 2.000 arcsec (5.61 px at 0.357 arcsec/px)
09:36:21 - INFO -
— PSF photometry: 1 sources —

09:36:21 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.357 arcsec/px
    base_xy_bounds=5.61 px
    effective per tier (bright/faint/very-faint)=5.61/5.61/5.61 px
09:36:21 - INFO - Fit shapes:
    bright=(23, 23)
    faint=(19, 19)
    very-faint=(19, 19)
    xy_bounds=5.61 px
    undersampled=False
09:36:21 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.357 arcsec/px
09:36:21 - INFO - Target PSF: after bootstrap - flux_all[0]=777, x_all[0]=33, y_all[0]=33, valid=True
09:36:21 - INFO - Target PSF: using aperture-matched local background annulus (r_in=11.00 px, r_out=22.00 px, estimator=median).
09:36:21 - INFO - Fitting 1 bright sources (LSQ)
09:36:21 - INFO - Fitted 1 sources in 0.02s
09:36:21 - INFO - Target background debug: sky_bkg_total=424.275  noiseSky=0.0467455
09:36:21 - INFO - Converting cutout-local to full-image: cutout_x0=698.79, cutout_y0=494.69
09:36:21 - INFO -   x_pix: 33.000 -> 731.789
09:36:21 - INFO -   y_pix: 33.000 -> 527.691
09:36:21 - INFO -   x_fit: 30.614 -> 729.403
09:36:21 - INFO -   y_fit: 38.608 -> 533.298
09:36:21 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 5159, in run_photometry
    from photutils.psf import decode_psf_flags

[7/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_r_wcs_ultracam_20260219.fits

09:36:24 - INFO -
— File: EP260131a_r_wcs_ultracam_20260215_APT.fits —

09:36:24 - INFO - Full path: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_r_wcs_ultracam_20260215/EP260131a_r_wcs_ultracam_20260215_APT.fits
09:36:24 - INFO - Start time: 2026-05-18 09:36:24.219971
09:36:24 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:36:24 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:36:24 - INFO - Exposure time: 25.001 s (header keyword EXPTIME)
09:36:24 - INFO - Pixel scale from WCS: 0.357 arcsec/pixel
09:36:24 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:36:24 - INFO - Telescope: NTT
09:36:24 - INFO - Instrument: ULTRACAM
09:36:24 - INFO - Filter: r
09:36:24 - INFO - MJD: 61178.400
09:36:24 - INFO - Read noise: 0.000 e/pixel
09:36:24 - INFO - Saturation level: inf ADU
09:36:24 - INFO - Pixel scale: 0.357 arcsec/pixel
09:36:24 - INFO - Date of observation: 2026-05-18
09:36:24 - INFO -
-------------------
Image preprocessing
-------------------

09:36:24 - INFO - Target position for NaN trimming: (706.3, 519.2)
09:36:24 - INFO - NaN boundary trimming: image shape (1024, 1024)
09:36:24 - INFO - NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
09:36:24 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:36:24 - INFO - Target pixel coordinates refreshed after trimming: (706.3, 519.2)
09:36:24 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:36:24 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:36:24 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260215_APT.fits (default) —

09:36:24 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:36:24 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:36:24 - INFO - Initial source count: 318
09:36:24 - INFO - Rejected 13 sources outside FWHM range [1.1, 100.0]
09:36:24 - INFO - Rejected 1 low-SNR sources (SNR < 3.0)
09:36:24 - INFO - Estimated FWHM: 6.34 pixels (sigma = 5.11 pixels)
09:36:24 - INFO - Rejected 48 sources with FLAGS > 2
09:36:24 - INFO - Filtering completed in 0.003 s (retained 256 of 318 initial sources)
09:36:24 - INFO - Filtered from 318 to 256 point sources
09:36:24 - INFO - Found 256 point sources, robust FWHM 6.18 px; scale = 19.0 (FWHM x 3.00 from source_detection / config)
09:36:24 - INFO -
------------------------
Background: initial pass
------------------------

09:36:24 - INFO -
— Background: sky & RMS —

09:36:24 - INFO - NaN pixels: 0 (0.00%)
09:36:24 - INFO - Background regime=sparse  bright_frac=0.011  large_scale_ratio=0.104
09:36:24 - INFO - Background mesh: fwhm=6.18 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:25 - INFO - Source mask contains 174717 pixels (16.66% of the image) after 2 iteration(s)
09:36:25 - INFO - Masked fraction (total): 16.66%
09:36:25 - INFO - box_size=(65, 65)  filter_size=3
09:36:25 - INFO - Global stats - mean 1.921e+02  median 1.926e+02  std 3.956e+00
09:36:25 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:26 - INFO - Background median 1.928e+02  RMS mean 2.301e+00
09:36:26 - INFO - Preliminary FWHM: 6.2 pixels
09:36:26 - INFO - Undersampled mode: False (FWHM=6.18 px, threshold=2.50 px)
09:36:26 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:36:26 - INFO - Pre-existing WCS found in header
09:36:26 - INFO - No variable sources found in input_yaml.
09:36:26 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:36:26 - INFO -
— TNS check: Transient —

09:36:26 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:36:26 - INFO - Expected pixel position: (706.31, 519.23)
09:36:26 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:36:26 - INFO -
— Background: sky & RMS —

09:36:26 - INFO - NaN pixels: 0 (0.00%)
09:36:26 - INFO - Background regime=sparse  bright_frac=0.011  large_scale_ratio=0.104
09:36:26 - INFO - Background mesh: fwhm=6.18 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:26 - INFO - Source mask contains 174717 pixels (16.66% of the image) after 2 iteration(s)
09:36:26 - INFO - Masked fraction (total): 16.66%
09:36:26 - INFO - box_size=(65, 65)  filter_size=3
09:36:27 - INFO - Global stats - mean 1.921e+02  median 1.926e+02  std 3.956e+00
09:36:27 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:27 - INFO - Background median 1.928e+02  RMS mean 2.301e+00
09:36:29 - INFO -
---------------
Target position
---------------

09:36:29 - INFO -
— 149.9025 -3.3073 —

09:36:29 - INFO - Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (706.31, 519.23)
  Offset from image center: dx=+194.81 px, dy=+7.73 px
  Bounds: within bounds (min edge margin 316.69 px)
09:36:29 - INFO -
— 149.9025 -3.3073 —

09:36:29 - INFO -
— 149.9025 -3.3073 —

09:36:29 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:36:29 - INFO - Reusing cached background results (fpath unchanged)
09:36:29 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:36:29 - INFO -
— Catalog: sequence sources in field —

09:36:29 - INFO - Existing PAN_STARRS catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/pan_starrs/transient/Transient_r_10.0arcmins_pan_starrs_target_ra_149.902500_dec_-3.307300.csv
09:36:29 - INFO - Cleaning 10000 sources
09:36:29 - INFO - Excluding 7502 sources with no r band information
09:36:29 - INFO - 2498 sources in output catalog
09:36:29 - INFO - Border filtering: removed 1787 sources outside border, 711 sources remaining
09:36:29 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:36:29 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260215_APT.fits (default) —

09:36:29 - INFO - Using FWHM = 6.2 pixels to construct the SExtractor convolution kernel
09:36:29 - INFO - Creating convolution kernel with FWHM: 6.2 pixels
09:36:29 - INFO - Initial source count: 196
09:36:29 - INFO - Rejected 5 sources outside FWHM range [1.1, 100.0]
09:36:29 - INFO - Estimated FWHM: 6.21 pixels (sigma = 5.45 pixels)
09:36:29 - INFO - Rejected 25 sources with FLAGS > 2
09:36:29 - INFO - Filtering completed in 0.002 s (retained 166 of 196 initial sources)
09:36:29 - INFO - Filtered from 196 to 166 point sources
09:36:29 - INFO - Found 166 point sources, robust FWHM 6.21 px; scale = 19.0 (FWHM x 3.00 from source_detection / config)
09:36:29 - INFO -
— SExtractor: EP260131a_r_wcs_ultracam_20260215_APT.fits (default) —

09:36:29 - INFO - Using FWHM = 6.2 pixels to construct the SExtractor convolution kernel
09:36:29 - INFO - Creating convolution kernel with FWHM: 6.2 pixels
09:36:29 - INFO - Initial source count: 194
09:36:29 - INFO - Rejected 4 sources outside FWHM range [1.1, 100.0]
09:36:29 - INFO - Estimated FWHM: 6.21 pixels (sigma = 5.64 pixels)
09:36:29 - INFO - Rejected 25 sources with FLAGS > 2
09:36:29 - INFO - Filtering completed in 0.002 s (retained 165 of 194 initial sources)
09:36:29 - INFO - Filtered from 194 to 165 point sources
09:36:29 - INFO - Found 165 point sources, robust FWHM 6.21 px; scale = 19.0 (FWHM x 3.00 from source_detection / config)
09:36:29 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:36:29 - INFO - Cleaned 165 sources to 152 with isolation distance [19]
09:36:29 - INFO -
— Recentering 152 sources —

09:36:29 - INFO - Boxsize: 19 px, Border: 28 px (annulus outer=27.6, undersampled=False)
09:36:29 - INFO - Recentering 143 sources within border
09:36:29 - INFO - 143 sources have valid cutouts
09:36:29 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:36:29 - INFO - Median pixel correction: 0.0 px
09:36:29 - INFO - Recentered 143 sources
09:36:29 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:36:30 - INFO - Excluded 25 sources based on quality cuts (kept 118/143).
09:36:30 - INFO - Number of sources: 46
09:36:30 - INFO -
— Optimum aperture: 46 sources —

09:36:30 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:36:30 - INFO - Concentration gate rejected 3 broad sources (enc_flux(1.70*FWHM) < 0.50).
09:36:30 - INFO - Using 33 sources with stable profiles for optimum-radius and PSF selection.
09:36:30 - INFO - Returning 14 sources, optimum radius: 1.05 * FWHM, scale: 19.5
09:36:30 - INFO - Aperture radius: 7.00 [pixels] (optimum_radius=1.05 FWHM)
09:36:30 - INFO - Computing aperture correction using 14 isolated sources at radius 7.00 pixels
09:36:30 - INFO - Aperture correction: -0.086 +/- 0.022
09:36:30 - INFO - Aperture correction (AP to total): -0.086 +/- 0.022 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:36:30 - INFO - Found 711 sources in field
09:36:30 - INFO -
— Recentering 711 sources —

09:36:30 - INFO - Boxsize: 9 px, Border: 25 px (annulus outer=24.1, undersampled=False)
09:36:30 - INFO - Recentering 658 sources within border
09:36:30 - INFO - 658 sources have valid cutouts
09:36:30 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:36:30 - INFO - Failed to recenter 6 sources - ignoring
09:36:30 - INFO - Median pixel correction: 0.0 px
09:36:30 - INFO - Recentered 652 sources
09:36:30 - INFO -
— Aperture photometry: 652 field sources —

09:36:31 - INFO - Instrumental magnitude of 407 sources measured
09:36:31 - INFO -
— Downsampling: 652 sources -> 300 max —

09:36:31 - INFO - Using 17x17 grid with ~1 sources per bin
09:36:31 - INFO - Processing spatial bins...
09:36:31 - INFO - Bin statistics: min=0, max=11, avg=2.2 sources per bin
09:36:31 - INFO - Selected 227 sources from spatial bins
09:36:31 - WARNING - Only 227 sources selected from bins, filling with top 73 remaining sources
09:36:31 - INFO - Added 73 additional sources from remaining pool
09:36:31 - INFO - Final selection: 300 sources
09:36:31 - INFO - Downsampling complete
09:36:31 - INFO - Building ePSF from 14 sources
09:36:31 - INFO - Small PSF-candidate pool (14): relaxed cuts to saturate_frac=0.97
09:36:31 - INFO - FWHM=5.16 pix  recenter=centroid_com  oversample=1x
09:36:31 - INFO - Initial sources: 14
09:36:31 - INFO - Sources after cuts: 14
09:36:31 - INFO - Using 14/14 PSF candidates after spatial downselection
09:36:31 - INFO - [robust_extract_stars] Extracted 14 cutouts
09:36:31 - INFO - FFT rejection at n_sigma=4.0 left too few stars; using relaxed n_sigma=6.0 -> 10 stars.
09:36:31 - INFO - Rejected 4 PSF stars via FFT outlier filtering
09:36:31 - INFO - PSF build FWHM: input=6.21 px, used=5.16 px; normalisation radius=7.00 px (same as photometry aperture_radius); oversample=x1
09:36:31 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=14, after_cuts=14, used_after_uniform=14
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.97
  geometry: fwhm_input=6.21px, fwhm_used=5.16px, fwhm_arcsec=1.84", pixel_scale=0.357 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=11px, fit_box=13px, cutout=51px
  normalization: aperture_radius=7.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:36:31 - INFO - PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 13 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 51 px, sigma_clip=4.00
  (15 iters)
09:36:31 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=6.51804 px, size=51x51
09:36:33 - INFO - PSF sources roundness: 0.04 +/- 0.01
09:36:33 - INFO -
— PSF photometry: 300 sources —

09:36:33 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.357 arcsec/px
    base_xy_bounds=5.61 px
    effective per tier (bright/faint/very-faint)=5.61/5.61/5.61 px
09:36:33 - INFO - Fit shapes:
    bright=(19, 19)
    faint=(15, 15)
    very-faint=(15, 15)
    xy_bounds=5.61 px
    undersampled=False
09:36:33 - INFO - Fitting 184 bright sources (LSQ)
09:36:34 - INFO - Fitting 14 faint sources (LSQ)
09:36:35 - INFO - Fitting 102 very faint sources (LSQ)
09:36:36 - INFO - LSQ retry for 62/102 problematic fits (fit_shape (15, 15) -> (17, 17), xy_bounds 5.61 -> 3.93).
09:36:37 - INFO - Fitted 300 sources in 4.25s
09:36:37 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:36:37 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:36:37 - INFO -
— Zeropoint: clean sequence stars —

09:36:37 - INFO - Removing 67 sources with detection threshold < 3.0
09:36:37 - INFO - Removing 62 sources with FLAGS > 2 from zeropoint calibration.
09:36:37 - INFO - Removing 56 sources with |inst_AP - inst_PSF| > 0.50 mag from zeropoint calibration.
09:36:37 - INFO - 200 sources remaining after quality cuts
09:36:37 - INFO -
— Linearity: saturation check (200 sources) —

09:36:37 - INFO - Removing 22 sources with threshold < 5
09:36:37 - INFO - Selected 18 high S/N sources (SNR >= 100) for linearity fit
09:36:37 - INFO - Post-RANSAC sigma clipping removed 2 additional outliers
09:36:37 - INFO - Constrained fit results:  Zeropoint = 25.140 +/- 0.086
09:36:37 - INFO - Linearity range (0.5-95% flux percentiles): 788.4 - 20565.7
09:36:37 - INFO - Applying tight residual filter: removed 10 sources
09:36:37 - INFO - Returning 186 linear sources
09:36:37 - INFO - Catalog linearity check: 14 linear sources, ZP=25.140 +/- 0.086
09:36:37 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:36:37 - INFO - fit_color_term: using polynomial order 1 (linear)
09:36:37 - INFO - fit_color_term: color distribution before filtering: min=0.307, max=1.202, median=0.523, n_sources=186
09:36:37 - INFO - fit_color_term: removing 26 extreme color sources (beyond 2.5 sigma in color space)
09:36:37 - INFO - fit_color_term: RANSAC found 160 inliers
09:36:37 - INFO - fit_color_term: fitted linear color term: slope=-0.0657, intercept=25.1806, n_inliers=160, color_range=0.570 mag
09:36:38 - INFO - Estimating zeropoint via sigma clipping.
09:36:38 - INFO - [AP] Before color correction: ZP=25.141, std=0.027, color_term=-0.0657
09:36:38 - INFO - [AP] Zeropoint: 25.172 +/- 0.007 mag
09:36:38 - INFO - [PSF] Before color correction: ZP=25.196, std=0.027, color_term=-0.0657
09:36:38 - INFO - [PSF] Zeropoint: 25.228 +/- 0.007 mag
09:36:38 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:36:38 - INFO - Background mesh: fwhm=6.21 px  mesh_scale=4.00  box_size=(25, 25)  filter_size=3
09:36:38 - INFO - Local background: box_size=(25, 25)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:36:38 - INFO - Source mask contains 10201 pixels (10.61% of the image) after 2 iteration(s)
09:36:38 - INFO - Local background: adding a bias of +4.28815 to the local cutout residual (and -4.28815 to the local background surface) to enforce median >= 4.30976.
  Annulus_std=2.15488, annulus_k=2.
09:36:38 - INFO - Local background: subtracted cutout median=0.0216093; raised cutout by 4.28815 so median >= 4.30976 on 85899 pixels.
09:36:38 - INFO - Source mask contains 370910 pixels (35.37% of the image) after 2 iteration(s)
09:36:38 - INFO - Background mesh: fwhm=6.21 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:39 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:39 - INFO - Target cutout: keeping uniform bias level 4.28815 in measurement image (shifted mean enabled).
09:36:39 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:36:39 - INFO - Transient's expected location: x = 706.314 pixels, y = 519.227 pixels
09:36:39 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:36:39 - INFO - Target PSF fitting bound: 2.000 arcsec (5.61 px at 0.357 arcsec/px)
09:36:39 - INFO -
— PSF photometry: 1 sources —

09:36:39 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.357 arcsec/px
    base_xy_bounds=5.61 px
    effective per tier (bright/faint/very-faint)=5.61/5.61/5.61 px
09:36:39 - INFO - Fit shapes:
    bright=(29, 29)
    faint=(23, 23)
    very-faint=(23, 23)
    xy_bounds=5.61 px
    undersampled=False
09:36:39 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.357 arcsec/px
09:36:39 - INFO - Target PSF: after bootstrap - flux_all[0]=771, x_all[0]=37, y_all[0]=37, valid=True
09:36:39 - INFO - Target PSF: using aperture-matched local background annulus (r_in=12.00 px, r_out=25.00 px, estimator=median).
09:36:39 - INFO - Fitting 1 bright sources (LSQ)
09:36:39 - INFO - Fitted 1 sources in 0.02s
09:36:39 - INFO - Target background debug: sky_bkg_total=662.52  noiseSky=0.0887451
09:36:39 - INFO - Converting cutout-local to full-image: cutout_x0=669.31, cutout_y0=482.23
09:36:39 - INFO -   x_pix: 37.000 -> 706.314
09:36:39 - INFO -   y_pix: 37.000 -> 519.227
09:36:39 - INFO -   x_fit: 35.315 -> 704.630
09:36:39 - INFO -   y_fit: 42.609 -> 524.836
09:36:39 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):

[8/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_r_wcs_ultracam_20260215.fits

09:36:42 - INFO -
— File: EP260131a_g_wcs_ultracam_20260222_APT.fits —

09:36:42 - INFO - Full path: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_g_wcs_ultracam_20260222/EP260131a_g_wcs_ultracam_20260222_APT.fits
09:36:42 - INFO - Start time: 2026-05-18 09:36:42.519160
09:36:42 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:36:42 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:36:42 - INFO - Exposure time: 31.159 s (header keyword EXPTIME)
09:36:42 - INFO - Pixel scale from WCS: 0.353 arcsec/pixel
09:36:42 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:36:42 - INFO - Telescope: NTT
09:36:42 - INFO - Instrument: ULTRACAM
09:36:42 - INFO - Filter: g
09:36:42 - INFO - MJD: 61178.400
09:36:42 - INFO - Read noise: 0.000 e/pixel
09:36:42 - INFO - Saturation level: inf ADU
09:36:42 - INFO - Pixel scale: 0.353 arcsec/pixel
09:36:42 - INFO - Date of observation: 2026-05-18
09:36:42 - INFO -
-------------------
Image preprocessing
-------------------

09:36:42 - INFO - Target position for NaN trimming: (746.0, 525.5)
09:36:42 - INFO - NaN boundary trimming: image shape (1024, 1024)
09:36:42 - INFO - NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
09:36:42 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:36:42 - INFO - Target pixel coordinates refreshed after trimming: (746.0, 525.5)
09:36:42 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:36:42 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:36:42 - INFO -
— SExtractor: EP260131a_g_wcs_ultracam_20260222_APT.fits (default) —

09:36:42 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:36:42 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:36:43 - INFO - Initial source count: 532
09:36:43 - INFO - Estimated FWHM: 4.73 pixels (sigma = 2.88 pixels)
09:36:43 - INFO - Rejected 60 sources with FLAGS > 2
09:36:43 - INFO - Filtering completed in 0.003 s (retained 472 of 532 initial sources)
09:36:43 - INFO - Filtered from 532 to 472 point sources
09:36:43 - INFO - Found 472 point sources, robust FWHM 4.69 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:36:43 - INFO -
------------------------
Background: initial pass
------------------------

09:36:43 - INFO -
— Background: sky & RMS —

09:36:43 - INFO - NaN pixels: 0 (0.00%)
09:36:43 - INFO - Background regime=sparse  bright_frac=0.018  large_scale_ratio=0.078
09:36:43 - INFO - Background mesh: fwhm=4.69 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:43 - INFO - Source mask contains 259176 pixels (24.72% of the image) after 2 iteration(s)
09:36:43 - INFO - Masked fraction (total): 24.72%
09:36:43 - INFO - box_size=(65, 65)  filter_size=3
09:36:44 - INFO - Global stats - mean -1.727e-01  median -1.423e-01  std 1.042e+00
09:36:44 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:44 - INFO - Background median -4.359e-02  RMS mean 9.328e-01
09:36:44 - INFO - Preliminary FWHM: 4.7 pixels
09:36:44 - INFO - Undersampled mode: False (FWHM=4.69 px, threshold=2.50 px)
09:36:44 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:36:44 - INFO - Pre-existing WCS found in header
09:36:44 - INFO - No variable sources found in input_yaml.
09:36:44 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:36:44 - INFO -
— TNS check: Transient —

09:36:44 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:36:44 - INFO - Expected pixel position: (745.95, 525.46)
09:36:44 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:36:44 - INFO -
— Background: sky & RMS —

09:36:44 - INFO - NaN pixels: 0 (0.00%)
09:36:44 - INFO - Background regime=sparse  bright_frac=0.018  large_scale_ratio=0.078
09:36:44 - INFO - Background mesh: fwhm=4.69 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:45 - INFO - Source mask contains 259176 pixels (24.72% of the image) after 2 iteration(s)
09:36:45 - INFO - Masked fraction (total): 24.72%
09:36:45 - INFO - box_size=(65, 65)  filter_size=3
09:36:45 - INFO - Global stats - mean -1.727e-01  median -1.423e-01  std 1.042e+00
09:36:45 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:45 - INFO - Background median -4.359e-02  RMS mean 9.328e-01
09:36:47 - INFO -
---------------
Target position
---------------

09:36:47 - INFO -
— 149.9025 -3.3073 —

09:36:47 - INFO - Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (745.95, 525.46)
  Offset from image center: dx=+234.45 px, dy=+13.96 px
  Bounds: within bounds (min edge margin 277.05 px)
09:36:47 - INFO -
— 149.9025 -3.3073 —

09:36:47 - INFO -
— 149.9025 -3.3073 —

09:36:47 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:36:47 - INFO - Reusing cached background results (fpath unchanged)
09:36:47 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:36:47 - INFO -
— Catalog: sequence sources in field —

09:36:47 - INFO - Existing PAN_STARRS catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/pan_starrs/transient/Transient_r_10.0arcmins_pan_starrs_target_ra_149.902500_dec_-3.307300.csv
09:36:47 - INFO - Cleaning 10000 sources
09:36:47 - INFO - Excluding 8161 sources with no g band information
09:36:47 - INFO - 1839 sources in output catalog
09:36:47 - INFO - Border filtering: removed 1321 sources outside border, 518 sources remaining
09:36:47 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:36:47 - INFO -
— SExtractor: EP260131a_g_wcs_ultracam_20260222_APT.fits (default) —

09:36:47 - INFO - Using FWHM = 4.7 pixels to construct the SExtractor convolution kernel
09:36:47 - INFO - Creating convolution kernel with FWHM: 4.7 pixels
09:36:47 - INFO - Initial source count: 376
09:36:47 - INFO - Estimated FWHM: 4.88 pixels (sigma = 2.45 pixels)
09:36:47 - INFO - Rejected 46 sources with FLAGS > 2
09:36:47 - INFO - Filtering completed in 0.002 s (retained 330 of 376 initial sources)
09:36:47 - INFO - Filtered from 376 to 330 point sources
09:36:47 - INFO - Found 330 point sources, robust FWHM 4.81 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:36:47 - INFO -
— SExtractor: EP260131a_g_wcs_ultracam_20260222_APT.fits (default) —

09:36:47 - INFO - Using FWHM = 4.8 pixels to construct the SExtractor convolution kernel
09:36:47 - INFO - Creating convolution kernel with FWHM: 4.8 pixels
09:36:48 - INFO - Initial source count: 368
09:36:48 - INFO - Estimated FWHM: 4.89 pixels (sigma = 2.45 pixels)
09:36:48 - INFO - Rejected 46 sources with FLAGS > 2
09:36:48 - INFO - Filtering completed in 0.002 s (retained 322 of 368 initial sources)
09:36:48 - INFO - Filtered from 368 to 322 point sources
09:36:48 - INFO - Found 322 point sources, robust FWHM 4.81 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:36:48 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:36:48 - INFO - Cleaned 322 sources to 286 with isolation distance [15]
09:36:48 - INFO -
— Recentering 286 sources —

09:36:48 - INFO - Boxsize: 15 px, Border: 22 px (annulus outer=21.4, undersampled=False)
09:36:48 - INFO - Recentering 274 sources within border
09:36:48 - INFO - 274 sources have valid cutouts
09:36:48 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:36:48 - INFO - Failed to recenter 1 sources - ignoring
09:36:48 - INFO - Median pixel correction: 0.0 px
09:36:48 - INFO - Recentered 273 sources
09:36:48 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:36:48 - INFO - Excluded 52 sources based on quality cuts (kept 221/273).
09:36:48 - INFO - Number of sources: 60
09:36:48 - INFO -
— Optimum aperture: 58 sources —

09:36:48 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:36:48 - INFO - Concentration gate rejected 4 broad sources (enc_flux(1.70*FWHM) < 0.50).
09:36:48 - INFO - Using 44 sources with stable profiles for optimum-radius and PSF selection.
09:36:49 - INFO - Returning 19 sources, optimum radius: 0.99 * FWHM, scale: 15.5
09:36:49 - INFO - Aperture radius: 5.00 [pixels] (optimum_radius=0.99 FWHM)
09:36:49 - INFO - Computing aperture correction using 19 isolated sources at radius 5.00 pixels
09:36:49 - INFO - Aperture correction: -0.079 +/- 0.027
09:36:49 - INFO - Aperture correction (AP to total): -0.079 +/- 0.027 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:36:49 - INFO - Found 518 sources in field
09:36:49 - INFO -
— Recentering 518 sources —

09:36:49 - INFO - Boxsize: 7 px, Border: 19 px (annulus outer=18.2, undersampled=False)
09:36:49 - INFO - Recentering 500 sources within border
09:36:49 - INFO - 500 sources have valid cutouts
09:36:49 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:36:49 - INFO - Failed to recenter 5 sources - ignoring
09:36:49 - INFO - Median pixel correction: 0.0 px
09:36:49 - INFO - Recentered 495 sources
09:36:49 - INFO -
— Aperture photometry: 495 field sources —

09:36:49 - INFO - Instrumental magnitude of 296 sources measured
09:36:49 - INFO -
— Downsampling: 495 sources -> 300 max —

09:36:49 - INFO - Using 17x17 grid with ~1 sources per bin
09:36:49 - INFO - Processing spatial bins...
09:36:49 - INFO - Bin statistics: min=0, max=10, avg=1.7 sources per bin
09:36:49 - INFO - Selected 200 sources from spatial bins
09:36:49 - WARNING - Only 200 sources selected from bins, filling with top 100 remaining sources
09:36:49 - INFO - Added 100 additional sources from remaining pool
09:36:49 - INFO - Final selection: 300 sources
09:36:49 - INFO - Downsampling complete
09:36:49 - INFO - Building ePSF from 19 sources
09:36:49 - INFO - Small PSF-candidate pool (19): relaxed cuts to saturate_frac=0.97
09:36:49 - INFO - FWHM=3.34 pix  recenter=centroid_com  oversample=1x
09:36:49 - INFO - Initial sources: 19
09:36:49 - INFO - Sources after cuts: 19
09:36:49 - INFO - Using 19/19 PSF candidates after spatial downselection
09:36:49 - INFO - [robust_extract_stars] Extracted 19 cutouts
09:36:49 - INFO - Rejected 5 PSF stars via FFT outlier filtering
09:36:49 - INFO - PSF build FWHM: input=4.81 px, used=3.34 px; normalisation radius=5.00 px (same as photometry aperture_radius); oversample=x1
09:36:49 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=19, after_cuts=19, used_after_uniform=19
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.97
  geometry: fwhm_input=4.81px, fwhm_used=3.34px, fwhm_arcsec=1.18", pixel_scale=0.353 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=7px, fit_box=9px, cutout=33px
  normalization: aperture_radius=5.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:36:49 - INFO - PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 9 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 33 px, sigma_clip=4.00
  (15 iters)
09:36:49 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=4.21698 px, size=33x33
09:36:50 - INFO - PSF sources roundness: 0.04 +/- 0.02
09:36:50 - INFO -
— PSF photometry: 300 sources —

09:36:50 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.353 arcsec/px
    base_xy_bounds=5.66 px
    effective per tier (bright/faint/very-faint)=5.66/5.4/5.4 px
09:36:50 - INFO - Fit shapes:
    bright=(15, 15)
    faint=(13, 13)
    very-faint=(13, 13)
    xy_bounds=5.66 px
    undersampled=False
09:36:50 - INFO - Fitting 126 bright sources (LSQ)
09:36:51 - INFO - Fitting 24 faint sources (LSQ)
09:36:52 - INFO - Fitting 150 very faint sources (LSQ)
09:36:54 - INFO - LSQ retry for 68/150 problematic fits (fit_shape (13, 13) -> (15, 15), xy_bounds 5.40 -> 3.78).
09:36:55 - INFO - Fitted 300 sources in 4.30s
09:36:55 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:36:55 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:36:55 - INFO -
— Zeropoint: clean sequence stars —

09:36:55 - INFO - Removing 116 sources with detection threshold < 3.0
09:36:55 - INFO - Removing 67 sources with FLAGS > 2 from zeropoint calibration.
09:36:55 - INFO - Removing 84 sources with |inst_AP - inst_PSF| > 0.50 mag from zeropoint calibration.
09:36:55 - INFO - 150 sources remaining after quality cuts
09:36:55 - INFO -
— Linearity: saturation check (150 sources) —

09:36:55 - INFO - Removing 28 sources with threshold < 5
09:36:55 - INFO - Selected 15 high S/N sources (SNR >= 75) for linearity fit
09:36:55 - INFO - Post-RANSAC sigma clipping removed 3 additional outliers
09:36:55 - INFO - Constrained fit results:  Zeropoint = 25.240 +/- 0.075
09:36:55 - INFO - Linearity range (0.5-95% flux percentiles): 390.3 - 15970.9
09:36:55 - INFO - Applying tight residual filter: removed 29 sources
09:36:55 - INFO - Returning 115 linear sources
09:36:55 - INFO - Catalog linearity check: 12 linear sources, ZP=25.240 +/- 0.075
09:36:55 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:36:55 - INFO - fit_color_term: using polynomial order 1 (linear)
09:36:55 - INFO - fit_color_term: color distribution before filtering: min=0.307, max=1.085, median=0.523, n_sources=115
09:36:55 - INFO - fit_color_term: removing 7 extreme color sources (beyond 2.5 sigma in color space)
09:36:55 - INFO - fit_color_term: RANSAC found 108 inliers
09:36:55 - INFO - fit_color_term: fitted linear color term: slope=-0.0619, intercept=25.2751, n_inliers=108, color_range=0.570 mag
09:36:55 - INFO - Estimating zeropoint via sigma clipping.
09:36:55 - INFO - [AP] Before color correction: ZP=25.238, std=0.029, color_term=-0.0619
09:36:55 - INFO - [AP] Zeropoint: 25.274 +/- 0.005 mag
09:36:55 - INFO - [PSF] Before color correction: ZP=25.306, std=0.038, color_term=-0.0619
09:36:55 - INFO - [PSF] Zeropoint: 25.341 +/- 0.006 mag
09:36:55 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:36:55 - INFO - Background mesh: fwhm=4.81 px  mesh_scale=4.00  box_size=(19, 19)  filter_size=3
09:36:55 - INFO - Local background: box_size=(19, 19)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:36:55 - INFO - Source mask contains 3904 pixels (6.78% of the image) after 2 iteration(s)
09:36:55 - INFO - Local background: adding a bias of +1.79065 to the local cutout residual (and -1.79065 to the local background surface) to enforce median >= 1.78632.
  Annulus_std=0.893161, annulus_k=2.
09:36:55 - INFO - Local background: subtracted cutout median=-0.00433036; raised cutout by 1.79065 so median >= 1.78632 on 53696 pixels.
09:36:56 - INFO - Source mask contains 412427 pixels (39.33% of the image) after 2 iteration(s)
09:36:56 - INFO - Background mesh: fwhm=4.81 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:36:56 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:36:56 - INFO - Target cutout: keeping uniform bias level 1.79065 in measurement image (shifted mean enabled).
09:36:56 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:36:56 - INFO - Transient's expected location: x = 745.951 pixels, y = 525.462 pixels
09:36:56 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:36:56 - INFO - Target PSF fitting bound: 2.000 arcsec (5.66 px at 0.353 arcsec/px)
09:36:56 - INFO -
— PSF photometry: 1 sources —

09:36:56 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.353 arcsec/px
    base_xy_bounds=5.66 px
    effective per tier (bright/faint/very-faint)=5.66/5.66/5.66 px
09:36:56 - INFO - Fit shapes:
    bright=(23, 23)
    faint=(19, 19)
    very-faint=(19, 19)
    xy_bounds=5.66 px
    undersampled=False
09:36:56 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.353 arcsec/px
09:36:56 - INFO - Target PSF: after bootstrap - flux_all[0]=91.7, x_all[0]=30, y_all[0]=29, valid=True
09:36:56 - INFO - Target PSF: using aperture-matched local background annulus (r_in=9.00 px, r_out=19.00 px, estimator=median).
09:36:56 - INFO - Fitting 1 faint sources (LSQ)
09:36:56 - INFO - Fitted 1 sources in 0.02s
09:36:57 - INFO - Target background debug: sky_bkg_total=147.37  noiseSky=0.0318409
09:36:57 - INFO - Converting cutout-local to full-image: cutout_x0=715.95, cutout_y0=496.46
09:36:57 - INFO -   x_pix: 30.000 -> 745.951
09:36:57 - INFO -   y_pix: 29.000 -> 525.462
09:36:57 - INFO -   x_fit: 27.969 -> 743.919
09:36:57 - INFO -   y_fit: 34.659 -> 531.122
09:36:57 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 5159, in run_photometry
    from photutils.psf import decode_psf_flags
ImportError: cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Processing:  75%|███████▌  | 9/12 [02:10<00:49, 16.39s/file]

[9/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_g_wcs_ultracam_20260222.fits

09:36:59 - INFO -
— File: EP260131a_g_wcs_ultracam_20260220_bkg_sub_APT.fits —

09:36:59 - INFO - Full path:
  /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_g_wcs_ultracam_20260220_bkg_sub/EP260131a_g_wcs_ultracam_20260220_bkg_sub_APT.fits
09:36:59 - INFO - Start time: 2026-05-18 09:36:59.779189
09:36:59 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:36:59 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:36:59 - INFO - Exposure time: 25.001 s (header keyword EXPTIME)
09:36:59 - INFO - Pixel scale from WCS: 0.707 arcsec/pixel
09:36:59 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:36:59 - INFO - Telescope: NTT
09:36:59 - INFO - Instrument: ULTRACAM
09:36:59 - INFO - Filter: g
09:36:59 - INFO - MJD: 61178.401
09:36:59 - INFO - Read noise: 0.000 e/pixel
09:36:59 - INFO - Saturation level: inf ADU
09:36:59 - INFO - Pixel scale: 0.707 arcsec/pixel
09:36:59 - INFO - Date of observation: 2026-05-18
09:36:59 - INFO -
-------------------
Image preprocessing
-------------------

09:36:59 - INFO - Target position for NaN trimming: (367.4, 261.1)
09:36:59 - INFO - NaN boundary trimming: image shape (512, 512)
09:36:59 - INFO - NaN boundary trimming: 0/262144 pixels are NaN (0.0%)
09:36:59 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:36:59 - INFO - Target pixel coordinates refreshed after trimming: (367.4, 261.1)
09:36:59 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:36:59 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:36:59 - INFO -
— SExtractor: EP260131a_g_wcs_ultracam_20260220_bkg_sub_APT.fits (default) —

09:36:59 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:36:59 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:37:00 - INFO - Initial source count: 101
09:37:00 - INFO - Rejected 1 sources outside FWHM range [1.1, 100.0]
09:37:00 - INFO - Estimated FWHM: 2.94 pixels (sigma = 7.21 pixels)
09:37:00 - INFO - Rejected 16 sources with FLAGS > 2
09:37:00 - INFO - Filtering completed in 0.003 s (retained 84 of 101 initial sources)
09:37:00 - INFO - Filtered from 101 to 84 point sources
09:37:00 - INFO - Found 84 point sources, robust FWHM 2.90 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:37:00 - INFO -
------------------------
Background: initial pass
------------------------

09:37:00 - INFO -
— Background: sky & RMS —

09:37:00 - INFO - NaN pixels: 0 (0.00%)
09:37:00 - INFO - Background regime=sparse  bright_frac=0.012  large_scale_ratio=0.066
09:37:00 - INFO - Background mesh: fwhm=2.90 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:37:00 - INFO - Source mask contains 25485 pixels (9.72% of the image) after 2 iteration(s)
09:37:00 - INFO - Masked fraction (total): 9.72%
09:37:00 - INFO - box_size=(65, 65)  filter_size=3
09:37:00 - INFO - Global stats - mean 1.695e-01  median 5.576e-02  std 5.066e+00
09:37:00 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:37:00 - INFO - Background median -1.492e-01  RMS mean 3.327e+00
09:37:00 - INFO - Preliminary FWHM: 2.9 pixels
09:37:00 - INFO - Undersampled mode: False (FWHM=2.90 px, threshold=2.50 px)
09:37:00 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:37:00 - INFO - Pre-existing WCS found in header
09:37:00 - INFO - No variable sources found in input_yaml.
09:37:00 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:37:00 - INFO -
— TNS check: Transient —

09:37:00 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:37:00 - INFO - Expected pixel position: (367.42, 261.08)
09:37:00 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:37:00 - INFO -
— Background: sky & RMS —

09:37:00 - INFO - NaN pixels: 0 (0.00%)
09:37:00 - INFO - Background regime=sparse  bright_frac=0.012  large_scale_ratio=0.066
09:37:00 - INFO - Background mesh: fwhm=2.90 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:37:00 - INFO - Source mask contains 25485 pixels (9.72% of the image) after 2 iteration(s)
09:37:00 - INFO - Masked fraction (total): 9.72%
09:37:00 - INFO - box_size=(65, 65)  filter_size=3
09:37:00 - INFO - Global stats - mean 1.695e-01  median 5.576e-02  std 5.066e+00
09:37:00 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:37:00 - INFO - Background median -1.492e-01  RMS mean 3.327e+00
09:37:01 - INFO -
---------------
Target position
---------------

09:37:01 - INFO -
— 149.9025 -3.3073 —

09:37:01 - INFO - Target summary:
  Name: Transient
  Image size: 512 x 512 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (367.42, 261.08)
  Offset from image center: dx=+111.92 px, dy=+5.58 px
  Bounds: within bounds (min edge margin 143.58 px)
09:37:01 - INFO -
— 149.9025 -3.3073 —

09:37:01 - INFO -
— 149.9025 -3.3073 —

09:37:01 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:37:01 - INFO - Reusing cached background results (fpath unchanged)
09:37:01 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:37:01 - INFO -
— Catalog: sequence sources in field —

09:37:01 - INFO - Existing PAN_STARRS catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/pan_starrs/transient/Transient_r_10.0arcmins_pan_starrs_target_ra_149.902500_dec_-3.307300.csv
09:37:01 - INFO - Cleaning 10000 sources
09:37:01 - INFO - Excluding 8161 sources with no g band information
09:37:01 - INFO - 1839 sources in output catalog
09:37:01 - INFO - Border filtering: removed 1342 sources outside border, 497 sources remaining
09:37:01 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:37:01 - INFO -
— SExtractor: EP260131a_g_wcs_ultracam_20260220_bkg_sub_APT.fits (default) —

09:37:01 - INFO - Using FWHM = 2.9 pixels to construct the SExtractor convolution kernel
09:37:01 - INFO - Creating convolution kernel with FWHM: 2.9 pixels
09:37:01 - INFO - Initial source count: 112
09:37:01 - INFO - Estimated FWHM: 2.96 pixels (sigma = 7.24 pixels)
09:37:01 - INFO - Rejected 23 sources with FLAGS > 2
09:37:01 - INFO - Filtering completed in 0.002 s (retained 89 of 112 initial sources)
09:37:01 - INFO - Filtered from 112 to 89 point sources
09:37:01 - INFO - Found 89 point sources, robust FWHM 2.76 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:37:01 - INFO -
— SExtractor: EP260131a_g_wcs_ultracam_20260220_bkg_sub_APT.fits (default) —

09:37:01 - INFO - Using FWHM = 2.8 pixels to construct the SExtractor convolution kernel
09:37:01 - INFO - Creating convolution kernel with FWHM: 2.8 pixels
09:37:01 - INFO - Initial source count: 112
09:37:01 - INFO - Estimated FWHM: 2.96 pixels (sigma = 7.24 pixels)
09:37:01 - INFO - Rejected 23 sources with FLAGS > 2
09:37:01 - INFO - Filtering completed in 0.002 s (retained 89 of 112 initial sources)
09:37:01 - INFO - Filtered from 112 to 89 point sources
09:37:01 - INFO - Found 89 point sources, robust FWHM 2.76 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
09:37:01 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:37:01 - INFO - Cleaned 89 sources to 77 with isolation distance [15]
09:37:01 - INFO -
— Recentering 77 sources —

09:37:01 - INFO - Boxsize: 15 px, Border: 15 px (annulus outer=12.3, undersampled=False)
09:37:01 - INFO - Recentering 74 sources within border
09:37:01 - INFO - 74 sources have valid cutouts
09:37:01 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:37:01 - INFO - Median pixel correction: 0.0 px
09:37:01 - INFO - Recentered 74 sources
09:37:01 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:37:01 - INFO - Excluded 30 sources based on quality cuts (kept 44/74).
09:37:01 - INFO - Number of sources: 19
09:37:01 - INFO -
— Optimum aperture: 18 sources —

09:37:01 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:37:01 - INFO - Concentration gate rejected 2 broad sources (enc_flux(1.70*FWHM) < 0.50).
09:37:01 - INFO - Using 16 sources with stable profiles for optimum-radius and PSF selection.
09:37:02 - INFO - Final tail screen was over-restrictive; rescued to 8 sources.
09:37:02 - INFO - Returning 8 sources, optimum radius: 1.42 * FWHM, scale: 12.5
09:37:02 - INFO - Aperture radius: 5.00 [pixels] (optimum_radius=1.42 FWHM)
09:37:02 - INFO - Computing aperture correction using 8 isolated sources at radius 5.00 pixels
09:37:02 - INFO - Aperture correction: -0.073 +/- 0.062
09:37:02 - INFO - Aperture correction (AP to total): -0.073 +/- 0.062 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:37:02 - INFO - Found 497 sources in field
09:37:02 - INFO -
— Recentering 497 sources —

09:37:02 - INFO - Boxsize: 7 px, Border: 13 px (annulus outer=12.6, undersampled=False)
09:37:02 - INFO - Recentering 487 sources within border
09:37:02 - INFO - 487 sources have valid cutouts
09:37:02 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:37:02 - INFO - Failed to recenter 3 sources - ignoring
09:37:02 - INFO - Median pixel correction: 0.0 px
09:37:02 - INFO - Recentered 484 sources
09:37:02 - INFO -
— Aperture photometry: 484 field sources —

09:37:02 - INFO - Instrumental magnitude of 293 sources measured
09:37:02 - INFO -
— Downsampling: 484 sources -> 300 max —

09:37:02 - INFO - Using 17x17 grid with ~1 sources per bin
09:37:02 - INFO - Processing spatial bins...
09:37:02 - INFO - Bin statistics: min=0, max=8, avg=1.7 sources per bin
09:37:02 - INFO - Selected 197 sources from spatial bins
09:37:02 - WARNING - Only 197 sources selected from bins, filling with top 103 remaining sources
09:37:02 - INFO - Added 103 additional sources from remaining pool
09:37:02 - INFO - Final selection: 300 sources
09:37:02 - INFO - Downsampling complete
09:37:02 - INFO - Building ePSF from 8 sources
09:37:02 - INFO - Small PSF-candidate pool (8): relaxed cuts to saturate_frac=0.97
09:37:02 - INFO - Image appears undersampled (FWHM=2.19 pix) and psf_oversample=1; consider increasing psf_oversample in the config if enough PSF stars are available.
09:37:02 - INFO - Undersampled regime (FWHM <= 2.50 px): disabling strict threshold/SNR candidate cuts for PSF build.
09:37:02 - INFO - FWHM=2.19 pix  recenter=centroid_2dg  oversample=1x
09:37:02 - INFO - Initial sources: 8
09:37:02 - INFO - Sources after cuts: 8
09:37:02 - INFO - Using 8/8 PSF candidates after spatial downselection
09:37:02 - INFO - [robust_extract_stars] Extracted 8 cutouts
09:37:02 - INFO - FFT outlier rejection would leave too few stars (5/8); keeping original set.
09:37:02 - INFO - PSF build FWHM: input=2.76 px, used=2.19 px; normalisation radius=5.00 px (same as photometry aperture_radius); oversample=x1
09:37:02 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=8, after_cuts=8, used_after_uniform=8
  selection cuts: min_candidates=8, threshold_limit=nan, SNR_limit=[0.0, 1000000000000.0], min_keep_frac_after_cut=0.30, saturate_frac=0.97
  geometry: fwhm_input=2.76px, fwhm_used=2.19px, fwhm_arcsec=1.55", pixel_scale=0.707 arcsec/px, build_sampling_boost=1.20, oversample=x1,
    recenter=centroid_2dg, cen_box=7px, fit_box=7px, cutout=27px
  normalization: aperture_radius=5.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:37:02 - INFO - PSF build windows: fit_box=3.00*FWHM (base 2.50, min 2.50 arcsec) -> 7 px, cutout=12.00*FWHM (base 10.00, min 9.00 arcsec) -> 27 px, sigma_clip=4.00
  (15 iters)
09:37:02 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=2.771 px, size=27x27
09:37:03 - INFO - PSF sources roundness: 0.02 +/- 0.00
09:37:03 - INFO -
— PSF photometry: 300 sources —

09:37:03 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.707 arcsec/px
    base_xy_bounds=2.83 px
    effective per tier (bright/faint/very-faint)=2.83/2.7/2.7 px
09:37:03 - INFO - Fit shapes:
    bright=(9, 9)
    faint=(7, 7)
    very-faint=(7, 7)
    xy_bounds=2.83 px
    undersampled=False
09:37:03 - INFO - Fitting 93 bright sources (LSQ)
09:37:04 - INFO - Fitting 43 faint sources (LSQ)
09:37:04 - INFO - LSQ retry for 2/43 problematic fits (fit_shape (7, 7) -> (9, 9), xy_bounds 2.70 -> 1.89).
09:37:04 - INFO - Fitting 164 very faint sources (LSQ)
09:37:07 - INFO - LSQ retry for 66/164 problematic fits (fit_shape (7, 7) -> (9, 9), xy_bounds 2.70 -> 1.89).
09:37:08 - INFO - Fitted 300 sources in 4.61s
09:37:08 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:37:08 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:37:08 - INFO -
— Zeropoint: clean sequence stars —

09:37:08 - INFO - Removing 131 sources with detection threshold < 3.0
09:37:08 - INFO - Removing 67 sources with FLAGS > 2 from zeropoint calibration.
09:37:08 - INFO - Removing 132 sources with |inst_AP - inst_PSF| > 0.50 mag from zeropoint calibration.
09:37:08 - INFO - 102 sources remaining after quality cuts
09:37:08 - INFO -
— Linearity: saturation check (102 sources) —

09:37:08 - INFO - Removing 10 sources with threshold < 5
09:37:08 - INFO - Selected 15 high S/N sources (SNR >= 100) for linearity fit
09:37:08 - INFO - Constrained fit results:  Zeropoint = 24.620 +/- 2.188
09:37:08 - INFO - Linearity range (0.5-95% flux percentiles): 552.5 - 7625.5
09:37:08 - INFO - Applying tight residual filter: removed 22 sources
09:37:08 - INFO - Returning 122 linear sources
09:37:08 - INFO - Catalog linearity check: 12 linear sources, ZP=24.620 +/- 2.188
09:37:08 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:37:08 - INFO - fit_color_term: using polynomial order 1 (linear)
09:37:08 - INFO - fit_color_term: color distribution before filtering: min=0.307, max=0.877, median=0.523, n_sources=89
09:37:12 - INFO - fit_color_term: RANSAC found 76 inliers
09:37:12 - INFO - fit_color_term: fitted linear color term: slope=-0.8865, intercept=25.1075, n_inliers=76, color_range=0.570 mag
09:37:13 - INFO - Estimating zeropoint via sigma clipping.
09:37:13 - INFO - [AP] Before color correction: ZP=24.621, std=0.149, color_term=-0.8865
09:37:13 - INFO - [AP] Zeropoint: 25.043 +/- 0.020 mag
09:37:13 - INFO - [PSF] Before color correction: ZP=24.734, std=0.149, color_term=-0.8865
09:37:13 - INFO - [PSF] Zeropoint: 25.151 +/- 0.019 mag
09:37:13 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:37:13 - INFO - Background mesh: fwhm=2.76 px  mesh_scale=4.00  box_size=(11, 11)  filter_size=3
09:37:13 - INFO - Local background: box_size=(11, 11)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:37:13 - INFO - Source mask contains 0 pixels (0.00% of the image) after 1 iteration(s)
09:37:13 - INFO - Local background: adding a bias of +4.6806 to the local cutout residual (and -4.6806 to the local background surface) to enforce median >= 4.67142.
  Annulus_std=2.33571, annulus_k=2.
09:37:13 - INFO - Local background: subtracted cutout median=-0.00918128; raised cutout by 4.6806 so median >= 4.67142 on 19044 pixels.
09:37:13 - INFO - Source mask contains 41961 pixels (16.01% of the image) after 2 iteration(s)
09:37:13 - INFO - Background mesh: fwhm=2.76 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:37:13 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:37:13 - INFO - Target cutout: keeping uniform bias level 4.6806 in measurement image (shifted mean enabled).
09:37:13 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:37:13 - INFO - Transient's expected location: x = 367.421 pixels, y = 261.079 pixels
09:37:13 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:37:13 - INFO - Target PSF fitting bound: 2.000 arcsec (2.83 px at 0.707 arcsec/px)
09:37:13 - INFO -
— PSF photometry: 1 sources —

09:37:13 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.707 arcsec/px
    base_xy_bounds=2.83 px
    effective per tier (bright/faint/very-faint)=2.83/2.83/2.83 px
09:37:13 - INFO - Fit shapes:
    bright=(13, 13)
    faint=(11, 11)
    very-faint=(11, 11)
    xy_bounds=2.83 px
    undersampled=False
09:37:13 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.707 arcsec/px
09:37:13 - INFO - Target PSF: after bootstrap - flux_all[0]=292, x_all[0]=21, y_all[0]=21, valid=True
09:37:13 - INFO - Target PSF: using aperture-matched local background annulus (r_in=8.00 px, r_out=14.00 px, estimator=median).
09:37:13 - INFO - Fitting 1 bright sources (LSQ)
09:37:13 - INFO - Fitted 1 sources in 0.02s
09:37:13 - INFO - Target background debug: sky_bkg_total=361.933  noiseSky=0.0943546
09:37:13 - INFO - Converting cutout-local to full-image: cutout_x0=346.42, cutout_y0=240.08
09:37:13 - INFO -   x_pix: 21.000 -> 367.421
09:37:13 - INFO -   y_pix: 21.000 -> 261.079
09:37:13 - INFO -   x_fit: 20.441 -> 366.863
09:37:13 - INFO -   y_fit: 23.829 -> 263.908
09:37:13 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):

[10/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_g_wcs_ultracam_20260220_bkg_sub.fits

09:37:16 - INFO -
— File: EP260131a_g_wcs_ultracam_20260219_bkg_sub_APT.fits —

09:37:16 - INFO - Full path:
  /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_g_wcs_ultracam_20260219_bkg_sub/EP260131a_g_wcs_ultracam_20260219_bkg_sub_APT.fits
09:37:16 - INFO - Start time: 2026-05-18 09:37:16.633388
09:37:16 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:37:16 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:37:16 - INFO - Exposure time: 31.159 s (header keyword EXPTIME)
09:37:16 - INFO - Pixel scale from WCS: 0.354 arcsec/pixel
09:37:16 - INFO - Gain: 1 e-/ADU (header keyword GAIN)
09:37:16 - INFO - Telescope: NTT
09:37:16 - INFO - Instrument: ULTRACAM
09:37:16 - INFO - Filter: g
09:37:16 - INFO - MJD: 61178.401
09:37:16 - INFO - Read noise: 0.000 e/pixel
09:37:16 - INFO - Saturation level: inf ADU
09:37:16 - INFO - Pixel scale: 0.354 arcsec/pixel
09:37:16 - INFO - Date of observation: 2026-05-18
09:37:16 - INFO -
-------------------
Image preprocessing
-------------------

09:37:16 - INFO - Target position for NaN trimming: (732.8, 528.8)
09:37:16 - INFO - NaN boundary trimming: image shape (1024, 1024)
09:37:16 - INFO - NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
09:37:16 - INFO - NaN boundary trimming: skipped (all NaNs: False, no NaNs: True)
09:37:17 - INFO - Target pixel coordinates refreshed after trimming: (732.8, 528.8)
09:37:17 - INFO -
-------------------------
Source detection and FWHM
-------------------------

09:37:17 - INFO - SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
09:37:17 - INFO -
— SExtractor: EP260131a_g_wcs_ultracam_20260219_bkg_sub_APT.fits (default) —

09:37:17 - INFO - Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
09:37:17 - INFO - Creating convolution kernel with FWHM: 3.0 pixels
09:37:17 - INFO - Initial source count: 465
09:37:17 - INFO - Rejected 1 sources outside FWHM range [1.1, 100.0]
09:37:17 - INFO - Rejected 2 low-SNR sources (SNR < 3.0)
09:37:17 - INFO - Estimated FWHM: 5.60 pixels (sigma = 2.22 pixels)
09:37:17 - INFO - Rejected 59 sources with FLAGS > 2
09:37:17 - INFO - Filtering completed in 0.003 s (retained 403 of 465 initial sources)
09:37:17 - INFO - Filtered from 465 to 403 point sources
09:37:17 - INFO - Found 403 point sources, robust FWHM 5.50 px; scale = 17.0 (FWHM x 3.00 from source_detection / config)
09:37:17 - INFO -
------------------------
Background: initial pass
------------------------

09:37:17 - INFO -
— Background: sky & RMS —

09:37:17 - INFO - NaN pixels: 0 (0.00%)
09:37:17 - INFO - Background regime=sparse  bright_frac=0.019  large_scale_ratio=0.093
09:37:17 - INFO - Background mesh: fwhm=5.50 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:37:18 - INFO - Source mask contains 308036 pixels (29.38% of the image) after 2 iteration(s)
09:37:18 - INFO - Masked fraction (total): 29.38%
09:37:18 - INFO - box_size=(65, 65)  filter_size=3
09:37:18 - INFO - Global stats - mean -4.808e-02  median -4.867e-02  std 9.577e-01
09:37:18 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:37:18 - INFO - Background median -3.678e-02  RMS mean 9.404e-01
09:37:18 - INFO - Preliminary FWHM: 5.5 pixels
09:37:18 - INFO - Undersampled mode: False (FWHM=5.50 px, threshold=2.50 px)
09:37:18 - INFO -
---------------------------------
WCS: check header and plate solve
---------------------------------

09:37:19 - INFO - Pre-existing WCS found in header
09:37:19 - INFO - No variable sources found in input_yaml.
09:37:19 - INFO - Variable sources DataFrame is empty; no sources to check for image boundaries.
09:37:19 - INFO -
— TNS check: Transient —

09:37:19 - INFO - TNS RA/Dec: 149.902500, -3.307300
09:37:19 - INFO - Expected pixel position: (732.75, 528.77)
09:37:19 - INFO -
--------------------------------------------------
Background: masked pass (variable sources, SIMBAD)
--------------------------------------------------

09:37:19 - INFO -
— Background: sky & RMS —

09:37:19 - INFO - NaN pixels: 0 (0.00%)
09:37:19 - INFO - Background regime=sparse  bright_frac=0.019  large_scale_ratio=0.093
09:37:19 - INFO - Background mesh: fwhm=5.50 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:37:19 - INFO - Source mask contains 308036 pixels (29.38% of the image) after 2 iteration(s)
09:37:19 - INFO - Masked fraction (total): 29.38%
09:37:19 - INFO - box_size=(65, 65)  filter_size=3
09:37:19 - INFO - Global stats - mean -4.808e-02  median -4.867e-02  std 9.577e-01
09:37:20 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:37:20 - INFO - Background median -3.678e-02  RMS mean 9.404e-01
09:37:21 - INFO -
---------------
Target position
---------------

09:37:21 - INFO -
— 149.9025 -3.3073 —

09:37:21 - INFO - Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 149.902500 deg, Dec -3.307300 deg
  Pixel: (732.75, 528.77)
  Offset from image center: dx=+221.25 px, dy=+17.27 px
  Bounds: within bounds (min edge margin 290.25 px)
09:37:21 - INFO -
— 149.9025 -3.3073 —

09:37:22 - INFO -
— 149.9025 -3.3073 —

09:37:22 - INFO -
------------------------------------------------
Calibration stage: image, background, and weight
------------------------------------------------

09:37:22 - INFO - Reusing cached background results (fpath unchanged)
09:37:22 - INFO -
-----------------------------
Reference photometric catalog
-----------------------------

09:37:22 - INFO -
— Catalog: sequence sources in field —

09:37:22 - INFO - Existing PAN_STARRS catalog found for Transient
/home/liangrd/optical_data/EP260131a/NTT/catalog_queries/pan_starrs/transient/Transient_r_10.0arcmins_pan_starrs_target_ra_149.902500_dec_-3.307300.csv
09:37:22 - INFO - Cleaning 10000 sources
09:37:22 - INFO - Excluding 8161 sources with no g band information
09:37:22 - INFO - 1839 sources in output catalog
09:37:22 - INFO - Border filtering: removed 1320 sources outside border, 519 sources remaining
09:37:22 - INFO -
------------------------------------
Source detection on calibrated image
------------------------------------

09:37:22 - INFO -
— SExtractor: EP260131a_g_wcs_ultracam_20260219_bkg_sub_APT.fits (default) —

09:37:22 - INFO - Using FWHM = 5.5 pixels to construct the SExtractor convolution kernel
09:37:22 - INFO - Creating convolution kernel with FWHM: 5.5 pixels
09:37:22 - INFO - Initial source count: 285
09:37:22 - INFO - Rejected 1 sources outside FWHM range [1.1, 100.0]
09:37:22 - INFO - Rejected 2 low-SNR sources (SNR < 3.0)
09:37:22 - INFO - Estimated FWHM: 5.64 pixels (sigma = 2.30 pixels)
09:37:22 - INFO - Rejected 44 sources with FLAGS > 2
09:37:22 - INFO - Filtering completed in 0.002 s (retained 238 of 285 initial sources)
09:37:22 - INFO - Filtered from 285 to 238 point sources
09:37:22 - INFO - Found 238 point sources, robust FWHM 5.53 px; scale = 17.0 (FWHM x 3.00 from source_detection / config)
09:37:22 - INFO -
— SExtractor: EP260131a_g_wcs_ultracam_20260219_bkg_sub_APT.fits (default) —

09:37:22 - INFO - Using FWHM = 5.5 pixels to construct the SExtractor convolution kernel
09:37:22 - INFO - Creating convolution kernel with FWHM: 5.5 pixels
09:37:22 - INFO - Initial source count: 284
09:37:22 - INFO - Rejected 1 sources outside FWHM range [1.1, 100.0]
09:37:22 - INFO - Rejected 2 low-SNR sources (SNR < 3.0)
09:37:22 - INFO - Estimated FWHM: 5.65 pixels (sigma = 2.28 pixels)
09:37:22 - INFO - Rejected 44 sources with FLAGS > 2
09:37:22 - INFO - Filtering completed in 0.002 s (retained 237 of 284 initial sources)
09:37:22 - INFO - Filtered from 284 to 237 point sources
09:37:22 - INFO - Found 237 point sources, robust FWHM 5.54 px; scale = 17.0 (FWHM x 3.00 from source_detection / config)
09:37:22 - INFO - No cosmic ray pixels found. Skipping source exclusion.
09:37:22 - INFO - Cleaned 237 sources to 203 with isolation distance [17]
09:37:22 - INFO -
— Recentering 203 sources —

09:37:22 - INFO - Boxsize: 17 px, Border: 25 px (annulus outer=24.6, undersampled=False)
09:37:22 - INFO - Recentering 192 sources within border
09:37:22 - INFO - 192 sources have valid cutouts
09:37:22 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:37:22 - INFO - Median pixel correction: 0.0 px
09:37:22 - INFO - Recentered 192 sources
09:37:22 - INFO -
---------------------------------------------------
Aperture, optimum radius, and PSF on sequence stars
---------------------------------------------------

09:37:23 - INFO - Excluded 36 sources based on quality cuts (kept 156/192).
09:37:23 - INFO - Number of sources: 65
09:37:23 - INFO -
— Optimum aperture: 65 sources —

09:37:23 - INFO - Optimum-radius CoG mode: empirical (moffat_beta=4.765)
09:37:23 - INFO - Concentration gate rejected 2 broad sources (enc_flux(1.70*FWHM) < 0.50).
09:37:23 - INFO - Using 55 sources with stable profiles for optimum-radius and PSF selection.
09:37:23 - INFO - Returning 22 sources, optimum radius: 1.06 * FWHM, scale: 17.5
09:37:23 - INFO - Aperture radius: 7.00 [pixels] (optimum_radius=1.06 FWHM)
09:37:23 - INFO - Computing aperture correction using 22 isolated sources at radius 7.00 pixels
09:37:24 - INFO - Aperture correction: -0.061 +/- 0.017
09:37:24 - INFO - Aperture correction (AP to total): -0.061 +/- 0.017 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
09:37:24 - INFO - Found 519 sources in field
09:37:24 - INFO -
— Recentering 519 sources —

09:37:24 - INFO - Boxsize: 9 px, Border: 23 px (annulus outer=22.2, undersampled=False)
09:37:24 - INFO - Recentering 494 sources within border
09:37:24 - INFO - 494 sources have valid cutouts
09:37:24 - INFO - Using center-of-mass centroiding (FWHM >= 3 px)
09:37:24 - INFO - Failed to recenter 3 sources - ignoring
09:37:24 - INFO - Median pixel correction: 0.0 px
09:37:24 - INFO - Recentered 491 sources
09:37:24 - INFO -
— Aperture photometry: 491 field sources —

09:37:24 - INFO - Instrumental magnitude of 305 sources measured
09:37:24 - INFO -
— Downsampling: 491 sources -> 300 max —

09:37:24 - INFO - Using 17x17 grid with ~1 sources per bin
09:37:24 - INFO - Processing spatial bins...
09:37:24 - INFO - Bin statistics: min=0, max=8, avg=1.7 sources per bin
09:37:24 - INFO - Selected 198 sources from spatial bins
09:37:24 - WARNING - Only 198 sources selected from bins, filling with top 102 remaining sources
09:37:24 - INFO - Added 102 additional sources from remaining pool
09:37:24 - INFO - Final selection: 300 sources
09:37:24 - INFO - Downsampling complete
09:37:24 - INFO - Building ePSF from 22 sources
09:37:24 - INFO - FWHM=4.26 pix  recenter=centroid_com  oversample=1x
09:37:24 - INFO - Initial sources: 22
09:37:24 - INFO - Sources after cuts: 22
09:37:24 - INFO - Using 22/22 PSF candidates after spatial downselection
09:37:24 - INFO - [robust_extract_stars] Extracted 22 cutouts
09:37:24 - INFO - Rejected 4 PSF stars via FFT outlier filtering
09:37:24 - INFO - PSF build FWHM: input=5.54 px, used=4.26 px; normalisation radius=7.00 px (same as photometry aperture_radius); oversample=x1
09:37:24 - INFO -
— PSF: ePSF build details —

  make_template_psf: False
  candidates: initial=22, after_cuts=22, used_after_uniform=22
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.90
  geometry: fwhm_input=5.54px, fwhm_used=4.26px, fwhm_arcsec=1.51", pixel_scale=0.354 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=9px, fit_box=11px, cutout=43px
  normalization: aperture_radius=7.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
09:37:24 - INFO - PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 11 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 43 px, sigma_clip=4.00
  (15 iters)
09:37:24 - INFO - ePSF init kernel: moffat_beta=4.765, gamma=5.38591 px, size=43x43
09:37:26 - INFO - PSF sources roundness: 0.03 +/- 0.01
09:37:26 - INFO -
— PSF photometry: 300 sources —

09:37:26 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.354 arcsec/px
    base_xy_bounds=5.66 px
    effective per tier (bright/faint/very-faint)=5.66/5.4/5.4 px
09:37:26 - INFO - Fit shapes:
    bright=(17, 17)
    faint=(13, 13)
    very-faint=(13, 13)
    xy_bounds=5.66 px
    undersampled=False
09:37:26 - INFO - Fitting 136 bright sources (LSQ)
09:37:27 - INFO - Fitting 37 faint sources (LSQ)
09:37:27 - INFO - LSQ retry for 6/37 problematic fits (fit_shape (13, 13) -> (15, 15), xy_bounds 5.40 -> 3.78).
09:37:28 - INFO - Fitting 127 very faint sources (LSQ)
09:37:29 - INFO - LSQ retry for 83/127 problematic fits (fit_shape (13, 13) -> (15, 15), xy_bounds 5.40 -> 3.78).
09:37:30 - INFO - Fitted 300 sources in 4.04s
09:37:30 - WARNING - WCS vs PSF offset plot failed: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style,
  path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:37:30 - INFO -
-------------------------
Zeropoint and color terms
-------------------------

09:37:30 - INFO -
— Zeropoint: clean sequence stars —

09:37:30 - INFO - Removing 83 sources with detection threshold < 3.0
09:37:30 - INFO - Removing 89 sources with FLAGS > 2 from zeropoint calibration.
09:37:30 - INFO - Removing 97 sources with |inst_AP - inst_PSF| > 0.50 mag from zeropoint calibration.
09:37:30 - INFO - 154 sources remaining after quality cuts
09:37:30 - INFO -
— Linearity: saturation check (154 sources) —

09:37:30 - INFO - Removing 28 sources with threshold < 5
09:37:30 - INFO - Selected 16 high S/N sources (SNR >= 100) for linearity fit
09:37:30 - INFO - Post-RANSAC sigma clipping removed 6 additional outliers
09:37:30 - INFO - Constrained fit results:  Zeropoint = 25.305 +/- 0.045
09:37:30 - INFO - Linearity range (0.5-95% flux percentiles): 646.3 - 18613.7
09:37:30 - INFO - Applying tight residual filter: removed 14 sources
09:37:30 - INFO - Returning 86 linear sources
09:37:30 - INFO - Catalog linearity check: 10 linear sources, ZP=25.305 +/- 0.045
09:37:30 - INFO - Color term correction enabled (photometry.apply_colorterms=True); measuring and applying color term corrections to catalog sources.
09:37:30 - INFO - fit_color_term: using polynomial order 1 (linear)
09:37:30 - INFO - fit_color_term: color distribution before filtering: min=0.307, max=0.711, median=0.517, n_sources=86
09:37:30 - INFO - fit_color_term: RANSAC found 86 inliers
09:37:30 - INFO - fit_color_term: fitted linear color term: slope=-0.1137, intercept=25.3664, n_inliers=86, color_range=0.403 mag
09:37:30 - INFO - Estimating zeropoint via sigma clipping.
09:37:30 - INFO - [AP] Before color correction: ZP=25.305, std=0.012, color_term=-0.1137
09:37:30 - INFO - [AP] Zeropoint: 25.372 +/- 0.001 mag
09:37:30 - INFO - [PSF] Before color correction: ZP=25.365, std=0.012, color_term=-0.1137
09:37:30 - INFO - [PSF] Zeropoint: 25.422 +/- 0.002 mag
09:37:30 - ERROR - SourceCheck failed: OSError in plot.py:723
Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 129, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 903, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/__init__.py", line 880, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/plot.py", line 723, in source_check
    plt.style.use(os.path.join(dir_path, "autophot.mplstyle"))
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/matplotlib/style/core.py", line 131, in use
    raise OSError(
OSError: '/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/autophot.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
09:37:30 - INFO - Background mesh: fwhm=5.54 px  mesh_scale=4.00  box_size=(23, 23)  filter_size=3
09:37:30 - INFO - Local background: box_size=(23, 23)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
09:37:30 - INFO - Source mask contains 6976 pixels (9.16% of the image) after 2 iteration(s)
09:37:30 - INFO - Local background: adding a bias of +1.8382 to the local cutout residual (and -1.8382 to the local background surface) to enforce median >= 1.84371.
  Annulus_std=0.921856, annulus_k=2.
09:37:30 - INFO - Local background: subtracted cutout median=0.00550968; raised cutout by 1.8382 so median >= 1.84371 on 69200 pixels.
09:37:31 - INFO - Source mask contains 444284 pixels (42.37% of the image) after 2 iteration(s)
09:37:31 - INFO - Background mesh: fwhm=5.54 px  mesh_scale=10.00  box_size=(65, 65)  filter_size=3
09:37:31 - INFO - Background2D final: attempt=1 box_size=(65, 65) filter_size=3 exclude_percentile=90.0
09:37:31 - INFO - Target cutout: keeping uniform bias level 1.8382 in measurement image (shifted mean enabled).
09:37:31 - INFO -
----------------------------
Target photometry: Transient
----------------------------

09:37:31 - INFO - Transient's expected location: x = 732.752 pixels, y = 528.774 pixels
09:37:32 - INFO - Target AP: subtracting annulus median as measured (allowing negative local background).
09:37:32 - INFO - Target PSF fitting bound: 2.000 arcsec (5.66 px at 0.354 arcsec/px)
09:37:32 - INFO -
— PSF photometry: 1 sources —

09:37:32 - INFO - PSF fit bounds config:
    fitting_xy_bounds=2 arcsec
    pixel_scale=0.354 arcsec/px
    base_xy_bounds=5.66 px
    effective per tier (bright/faint/very-faint)=5.66/5.66/5.66 px
09:37:32 - INFO - Fit shapes:
    bright=(25, 25)
    faint=(19, 19)
    very-faint=(19, 19)
    xy_bounds=5.66 px
    undersampled=False
09:37:32 - INFO - Target-fit shape scaling:
    bright/faint/very-faint=3/2.5/2.5 * FWHM
    fit_sampling_boost=1
    target_boost=1.5
    pixel_scale=0.354 arcsec/px
09:37:32 - INFO - Target PSF: after bootstrap - flux_all[0]=649, x_all[0]=34, y_all[0]=34, valid=True
09:37:32 - INFO - Target PSF: using aperture-matched local background annulus (r_in=12.00 px, r_out=24.00 px, estimator=median).
09:37:32 - INFO - Fitting 1 bright sources (LSQ)
09:37:32 - INFO - Fitted 1 sources in 0.02s
09:37:32 - INFO - Target background debug: sky_bkg_total=294.733  noiseSky=0.0289127
09:37:32 - INFO - Converting cutout-local to full-image: cutout_x0=698.75, cutout_y0=494.77
09:37:32 - INFO -   x_pix: 34.000 -> 732.752
09:37:32 - INFO -   y_pix: 34.000 -> 528.774
09:37:32 - INFO -   x_fit: 31.528 -> 730.280
09:37:32 - INFO -   y_fit: 39.656 -> 534.430
09:37:32 - ERROR - Type     : ImportError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 5159
Message  : cannot import name 'decode_psf_flags' from 'photutils.psf'
  (/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/photutils/psf/__init__.py)

Traceback (most recent call last):

[11/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_g_wcs_ultracam_20260219_bkg_sub.fits

09:37:35 - INFO -
— File: EP260131a_g_wcs_ultracam_20260215_APT.fits —

09:37:35 - INFO - Full path: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_g_wcs_ultracam_20260215/EP260131a_g_wcs_ultracam_20260215_APT.fits
09:37:35 - INFO - Start time: 2026-05-18 09:37:35.033964
09:37:35 - INFO - telescope.yml loaded from: /home/liangrd/optical_data/EP260131a/NTT/telescope.yml
09:37:35 - INFO - Invalid MJD detected; setting MJD to today's value: 61178.4
09:37:35 - ERROR - Type     : ValueError
File     : /home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py
Line     : 1169
Message  : No valid exposure time in FITS header for
  PosixPath('/home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_g_wcs_ultracam_20260215/EP260131a_g_wcs_ultracam_20260215_APT.fits'): No valid
  exposure time in FITS header; tried keys ['EXPTIME', 'EXPOSURE', 'TEXP', 'EXPTIME0', 'TEXPTIME', 'INTTIME', 'EXPTIM']. Add EXPTIME or EXPOSURE
  (seconds).

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 1150, in run_photometry
    exposure_time, used_exptime_key = exposure_seconds_from_header(header, pref)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/aperture.py", line 178, in exposure_seconds_from_header
    raise ValueError(
ValueError: No valid exposure time in FITS header; tried keys ['EXPTIME', 'EXPOSURE', 'TEXP', 'EXPTIME0', 'TEXPTIME', 'INTTIME', 'EXPTIM']. Add
  EXPTIME or EXPOSURE (seconds).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/main.py", line 1169, in run_photometry
    raise ValueError(
ValueError: No valid exposure time in FITS header for
  PosixPath('/home/liangrd/optical_data/EP260131a/NTT_REDUCED/EP260131a_g_wcs_ultracam_20260215/EP260131a_g_wcs_ultracam_20260215_APT.fits'): No valid
  exposure time in FITS header; tried keys ['EXPTIME', 'EXPOSURE', 'TEXP', 'EXPTIME0', 'TEXPTIME', 'INTTIME', 'EXPTIM']. Add EXPTIME or EXPOSURE
  (seconds).

Processing: 100%|██████████| 12/12 [02:48<00:00, 14.03s/file]
09:37:35 - INFO - Concatenated 1 rows of tabular data into '/home/liangrd/optical_data/EP260131a/NTT_REDUCED/lightcurve_output.csv'.

[12/12] [OK]    /home/liangrd/optical_data/EP260131a/NTT/EP260131a_g_wcs_ultracam_20260215.fits



— Collect photometry: /home/liangrd/optical_data/EP260131a/NTT_REDUCED —

Photometry pipeline completed in 169.130 seconds.
Results saved to: /home/liangrd/optical_data/EP260131a/NTT_REDUCED/lightcurve_output.csv

In [15]:
import requests
import pandas as pd
import numpy as np
                        
ra = 149.9025
dec = -3.3073
radius_deg = 0.1
                        
# Direct MAST API call for Pan-STARRS
url = url = "https://catalogs.mast.stsci.edu/api/v0.1/panstarrs/dr2/mean"
params = {
    "ra": ra,
    "dec": dec,
    "radius": radius_deg,
    "pagesize": 10000,
    "format": "json"
    }
                        
response = requests.get(url, params=params, timeout=60)
response.raise_for_status()
data = response.json()

                        
if not data:
    electedCatalog = pd.DataFrame()
else:
# Convert to DataFrame, handling None strings
    cols = [data['info'][i]['name'] for i in range(len(data['info']))]
    selectedCatalog = pd.DataFrame(data['data'],columns=cols)

# Replace all forms of None/null with np.nan
    for col in selectedCatalog.columns:
        if selectedCatalog[col].dtype == object:
                                    selectedCatalog[col] = selectedCatalog[col].replace(
                                        ['None', 'none', 'NONE', 'null', 'NULL', 'nan', 'NaN'], np.nan
                                    )
    # Convert numeric columns
    for col in selectedCatalog.columns:
        if col not in ['objName', 'objAltName1', 'objAltName2', 'objAltName3']:
            try:
                selectedCatalog[col] = pd.to_numeric(selectedCatalog[col], errors='coerce')
            except Exception:
                pass                      
                # except Exception as api_exc:
                #         logger.warning(f"Direct Pan-STARRS API failed ({api_exc}), using empty catalog")
                #         selectedCatalog = pd.DataFrame()
                    
# Replace all common null representations
selectedCatalog = selectedCatalog.replace([-999, -999.0, "None", "none", "NONE", "null", "NULL"], np.nan)
columns = [
                        "raMean",
                        "decMean",
                        "raMeanErr",
                        "decMeanErr",
                        "gMeanPSFMag",
                        "gMeanPSFMagErr",
                        "rMeanPSFMag",
                        "rMeanPSFMagErr",
                        "iMeanPSFMag",
                        "iMeanPSFMagErr",
                        "zMeanPSFMag",
                        "zMeanPSFMagErr",
                        "yMeanPSFMag",
                        "yMeanPSFMagErr",
                    ]
selectedCatalog = selectedCatalog[columns]

In [17]:
selectedCatalog

,raMean,decMean,raMeanErr,decMeanErr,gMeanPSFMag,gMeanPSFMagErr,rMeanPSFMag,rMeanPSFMagErr,iMeanPSFMag,iMeanPSFMagErr,zMeanPSFMag,zMeanPSFMagErr,yMeanPSFMag,yMeanPSFMagErr
0,149.867420,-3.400961,0.02027,0.02027,NaN,NaN,NaN,NaN,18.491199,0.013639,NaN,NaN,NaN,NaN
1,149.903243,-3.337126,0.15781,0.15781,NaN,NaN,21.327101,0.427746,NaN,NaN,NaN,NaN,NaN,NaN
2,149.903353,-3.334899,0.01553,0.01553,NaN,NaN,NaN,NaN,NaN,NaN,16.557899,0.004028,NaN,NaN
3,149.904030,-3.334530,0.01776,0.01776,NaN,NaN,NaN,NaN,NaN,NaN,17.524099,0.009503,NaN,NaN
4,149.904596,-3.338761,0.28444,0.28444,NaN,NaN,NaN,NaN,21.210501,0.284047,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,149.956071,-3.321201,0.01618,0.01618,17.238001,0.005908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,149.956445,-3.318800,0.21728,0.21728,NaN,NaN,NaN,NaN,NaN,NaN,20.944700,0.216764,NaN,NaN
9997,149.956955,-3.320192,0.25385,0.25385,NaN,NaN,NaN,NaN,17.620199,0.253411,NaN,NaN,NaN,NaN
9998,149.956955,-3.323005,0.23360,0.23360,NaN,NaN,NaN,NaN,18.852501,0.233115,NaN,NaN,NaN,NaN
9999,149.957183,-3.321400,0.01640,0.01640,17.403500,0.006541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
cols = [data['info'][i]['name'] for i in range(len(data['info']))]
cols

['objName',
 'objAltName1',
 'objAltName2',
 'objAltName3',
 'objID',
 'uniquePspsOBid',
 'ippObjID',
 'surveyID',
 'htmID',
 'zoneID',
 'tessID',
 'projectionID',
 'skyCellID',
 'randomID',
 'batchID',
 'dvoRegionID',
 'processingVersion',
 'objInfoFlag',
 'astrometryCorrectionFlag',
 'qualityFlag',
 'raStack',
 'decStack',
 'raStackErr',
 'decStackErr',
 'raMean',
 'decMean',
 'raMeanErr',
 'decMeanErr',
 'pmra',
 'pmdec',
 'pmraErr',
 'pmdecErr',
 'epochMean',
 'posMeanChisq',
 'cx',
 'cy',
 'cz',
 'lambda',
 'beta',
 'l',
 'b',
 'nStackObjectRows',
 'nStackDetections',
 'nDetections',
 'ng',
 'nr',
 'ni',
 'nz',
 'ny',
 'gQfPerfect',
 'gMeanPSFMag',
 'gMeanPSFMagErr',
 'gMeanPSFMagStd',
 'gMeanPSFMagNpt',
 'gMeanPSFMagMin',
 'gMeanPSFMagMax',
 'gMeanKronMag',
 'gMeanKronMagErr',
 'gMeanKronMagStd',
 'gMeanKronMagNpt',
 'gMeanApMag',
 'gMeanApMagErr',
 'gMeanApMagStd',
 'gMeanApMagNpt',
 'gFlags',
 'rQfPerfect',
 'rMeanPSFMag',
 'rMeanPSFMagErr',
 'rMeanPSFMagStd',
 'rMeanPSFMagNpt',
 'rMeanPSFMagMin',
 'rMeanPSFMagMax',
 'rMeanKronMag',
 'rMeanKronMagErr',
 'rMeanKronMagStd',
 'rMeanKronMagNpt',
 'rMeanApMag',
 'rMeanApMagErr',
 'rMeanApMagStd',
 'rMeanApMagNpt',
 'rFlags',
 'iQfPerfect',
 'iMeanPSFMag',
 'iMeanPSFMagErr',
 'iMeanPSFMagStd',
 'iMeanPSFMagNpt',
 'iMeanPSFMagMin',
 'iMeanPSFMagMax',
 'iMeanKronMag',
 'iMeanKronMagErr',
 'iMeanKronMagStd',
 'iMeanKronMagNpt',
 'iMeanApMag',
 'iMeanApMagErr',
 'iMeanApMagStd',
 'iMeanApMagNpt',
 'iFlags',
 'zQfPerfect',
 'zMeanPSFMag',
 'zMeanPSFMagErr',
 'zMeanPSFMagStd',
 'zMeanPSFMagNpt',
 'zMeanPSFMagMin',
 'zMeanPSFMagMax',
 'zMeanKronMag',
 'zMeanKronMagErr',
 'zMeanKronMagStd',
 'zMeanKronMagNpt',
 'zMeanApMag',
 'zMeanApMagErr',
 'zMeanApMagStd',
 'zMeanApMagNpt',
 'zFlags',
 'yQfPerfect',
 'yMeanPSFMag',
 'yMeanPSFMagErr',
 'yMeanPSFMagStd',
 'yMeanPSFMagNpt',
 'yMeanPSFMagMin',
 'yMeanPSFMagMax',
 'yMeanKronMag',
 'yMeanKronMagErr',
 'yMeanKronMagStd',
 'yMeanKronMagNpt',
 'yMeanApMag',
 'yMeanApMagErr',
 'yMeanApMagStd',
 'yMeanApMagNpt',
 'yFlags',
 'distance']

In [14]:
pd.DataFrame(data['data'],columns=cols)

,objName,objAltName1,objAltName2,objAltName3,objID,uniquePspsOBid,ippObjID,surveyID,htmID,zoneID,...,yMeanKronMag,yMeanKronMagErr,yMeanKronMagStd,yMeanKronMagNpt,yMeanApMag,yMeanApMagErr,yMeanApMagStd,yMeanApMagNpt,yFlags,distance
0,PSO J149.8674-03.4010,-999,-999,-999,103911498673939288,3604974000100663,378077381232954,0,10554534216377,10391,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.099994
1,PSO J149.8726-03.4018,-999,-999,-999,103911498725808282,3604974000101295,378077381233586,0,10554534036893,10391,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.099088
2,PSO J149.8727-03.4006,-999,-999,-999,103911498727599787,3604974000125933,378077381260093,0,10554534050922,10391,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,16416,0.097880
3,PSO J149.8742-03.4015,-999,-999,-999,103911498742068654,3604974000046462,378077381178751,0,10554534050264,10391,...,-999.0000,-999.000000,-999.00000,0,26.0639,0.400649,-999.000000,1,4120,0.098313
4,PSO J149.8761-03.4027,-999,-999,-999,103911498761477130,3604974000126007,378077381260167,0,10554534041958,10391,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,16416,0.098992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,PSO J149.9857-03.3167,-999,-999,-999,104021499856960362,3604974000114400,378077381246691,0,10554621099854,10402,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.083610
9996,PSO J149.9861-03.3146,-999,-999,-999,104021499860982908,3604974000127986,378077381262146,0,10554621094614,10402,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,16416,0.083785
9997,PSO J149.9861-03.3156,-999,-999,-999,104021499861381731,3604974000114458,378077381246749,0,10554621096217,10402,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.083917
9998,PSO J149.9863-03.3116,-999,-999,-999,104021499862526446,3604974000057378,378077381189668,0,10554621038905,10402,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.083723
9999,PSO J149.9865-03.3113,-999,-999,-999,104021499865426807,3604974000057402,378077381189692,0,10554621042334,10402,...,16.3578,0.016665,0.04203,15,16.2768,0.009616,0.026111,15,115000,0.084008

In [ ]:
#!/usr/bin/env python3
"""
Example AutoPhOT driver script.
"""
import os
from autophot import AutomatedPhotometry, prepare_template_directory

# Load default configuration
config = AutomatedPhotometry.load()
config["nCPU"] = 4  # Parallel processing

# Paths
config["outdir_name"] = "REDUCED"
config["wdir"] = "/home/liangrd/optical_data/EP260131a/NTT"
config["fits_dir"] = FITS_DIR

# Target coordinates
config["target_name"] = "EP260131a"
config["target_ra"] = 149.9025
config["target_dec"] = -3.3073

# Photometric catalogs by filter
config["catalog"]["use_catalog"] = {
    "griz": "pan_starrs",
    "u": "gaia", 
    "UBVRI": "apass",
}

# Processing options
config["cosmic_rays"]["remove_cmrays"] = False
config["wcs"]["redo_wcs"] = True

# Enable template subtraction
config["template_subtraction"]["do_subtraction"] = False
# config["template_subtraction"]["method"] = "sfft"
# config["template_subtraction"]["alignment_method"] = "swarp"  # SCAMP+SWarp onto science grid (recommended)

# Create template directories
prepare_template_directory(
    fits_dir=config["fits_dir"],
    include_legacy_p_folders=False,
    confirm_before_continue=True,
)

# Run photometry
output = AutomatedPhotometry.run_photometry(default_input=config, do_photometry=True)

# Generate plots and tables
from lightcurve import plot_lightcurve, generate_photometry_table
plot_lightcurve(output, snr_limit=3, method="PSF")
generate_photometry_table(output, snr_limit=3, method="PSF")

— Default input: /home/liangrd/autophot/databases/default_input.yml —

Configuration loaded in 0.059 seconds.



— Template directory prepared: /home/liangrd/optical_data/EP260131a/NTT/templates —

Template folder summary: created=13 existing=0 filters=U,B,V,R,I,u,g,r,i,z,J,H,K

KeyError: 'ps1'