# AutoPhot Learning

In [1]:
#Pre-Processing
import glob, os
from astropy.io import fits
# FITS_DIR = "/home/liangrd/optical_data/EP260131a/NTT/"
# bands = ['u','g','r']
# TELESCOP = 'NTT'
# INSTRUME = 'ultracam'

FITS_DIR = '/home/liangrd/optical_data/EP260518a/TRT'
bands = ['Rc','Ic','V']
TELESCOP = 'TRT'
INSTRUME = 'RED'

for band in bands:
    flist = glob.glob(os.path.join(FITS_DIR,f'**_{band}_**.fits'))
    for f in flist:
        hdul = fits.open(f)
        header = hdul[0].header
        
        if not header.get('TELESCOP',None):
            header['TELESCOP'] = TELESCOP
        
        if not header.get('INSTRUME',None):
            header['INSTRUME'] = INSTRUME
            
        if not header.get('FILTER',None):
            if band in ['Rc','Ic']:
                band = band[0].lower()
            print(band)
            header['FILTER'] = band
        
        if band in ['Rc','Ic']:
            band = band[0].lower()
        print(band)
        header['FILTER'] = band
            
        if not header.get('GAIN',None):
            header['GAIN'] = 1.0
        
        hdul[0].header = header
        
        hdul.writeto(f,overwrite=True)

r
i
V

In [2]:
import photutils

print(photutils.__version__)
from photutils.psf import decode_psf_flags

/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

3.0.0

In [2]:
from autophot import AutomatedPhotometry

# Load default configuration
config = AutomatedPhotometry.load()

# Set basic parameters
config["outdir_name"] = "REDUCED"
config["wdir"] =  '/home/liangrd/optical_data/EP260518a/TRT'
config["fits_dir"] =  '/home/liangrd/optical_data/EP260518a/TRT'
config["target_ra"] = 299.04067125
config["target_dec"] = -48.63621125
config["template_subtraction"]["do_subtraction"] = False
config["catalog"]["use_catalog"] = {
    "griz": "skymapper",
    "u": "skymapper", 
    "UBVRI": "apass",
}
config['catalog']

# config["cosmic_rays"]["remove_cmrays"] = False
config["wcs"]["redo_wcs"] = False
# config[""]OK




# Run photometry
output_file = AutomatedPhotometry.run_photometry(default_input=config)
print(f"Results saved to: {output_file}")

/home/liangrd/anaconda3/envs/autophot/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
04:55:27  Ignoring unsupported/non-photometric catalog keys: B_err, DEC, DEC_err, RA, RA_err, V_err, g_err, i_err, name, r_err, usky_err, vsky_err, z_err
  Skipping TNS query because target_ra/target_dec are already provided (299.040671, -48.636211).
  Restart = True -> reprocess all files (ignore existing OUTPUT_{base}.csv)
  Scanned 3 FITS file(s): 0 completed (OUTPUT present), 3 pending.
  Initialized: 3 files
  [File check: 3 FITS]
  [Headers (basic)]

[Configuration]
Configuration loaded in 0.027 seconds.
----------------------------------------------------------------------
+                     AutoPhOT Photometry Run                      +
----------------------------------------------------------------------
Available filters: ['usky', 'vsky', 'g', 'r', 'i', 'z', 'V', 'B']
[TNS check]
[WARNING] TNS lookup skipped; using target_ra/target_dec values from the configuration.

100%|██████████| 3/3 [00:00<00:00, 418.33it/s]

04:55:28  Telescopes discovered in headers: CDK700
  [Filters: 3 files]
100%|██████████| 3/3 [00:00<00:00, 464.61it/s]
  Header check complete: 3/3 files OK.
  telescope.yml loaded from: /home/liangrd/optical_data/EP260518a/TRT/telescope.yml
  [Filter check]
  Checking 3 image(s). Catalog bands: B, V, g, i, r, usky, vsky, z

  Progress completed: 3/3 item(s).
    Retained: 3 file(s) with filters: V, i, r

Querying SIMBAD within 10' of 19h56m09.7611s -48d38m10.3605s.
SIMBAD variable-source query finished in 1.9s (server time: 0.3s).
Most common SIMBAD object types in field: Galaxy (1), RR Lyr (1)
[Reduce/calibrate science files]

Processing:   0%|          | 0/3 [00:00<?, ?file/s]04:55:33  [File: EP260518a_TRT_20260523_AUS_V_stack_bgsub_reproject_wmean_APT.fits]
  telescope.yml loaded from: /home/liangrd/optical_data/EP260518a/TRT/telescope.yml
  Exposure time: 800 s (header keyword EXPTIME)
  Pixel scale from WCS: 0.587 arcsec/pixel
  Gain: 1 e-/ADU (header keyword GAIN)
  Telescope: CDK700, Instrument: Andor_DU934P_BV, Filter: V
  Pixel scale: 0.587 arcsec/pixel

──────────────────────────────────────────────────────────────────────
+                       Image preprocessing                        +
──────────────────────────────────────────────────────────────────────
  Target position for NaN trimming: (526.1, 564.0) px
  NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
  Target pixel coordinates refreshed after trimming: (526.1, 564.0) px

──────────────────────────────────────────────────────────────────────
+                    Source detection and FWHM                     +
──────────────────────────────────────────────────────────────────────
  SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
  [SExtractor: EP260518a_TRT_20260523_AUS_V_stack_bgsub_reproject_wmean_APT.fits (default)]
  Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
  Creating convolution kernel with FWHM: 3.0 pixels
  Initial source count: 420
  Rejected 2 sources outside FWHM range [1.1, 100.0]
  Estimated FWHM: 4.12 pixels (sigma = 2.39 pixels)
  Rejected 48 sources with FLAGS > 2
  Filtering completed in 0.003 s (retained 370 of 420 initial sources)
  Filtered from 420 to 370 point sources
  Found 370 point sources, robust FWHM 4.07 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)

──────────────────────────────────────────────────────────────────────
+                     Background: initial pass                     +
──────────────────────────────────────────────────────────────────────
  [Background: sky & RMS]
  NaN pixels: 0 (0.00%)

04:55:34  Background regime=sparse  bright_frac=0.026  large_scale_ratio=0.181
  Background mesh: FWHM=4.07 px scale=10.0 box=(65, 65) filter=3
  Source mask contains 178939 pixels (17.06% of the image) after 2 iteration(s)
  Masked fraction (total): 17.06%
  box_size=(65, 65)  filter_size=3
  Global stats: mean=-9.936e-01 med=-1.352e+00 std=9.541e+00

04:55:35  Background RMS statistics: median=7.071, mean=7.077, std=0.331, floor=1.000

──────────────────────────────────────────────────────────────────────
+                      Background estimation                       +
──────────────────────────────────────────────────────────────────────
  Attempt: 1 | Box: (65, 65) | Filter: 3 | Exclude: 90.0%
  Background median=-1.957e+00 RMS=7.077e+00
  Preliminary FWHM: 4.1 pixels
  Undersampled mode: False (FWHM=4.07 px, threshold=2.50 px)

──────────────────────────────────────────────────────────────────────
+                WCS: check header and plate solve                 +
──────────────────────────────────────────────────────────────────────
  Pre-existing WCS found in header
  Loaded 2 variable sources from input_yaml.
  Variable sources within image boundaries (1):
  [TNS check: Transient]
  TNS RA/Dec: 299.040671, -48.636211
  Expected pixel position: (526.08, 564.04)

──────────────────────────────────────────────────────────────────────
+        Background: masked pass (variable sources, SIMBAD)        +
──────────────────────────────────────────────────────────────────────
  [Background: sky & RMS]
  NaN pixels: 0 (0.00%)
  Background regime=sparse  bright_frac=0.026  large_scale_ratio=0.181
  Background mesh: FWHM=4.07 px scale=10.0 box=(65, 65) filter=3

04:55:36  Source mask contains 178939 pixels (17.06% of the image) after 2 iteration(s)
  Masked fraction (total): 17.06%
  box_size=(65, 65)  filter_size=3
  Global stats: mean=-9.936e-01 med=-1.352e+00 std=9.541e+00
  Background RMS statistics: median=7.071, mean=7.077, std=0.331, floor=1.000

──────────────────────────────────────────────────────────────────────
+                      Background estimation                       +
──────────────────────────────────────────────────────────────────────
  Attempt: 1 | Box: (65, 65) | Filter: 3 | Exclude: 90.0%

04:55:37  Background median=-1.957e+00 RMS=7.077e+00

──────────────────────────────────────────────────────────────────────
+                         Target position                          +
──────────────────────────────────────────────────────────────────────
  [299.04067125 -48.63621125]
  Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 299.040671 deg, Dec -48.636211 deg
  Pixel: (526.08, 564.04)
  Offset from image center: dx=+14.58 px, dy=+52.54 px
  Bounds: within bounds (min edge margin 458.96 px)
  [299.04067125 -48.63621125]
  [299.04067125 -48.63621125]

──────────────────────────────────────────────────────────────────────
+         Calibration stage: image, background, and weight         +
──────────────────────────────────────────────────────────────────────
  Reusing cached background results (fpath unchanged)

──────────────────────────────────────────────────────────────────────
+                  Reference photometric catalog                   +
──────────────────────────────────────────────────────────────────────
  [Catalog: sequence sources in field]
  Existing APASS catalog found for Transient
/home/liangrd/optical_data/EP260518a/TRT/catalog_queries/apass/transient/Transient_r_10.0arcmins_apass_target_ra_299.040671_dec_-48.636211.csv
  Cleaning 115 sources
  Excluding 6 sources with no V band information
  109 sources in output catalog
  Border filtering: removed 75 sources outside border, 34 sources remaining

04:55:43 - WARNING - Border filtering removed 68.8% of sources; skipping border filter to preserve catalog sources

──────────────────────────────────────────────────────────────────────
+               Source detection on calibrated image               +
──────────────────────────────────────────────────────────────────────
  [SExtractor: EP260518a_TRT_20260523_AUS_V_stack_bgsub_reproject_wmean_APT.fits (default)]
  Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
  Creating convolution kernel with FWHM: 3.0 pixels

04:55:44  Initial source count: 426
  Rejected 2 sources outside FWHM range [1.1, 100.0]
  Estimated FWHM: 4.09 pixels (sigma = 2.36 pixels)
  Rejected 1 sources within 8.18 pixels of masked regions
  Rejected 48 sources with FLAGS > 2
  Filtering completed in 0.051 s (retained 375 of 426 initial sources)
  Filtered from 426 to 375 point sources
  Found 375 point sources, robust FWHM 4.07 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
  [SExtractor: EP260518a_TRT_20260523_AUS_V_stack_bgsub_reproject_wmean_APT.fits (default)]
  Using FWHM = 4.1 pixels to construct the SExtractor convolution kernel
  Creating convolution kernel with FWHM: 4.1 pixels
  Initial source count: 376
  Rejected 1 sources outside FWHM range [1.1, 100.0]
  Estimated FWHM: 4.07 pixels (sigma = 2.49 pixels)
  Rejected 1 sources within 8.15 pixels of masked regions
  Rejected 48 sources with FLAGS > 2
  Filtering completed in 0.071 s (retained 326 of 376 initial sources)
  Filtered from 376 to 326 point sources
  Found 326 point sources, robust FWHM 4.02 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
  No cosmic ray pixels found. Skipping source exclusion.
  Cleaned 326 sources to 296 with isolation distance [15]
  [Recentering 296 sources]
  Boxsize: 15 px, Border: 18 px (annulus outer=17.9, undersampled=False)
  Recentering 290 sources within border
  290 sources have valid cutouts
  Using center-of-mass centroiding (FWHM >= 3 px)
  Median pixel correction: 0.0 px
  Recentered 290 sources

──────────────────────────────────────────────────────────────────────
+       Aperture, optimum radius, and PSF on sequence stars        +
──────────────────────────────────────────────────────────────────────
  Excluded 26 sources based on quality cuts (kept 264/290).

04:55:45  Number of sources: 80
  [Optimum aperture: 80 sources]
  Optimum-radius CoG mode: empirical (moffat_beta=4.765)
  Using 80 sources with stable profiles for optimum-radius and PSF selection.
  Returning 70 sources, optimum radius: 1.69 * FWHM, scale: 15.5
  Aperture radius: 7.00 [pixels] (optimum_radius=1.69 FWHM)
  Computing aperture correction using 70 isolated sources at radius 7.00 pixels
  Aperture correction: -0.067 +/- 0.011
  Aperture correction (AP to total): -0.067 +/- 0.011 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
  Found 109 sources in field
  [Recentering 109 sources]
  Boxsize: 7 px, Border: 19 px (annulus outer=18.1, undersampled=False)
  Recentering 30 sources within border
  30 sources have valid cutouts
  Using center-of-mass centroiding (FWHM >= 3 px)
  Median pixel correction: 0.0 px
  Recentered 30 sources
  [Aperture photometry: 30 field sources]
  Instrumental magnitude of 30 sources measured
  Downsampling skipped: 30 sources (<= 300 target).
  Matched 28/30 catalog sources to SExtractor FWHM
  Building PSF from aligned image (psf_build_from_aligned=True).
  Building ePSF from 70 sources
  FWHM=3.83 pix  recenter=centroid_com  oversample=1x
  Initial sources: 70
  Sources after cuts: 70
  Using 70/70 PSF candidates after spatial downselection

04:55:46  [robust_extract_stars] Extracted 70 cutouts
  Rejected 3 PSF stars via FFT outlier filtering
  PSF build FWHM: input=4.02 px, used=3.83 px; normalisation radius=7.00 px (same as photometry aperture_radius); oversample=x1
  [PSF: ePSF build details]
  make_template_psf: False
  candidates: initial=70, after_cuts=70, used_after_uniform=70
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.90
  geometry: fwhm_input=4.02px, fwhm_used=3.83px, fwhm_arcsec=2.25", pixel_scale=0.587 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=9px, fit_box=9px, cutout=39px
  normalization: aperture_radius=7.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
  PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 9 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 39 px, sigma_clip=4.00
  (15 iters)
  ePSF init kernel: moffat_beta=4.765, gamma=4.83682 px, size=39x39
  ePSF build: converged=False, iterations=5, final_center_accuracy=0.03994 px
  ePSF did not converge in 5 iterations; retrying with 10 iterations

04:55:48 - WARNING - ePSF did NOT converge even with 10 iterations

04:55:49  PSF sources roundness: 0.03 +/- 0.01
  [PSF photometry: 30 sources]
  PSF fit bounds config:
  fitting_xy_bounds: 1 arcsec
  pixel_scale: 0.587 arcsec/px
  base_xy_bounds: 1.7 px
    effective per tier (bright/faint/very-faint)=1.7/1.7/1.7 px
  Fit shapes:
  bright: (13, 13)
  faint: (11, 11)
  very-faint: (11, 11)
  xy_bounds: 1.7 px
  undersampled: False
  Fitting 30 bright sources (LSQ)
  LSQ retry for 3/30 problematic fits (fit_shape (13, 13) -> (15, 15), xy_bounds 1.70 -> 1.19).
  Fitted 30 sources in 0.28s

04:55:50  Saved WCS vs PSF offset plot:
  /home/liangrd/optical_data/EP260518a/TRT_REDUCED/EP260518a_TRT_20260523_AUS_V_stack_bgsub_reproject_wmean/WCS_vs_PSF_Offset_EP260518a_TRT_20260523_AUS_V_stack_bgsub_reproject_wmean_APT.png
  WCS vs PSF offset statistics:
  Median: (-0.045, -0.047) px
  RMS: (0.430, 0.389) px

──────────────────────────────────────────────────────────────────────
+                    Zeropoint and color terms                     +
──────────────────────────────────────────────────────────────────────
  [Zeropoint: clean sequence stars]
  Removing 1 sources outside magnitude range 11.00-22.00 mag
  Removing 3 sources with FLAGS > 2 from zeropoint calibration.
  26 sources remaining after quality cuts
  [Linearity: saturation check (26 sources)]
  Removing 0 sources with threshold < 5
  Selected 26 high S/N sources (SNR >= 100) for linearity fit
  Post-RANSAC sigma clipping removed 4 additional outliers
  Constrained fit results:  Zeropoint = 20.679 +/- 0.041
  Linearity range (0.5-95% flux percentiles): 40.3 - 677.5
  Returning 22 sources for zeropoint fitting
  Catalog linearity check: 22 linear sources, ZP=20.679 +/- 0.041
  Color term correction disabled (photometry.apply_colorterms=False).
  Fitting zeropoints vs m_inst.

04:55:50 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 10;
tau: [27.36092474 35.18317556]

04:55:50 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 20;
tau: [31.183537   36.86778377]

04:55:50 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 30;
tau: [32.62527198 32.30617779]

04:55:50 - WARNING - ZP MCMC low ESS: n_eff ≈ 29 (chain 999, tau ≈ 34.9)
  MCMC (robust): ZP=20.6835 ± 0.0097, f_out=0.035 (19/19 inliers, n_walkers=9, n_steps=2000)
  [AP] ZP=20.683 +/- 0.010

04:55:51 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 10;
tau: [22.58649591 22.66938078]

04:55:51 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 20;
tau: [27.80268781 28.58680935]

04:55:51 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 1 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 30;
tau: [29.11764805 44.33444872]

04:55:51 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 1 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 40;
tau: [30.00006653 46.68243447]

04:55:51 - WARNING - ZP MCMC low ESS: n_eff ≈ 26 (chain 1170, tau ≈ 44.3)

04:55:51  MCMC (robust): ZP=20.7373 ± 0.0088, f_out=0.039 (19/19 inliers, n_walkers=9, n_steps=3000)
  [PSF] ZP=20.737 +/- 0.009

04:55:52  [fit_zeropoint] Done in 1.700s

04:55:52 - WARNING - Source check plot: WCS axes failed (WCSAxes has insufficient coords (n=0)), using pixel coordinates only

04:55:54  Background mesh: FWHM=4.02 px scale=4.0 box=(17, 17) filter=3
  Local background: box_size=(17, 17)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
  Source mask contains 3582 pixels (8.96% of the image) after 2 iteration(s)

04:55:55  Source mask contains 323913 pixels (30.89% of the image) after 2 iteration(s)
  Background mesh: FWHM=4.02 px scale=10.0 box=(65, 65) filter=3
  Background RMS statistics: median=7.003, mean=7.019, std=0.336, floor=1.000

──────────────────────────────────────────────────────────────────────
+                      Background estimation                       +
──────────────────────────────────────────────────────────────────────
  Attempt: 1 | Box: (65, 65) | Filter: 3 | Exclude: 90.0%
  Target cutout: keeping uniform bias level 13.1568 in measurement image (shifted mean enabled).

──────────────────────────────────────────────────────────────────────
+                   Target photometry: Transient                   +
──────────────────────────────────────────────────────────────────────
  Transient's expected location: x = 526.077 pixels, y = 564.042 pixels
  Target AP: subtracting annulus median as measured (allowing negative local background).

04:55:56  Target PSF fitting bound: 1.000 arcsec (1.70 px at 0.587 arcsec/px)
  [PSF photometry: 1 sources]
  PSF fit bounds config:
  fitting_xy_bounds: 1 arcsec
  pixel_scale: 0.587 arcsec/px
  base_xy_bounds: 1.7 px
    effective per tier (bright/faint/very-faint)=1.7/1.7/1.7 px
  Fit shapes:
  bright: (19, 19)
  faint: (17, 17)
  very-faint: (17, 17)
  xy_bounds: 1.7 px
  undersampled: False
  Target-fit shape scaling:
  bright/faint/very-faint: 3/2.5/2.5 * FWHM
  fit_sampling_boost: 1
  target_boost: 1.5
  pixel_scale: 0.587 arcsec/px
  Target PSF: after bootstrap - flux_all[0]=414, x_all[0]=27, y_all[0]=27, valid=True
  Target PSF: using aperture-matched local background annulus (r_in=11.00 px, r_out=20.00 px, estimator=median).
  Fitting 1 faint sources (LSQ)
  Fitted 1 sources in 0.02s
/home/liangrd/autophot/psf.py:4863: UserWarning: Legend does not support handles for PatchCollection instances.
See: https://matplotlib.org/stable/tutorials/intermediate/legend_guide.html#implementing-a-custom-legend-handler
  ax1.legend(loc="upper left")
  Target reduced chi2: 8.1e-01
  Target cfit: -1.7e-02
  Target qfit: 3.5e+00 (qfit of zero indicates a good fit)
  Transient fitted position: x = 526.748 +/- 0.327, y = 564.550 +/- 0.336
  Target SNR (aperture): 4.5
  Target SNR (PSF): 7.2
  Target threshold: 3.3 x background standard deviation
  Target detectability: 100.0 %
  Target location measured with FWHM: 4.8 px
  POSITION OFFSET ANALYSIS:
    Expected pixel position: (526.077, 564.042) px
    Fitted pixel position:   (526.748, 564.550) px
    Pixel offset: dx = +0.671 px, dy = +0.508 px
    Total pixel offset: 0.841 px
    Fitting uncertainty: 0.327, 0.336 px
    Sky offset: dRA = -0.421", dDec = -0.258"
    Total separation: 0.493 +/- 0.275 arcsec

──────────────────────────────────────────────────────────────────────
+           Calibrated magnitudes (AP and PSF on target)           +
──────────────────────────────────────────────────────────────────────
  Instrumental AP V-band magnitude: 0.715 +/- 0.218 [mag]
  Calibrated AP V-band magnitude: 21.399 +/- 0.219 [mag]
  Instrumental PSF V-band magnitude: 0.694 +/- 0.150 [mag]
  Calibrated PSF V-band magnitude: 21.431 +/- 0.150 [mag]

──────────────────────────────────────────────────────────────────────
+            Limiting magnitude (injection) near target            +
──────────────────────────────────────────────────────────────────────
  limiting_magnitude.recovery_method auto -> PSF (transient path: PSF)
  Limiting magnitude config:
  beta_limit: 0.5 (~3.00 sigma; n=3 beta formalism)
  detection_limit: None
  completeness_target: 0.50
    recovery_method=PSF
  Performing artificial source injection (beta_limit=0.500, snr_gate=off)
  Calculating injection limits for S/N thresholds: [3.0, 5.0]
  Calculating limiting magnitude for S/N >= 3.0

04:55:57  Injected limiting magnitude: initial guess from 5.0*sigma*sqrt(Npix) = 0.77 (sigma=0.00791, Npix=153.9, N=24)
  Found 965 valid candidate sites for injection
  inject m= +0.773 |  99.0%  (99/100 detected)

04:55:58  inject m= +1.273 |  97.0%  (97/100 detected)
  inject m= +1.773 |  57.0%  (57/100 detected)

04:55:59  inject m= +2.273 |  33.0%  (33/100 detected)
  inject m= +2.023 |  42.0%  (42/100 detected)

04:56:00  inject m= +1.898 |  49.0%  (49/100 detected)
  inject m= +1.836 |  52.0%  (52/100 detected)

04:56:01  inject m= +1.867 |  49.0%  (49/100 detected)
  inject m= +1.852 |  50.0%  (50/100 detected)
      Bisection converged: m50=1.8516 (bracket width=0.0156 mag)
  Limiting magnitude: inst=1.852  apparent=22.589  ZP=20.737  method=PSF  completeness=50%  trials=9  [4.8s]
  S/N 3.0 limiting magnitude: 1.852
  Calculating limiting magnitude for S/N >= 5.0
  Injected limiting magnitude: initial guess from 5.0*sigma*sqrt(Npix) = 0.77 (sigma=0.00791, Npix=153.9, N=24)

04:56:02  Found 954 valid candidate sites for injection
  inject m= +0.773 |  99.0%  (99/100 detected)

04:56:03  inject m= +1.273 |  45.0%  (45/100 detected)
  inject m= +1.023 |  88.0%  (88/100 detected)

04:56:04  inject m= +1.148 |  61.0%  (61/100 detected)
  inject m= +1.211 |  51.0%  (51/100 detected)


[1/3] [OK]    /home/liangrd/optical_data/EP260518a/TRT/EP260518a_TRT_20260523_AUS_V_stack_bgsub_reproject_wmean.fits

04:56:11  [File: EP260518a_TRT_20260523_AUS_Rc_stack_bgsub_reproject_wmean_APT.fits]
  telescope.yml loaded from: /home/liangrd/optical_data/EP260518a/TRT/telescope.yml
  Exposure time: 800 s (header keyword EXPTIME)
  Pixel scale from WCS: 0.587 arcsec/pixel
  Gain: 1 e-/ADU (header keyword GAIN)
  Telescope: CDK700, Instrument: Andor_DU934P_BV, Filter: r
  Pixel scale: 0.587 arcsec/pixel

──────────────────────────────────────────────────────────────────────
+                       Image preprocessing                        +
──────────────────────────────────────────────────────────────────────
  Target position for NaN trimming: (529.4, 561.4) px
  NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
  Target pixel coordinates refreshed after trimming: (529.4, 561.4) px

──────────────────────────────────────────────────────────────────────
+                    Source detection and FWHM                     +
──────────────────────────────────────────────────────────────────────
  SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
  [SExtractor: EP260518a_TRT_20260523_AUS_Rc_stack_bgsub_reproject_wmean_APT.fits (default)]
  Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
  Creating convolution kernel with FWHM: 3.0 pixels
  Initial source count: 532
  Rejected 3 sources outside FWHM range [1.1, 100.0]
  Estimated FWHM: 4.01 pixels (sigma = 3.02 pixels)
  Rejected 66 sources with FLAGS > 2
  Filtering completed in 0.005 s (retained 463 of 532 initial sources)
  Filtered from 532 to 463 point sources
  Found 463 point sources, robust FWHM 3.97 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)

──────────────────────────────────────────────────────────────────────
+                     Background: initial pass                     +
──────────────────────────────────────────────────────────────────────
  [Background: sky & RMS]
  NaN pixels: 0 (0.00%)

04:56:12  Background regime=sparse  bright_frac=0.031  large_scale_ratio=0.212
  Background mesh: FWHM=3.97 px scale=10.0 box=(65, 65) filter=3
  Source mask contains 217871 pixels (20.78% of the image) after 2 iteration(s)
  Masked fraction (total): 20.78%
  box_size=(65, 65)  filter_size=3
  Global stats: mean=-1.949e+00 med=-2.176e+00 std=1.365e+01
  Background RMS statistics: median=9.925, mean=10.009, std=0.468, floor=1.000

──────────────────────────────────────────────────────────────────────
+                      Background estimation                       +
──────────────────────────────────────────────────────────────────────
  Attempt: 1 | Box: (65, 65) | Filter: 3 | Exclude: 90.0%
  Background median=-2.572e+00 RMS=1.001e+01
  Preliminary FWHM: 4.0 pixels
  Undersampled mode: False (FWHM=3.97 px, threshold=2.50 px)

──────────────────────────────────────────────────────────────────────
+                WCS: check header and plate solve                 +
──────────────────────────────────────────────────────────────────────
  Pre-existing WCS found in header
  Loaded 2 variable sources from input_yaml.
  Variable sources within image boundaries (1):
  [TNS check: Transient]
  TNS RA/Dec: 299.040671, -48.636211
  Expected pixel position: (529.40, 561.36)

──────────────────────────────────────────────────────────────────────
+        Background: masked pass (variable sources, SIMBAD)        +
──────────────────────────────────────────────────────────────────────
  [Background: sky & RMS]
  NaN pixels: 0 (0.00%)
  Background regime=sparse  bright_frac=0.031  large_scale_ratio=0.212
  Background mesh: FWHM=3.97 px scale=10.0 box=(65, 65) filter=3
  Source mask contains 217871 pixels (20.78% of the image) after 2 iteration(s)
  Masked fraction (total): 20.78%
  box_size=(65, 65)  filter_size=3
  Global stats: mean=-1.949e+00 med=-2.176e+00 std=1.365e+01

04:56:14  Background RMS statistics: median=9.925, mean=10.009, std=0.468, floor=1.000

──────────────────────────────────────────────────────────────────────
+                      Background estimation                       +
──────────────────────────────────────────────────────────────────────
  Attempt: 1 | Box: (65, 65) | Filter: 3 | Exclude: 90.0%
  Background median=-2.572e+00 RMS=1.001e+01

──────────────────────────────────────────────────────────────────────
+                         Target position                          +
──────────────────────────────────────────────────────────────────────
  [299.04067125 -48.63621125]
  Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 299.040671 deg, Dec -48.636211 deg
  Pixel: (529.40, 561.36)
  Offset from image center: dx=+17.90 px, dy=+49.86 px
  Bounds: within bounds (min edge margin 461.64 px)
  [299.04067125 -48.63621125]
  [299.04067125 -48.63621125]

──────────────────────────────────────────────────────────────────────
+         Calibration stage: image, background, and weight         +
──────────────────────────────────────────────────────────────────────
  Reusing cached background results (fpath unchanged)

──────────────────────────────────────────────────────────────────────
+                  Reference photometric catalog                   +
──────────────────────────────────────────────────────────────────────
  [Catalog: sequence sources in field]
  Existing SKYMAPPER catalog found for Transient
/home/liangrd/optical_data/EP260518a/TRT/catalog_queries/skymapper/transient/Transient_r_10.0arcmins_skymapper_target_ra_299.040671_dec_-48.636211.csv
  Cleaning 736 sources
  Excluding 5 sources with no r band information
  731 sources in output catalog
  Border filtering: removed 499 sources outside border, 232 sources remaining

04:56:18 - WARNING - Border filtering removed 68.3% of sources; skipping border filter to preserve catalog sources

──────────────────────────────────────────────────────────────────────
+               Source detection on calibrated image               +
──────────────────────────────────────────────────────────────────────
  [SExtractor: EP260518a_TRT_20260523_AUS_Rc_stack_bgsub_reproject_wmean_APT.fits (default)]
  Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
  Creating convolution kernel with FWHM: 3.0 pixels
  Initial source count: 541
  Rejected 3 sources outside FWHM range [1.1, 100.0]
  Estimated FWHM: 4.02 pixels (sigma = 2.98 pixels)
  Rejected 1 sources within 8.04 pixels of masked regions
  Rejected 70 sources with FLAGS > 2
  Filtering completed in 0.059 s (retained 467 of 541 initial sources)
  Filtered from 541 to 467 point sources
  Found 467 point sources, robust FWHM 3.99 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
  [SExtractor: EP260518a_TRT_20260523_AUS_Rc_stack_bgsub_reproject_wmean_APT.fits (default)]
  Using FWHM = 4.0 pixels to construct the SExtractor convolution kernel
  Creating convolution kernel with FWHM: 4.0 pixels
  Initial source count: 472
  Rejected 2 sources outside FWHM range [1.1, 100.0]
  Estimated FWHM: 3.97 pixels (sigma = 3.21 pixels)

04:56:19  Rejected 1 sources within 7.94 pixels of masked regions
  Rejected 61 sources with FLAGS > 2
  Filtering completed in 0.063 s (retained 408 of 472 initial sources)
  Filtered from 472 to 408 point sources
  Found 408 point sources, robust FWHM 3.94 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
  No cosmic ray pixels found. Skipping source exclusion.
  Cleaned 408 sources to 368 with isolation distance [15]
  [Recentering 368 sources]
  Boxsize: 15 px, Border: 18 px (annulus outer=17.5, undersampled=False)
  Recentering 364 sources within border
  364 sources have valid cutouts
  Using center-of-mass centroiding (FWHM >= 3 px)
  Median pixel correction: 0.0 px
  Recentered 364 sources

──────────────────────────────────────────────────────────────────────
+       Aperture, optimum radius, and PSF on sequence stars        +
──────────────────────────────────────────────────────────────────────
  Excluded 45 sources based on quality cuts (kept 319/364).
  Number of sources: 103
  [Optimum aperture: 103 sources]
  Optimum-radius CoG mode: empirical (moffat_beta=4.765)

04:56:20  Using 103 sources with stable profiles for optimum-radius and PSF selection.
  Returning 73 sources, optimum radius: 1.68 * FWHM, scale: 15.5
  Aperture radius: 7.00 [pixels] (optimum_radius=1.68 FWHM)
  Computing aperture correction using 73 isolated sources at radius 7.00 pixels
  Aperture correction: -0.063 +/- 0.018
  Aperture correction (AP to total): -0.063 +/- 0.018 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
  Found 731 sources in field
  [Recentering 731 sources]
  Boxsize: 7 px, Border: 18 px (annulus outer=17.8, undersampled=False)
  Recentering 225 sources within border
  225 sources have valid cutouts
  Using center-of-mass centroiding (FWHM >= 3 px)
  Median pixel correction: 0.0 px
  Recentered 225 sources
  [Aperture photometry: 225 field sources]
  Instrumental magnitude of 225 sources measured
  Downsampling skipped: 225 sources (<= 300 target).
  Matched 219/225 catalog sources to SExtractor FWHM
  Building PSF from aligned image (psf_build_from_aligned=True).
  Building ePSF from 73 sources
  FWHM=3.68 pix  recenter=centroid_com  oversample=1x
  Initial sources: 73
  Sources after cuts: 73

04:56:21  Using 73/73 PSF candidates after spatial downselection
  [robust_extract_stars] Extracted 73 cutouts
  Rejected 7 PSF stars via FFT outlier filtering
  PSF build FWHM: input=3.94 px, used=3.68 px; normalisation radius=7.00 px (same as photometry aperture_radius); oversample=x1
  [PSF: ePSF build details]
  make_template_psf: False
  candidates: initial=73, after_cuts=73, used_after_uniform=73
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.90
  geometry: fwhm_input=3.94px, fwhm_used=3.68px, fwhm_arcsec=2.16", pixel_scale=0.587 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=9px, fit_box=9px, cutout=37px
  normalization: aperture_radius=7.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
  PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 9 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 37 px, sigma_clip=4.00
  (15 iters)
  ePSF init kernel: moffat_beta=4.765, gamma=4.65069 px, size=37x37
  ePSF build: converged=False, iterations=5, final_center_accuracy=0.005137 px
  ePSF did not converge in 5 iterations; retrying with 10 iterations

04:56:22 - WARNING - ePSF did NOT converge even with 10 iterations

04:56:24  PSF sources roundness: 0.03 +/- 0.01
  [PSF photometry: 225 sources]
  PSF fit bounds config:
  fitting_xy_bounds: 1 arcsec
  pixel_scale: 0.587 arcsec/px
  base_xy_bounds: 1.7 px
    effective per tier (bright/faint/very-faint)=1.7/1.7/1.7 px
  Fit shapes:
  bright: (11, 11)
  faint: (9, 9)
  very-faint: (9, 9)
  xy_bounds: 1.7 px
  undersampled: False
  Fitting 225 bright sources (LSQ)

04:56:25  Fitted 225 sources in 0.67s
  Saved WCS vs PSF offset plot:
  /home/liangrd/optical_data/EP260518a/TRT_REDUCED/EP260518a_TRT_20260523_AUS_Rc_stack_bgsub_reproject_wmean/WCS_vs_PSF_Offset_EP260518a_TRT_20260523_AUS_Rc_stack_bgsub_reproject_wmean_APT.png
  WCS vs PSF offset statistics:
  Median: (0.057, -0.025) px
  RMS: (0.109, 0.089) px

──────────────────────────────────────────────────────────────────────
+                    Zeropoint and color terms                     +
──────────────────────────────────────────────────────────────────────
  [Zeropoint: clean sequence stars]
  Removing 1 sources outside magnitude range 11.00-22.00 mag
  224 sources remaining after quality cuts
  [Linearity: saturation check (224 sources)]
  Removing 0 sources with threshold < 5
  Selected 60 high S/N sources (SNR >= 100) for linearity fit
  Post-RANSAC sigma clipping removed 12 additional outliers
  Constrained fit results:  Zeropoint = 21.099 +/- 0.014
  Linearity range (0.5-95% flux percentiles): 24.3 - 898.9
  Returning 48 sources for zeropoint fitting
  Catalog linearity check: 48 linear sources, ZP=21.099 +/- 0.014
  Color term correction disabled (photometry.apply_colorterms=False).
  Fitting zeropoints vs m_inst.

04:56:26 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 10;
tau: [19.40298045 22.98927767]

04:56:26 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 20;
tau: [25.53024681 26.24585755]

04:56:26 - WARNING - ZP MCMC low ESS: n_eff ≈ 94 (chain 2568, tau ≈ 27.2)

04:56:26  MCMC (robust): ZP=21.0988 ± 0.0019, f_out=0.066 (46/48 inliers, n_walkers=24, n_steps=1500)
  [AP] ZP=21.099 +/- 0.002

04:56:27 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 10;
tau: [23.66290305 22.02694804]

04:56:27 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 20;
tau: [23.91497619 27.77661107]

04:56:27 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 1 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 30;
tau: [26.41559308 32.12045511]

04:56:27 - WARNING - ZP MCMC low ESS: n_eff ≈ 76 (chain 2664, tau ≈ 34.9)

04:56:27  MCMC (robust): ZP=21.1481 ± 0.0028, f_out=0.068 (46/48 inliers, n_walkers=24, n_steps=2000)
  [PSF] ZP=21.148 +/- 0.003

04:56:28  [fit_zeropoint] Done in 2.606s

04:56:28 - WARNING - Source check plot: WCS axes failed (WCSAxes has insufficient coords (n=0)), using pixel coordinates only

04:56:29  Background mesh: FWHM=3.94 px scale=4.0 box=(15, 15) filter=3
  Local background: box_size=(15, 15)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
  Source mask contains 2580 pixels (6.72% of the image) after 2 iteration(s)
  Source mask contains 333883 pixels (31.84% of the image) after 2 iteration(s)
  Background mesh: FWHM=3.94 px scale=10.0 box=(65, 65) filter=3

04:56:30  Background RMS statistics: median=9.825, mean=9.904, std=0.479, floor=1.000

──────────────────────────────────────────────────────────────────────
+                      Background estimation                       +
──────────────────────────────────────────────────────────────────────
  Attempt: 1 | Box: (65, 65) | Filter: 3 | Exclude: 90.0%
  Target cutout: keeping uniform bias level 19.2072 in measurement image (shifted mean enabled).

──────────────────────────────────────────────────────────────────────
+                   Target photometry: Transient                   +
──────────────────────────────────────────────────────────────────────
  Transient's expected location: x = 529.400 pixels, y = 561.358 pixels
  Target AP: subtracting annulus median as measured (allowing negative local background).
  Target PSF fitting bound: 1.000 arcsec (1.70 px at 0.587 arcsec/px)
  [PSF photometry: 1 sources]
  PSF fit bounds config:
  fitting_xy_bounds: 1 arcsec
  pixel_scale: 0.587 arcsec/px
  base_xy_bounds: 1.7 px
    effective per tier (bright/faint/very-faint)=1.7/1.7/1.7 px
  Fit shapes:
  bright: (17, 17)
  faint: (13, 13)
  very-faint: (13, 13)
  xy_bounds: 1.7 px
  undersampled: False
  Target-fit shape scaling:
  bright/faint/very-faint: 3/2.5/2.5 * FWHM
  fit_sampling_boost: 1
  target_boost: 1.5
  pixel_scale: 0.587 arcsec/px
  Target PSF: after bootstrap - flux_all[0]=1.52e+03, x_all[0]=26, y_all[0]=26, valid=True
  Target PSF: using aperture-matched local background annulus (r_in=10.00 px, r_out=18.00 px, estimator=median).
  Fitting 1 bright sources (LSQ)
  Fitted 1 sources in 0.22s
/home/liangrd/autophot/psf.py:4863: UserWarning: Legend does not support handles for PatchCollection instances.
See: https://matplotlib.org/stable/tutorials/intermediate/legend_guide.html#implementing-a-custom-legend-handler
  ax1.legend(loc="upper left")

04:56:31  Target reduced chi2: 7.7e-01
  Target cfit: 1.2e-02
  Target qfit: 1.9e+00 (qfit of zero indicates a good fit)
  Transient fitted position: x = 530.364 +/- 0.157, y = 562.343 +/- 0.162
  Target SNR (aperture): 11.4
  Target SNR (PSF): 14.5
  Target threshold: 5.8 x background standard deviation
  Target detectability: 100.0 %
  Target location measured with FWHM: 5.2 px
  POSITION OFFSET ANALYSIS:
    Expected pixel position: (529.400, 561.358) px
    Fitted pixel position:   (530.364, 562.343) px
    Pixel offset: dx = +0.964 px, dy = +0.985 px
    Total pixel offset: 1.378 px
    Fitting uncertainty: 0.157, 0.162 px
    Sky offset: dRA = -0.742", dDec = -0.321"
    Total separation: 0.808 +/- 0.132 arcsec

──────────────────────────────────────────────────────────────────────
+           Calibrated magnitudes (AP and PSF on target)           +
──────────────────────────────────────────────────────────────────────
  Instrumental AP r-band magnitude: -0.699 +/- 0.091 [mag]
  Calibrated AP r-band magnitude: 20.400 +/- 0.091 [mag]
  Instrumental PSF r-band magnitude: -0.434 +/- 0.075 [mag]
  Calibrated PSF r-band magnitude: 20.714 +/- 0.075 [mag]

──────────────────────────────────────────────────────────────────────
+            Limiting magnitude (injection) near target            +
──────────────────────────────────────────────────────────────────────
  limiting_magnitude.recovery_method auto -> PSF (transient path: PSF)
  Limiting magnitude config:
  beta_limit: 0.5 (~3.00 sigma; n=3 beta formalism)
  detection_limit: None
  completeness_target: 0.50
    recovery_method=PSF
  Performing artificial source injection (beta_limit=0.500, snr_gate=off)
  Calculating injection limits for S/N thresholds: [3.0, 5.0]
  Calculating limiting magnitude for S/N >= 3.0
  Injected limiting magnitude: sigma-based initial guess unavailable (N=0); using -5.00
  Found 910 valid candidate sites for injection

04:56:32  inject m= -5.000 |  99.0%  (99/100 detected)
  inject m= -4.500 |  99.0%  (99/100 detected)

04:56:33  inject m= -4.000 |  99.0%  (99/100 detected)
  inject m= -3.500 |  99.0%  (99/100 detected)

04:56:34  inject m= -3.000 |  99.0%  (99/100 detected)
  inject m= -2.500 |  99.0%  (99/100 detected)

04:56:35  inject m= -2.000 |  99.0%  (99/100 detected)
  inject m= -1.500 |  99.0%  (99/100 detected)

04:56:36  inject m= -1.000 |  99.0%  (99/100 detected)
  inject m= -0.500 |  99.0%  (99/100 detected)

04:56:37  inject m= +0.000 |  99.0%  (99/100 detected)
  inject m= +0.500 |  99.0%  (99/100 detected)

04:56:38  inject m= +1.000 |  93.0%  (93/100 detected)
  inject m= +1.500 |  52.0%  (52/100 detected)

04:56:39  inject m= +2.000 |  24.0%  (24/100 detected)
  inject m= +1.750 |  36.0%  (36/100 detected)

04:56:40  inject m= +1.625 |  46.0%  (46/100 detected)
  inject m= +1.562 |  49.0%  (49/100 detected)

04:56:41  inject m= +1.531 |  49.0%  (49/100 detected)
  inject m= +1.516 |  50.0%  (50/100 detected)
      Bisection converged: m50=1.5156 (bracket width=0.0156 mag)
  Limiting magnitude: inst=1.516  apparent=22.664  ZP=21.148  method=PSF  completeness=50%  trials=20  [10.0s]
  S/N 3.0 limiting magnitude: 1.516
  Calculating limiting magnitude for S/N >= 5.0
  Injected limiting magnitude: sigma-based initial guess unavailable (N=0); using -5.00
  Found 893 valid candidate sites for injection

04:56:42  inject m= -5.000 |  98.0%  (98/100 detected)
  inject m= -4.500 |  98.0%  (98/100 detected)

04:56:43  inject m= -4.000 |  98.0%  (98/100 detected)
  inject m= -3.500 |  98.0%  (98/100 detected)

04:56:44  inject m= -3.000 |  98.0%  (98/100 detected)
  inject m= -2.500 |  98.0%  (98/100 detected)


[2/3] [OK]    /home/liangrd/optical_data/EP260518a/TRT/EP260518a_TRT_20260523_AUS_Rc_stack_bgsub_reproject_wmean.fits

04:56:56  [File: EP260518a_TRT_20260523_AUS_Ic_stack_bgsub_reproject_wmean_APT.fits]
  telescope.yml loaded from: /home/liangrd/optical_data/EP260518a/TRT/telescope.yml
  Exposure time: 800 s (header keyword EXPTIME)
  Pixel scale from WCS: 0.587 arcsec/pixel
  Gain: 1 e-/ADU (header keyword GAIN)
  Telescope: CDK700, Instrument: Andor_DU934P_BV, Filter: i
  Pixel scale: 0.587 arcsec/pixel

──────────────────────────────────────────────────────────────────────
+                       Image preprocessing                        +
──────────────────────────────────────────────────────────────────────
  Target position for NaN trimming: (530.0, 560.4) px
  NaN boundary trimming: 0/1048576 pixels are NaN (0.0%)
  Target pixel coordinates refreshed after trimming: (530.0, 560.4) px

──────────────────────────────────────────────────────────────────────
+                    Source detection and FWHM                     +
──────────────────────────────────────────────────────────────────────
  SExtractor executable detected: /home/liangrd/anaconda3/envs/autophot/bin/sex
  [SExtractor: EP260518a_TRT_20260523_AUS_Ic_stack_bgsub_reproject_wmean_APT.fits (default)]
  Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
  Creating convolution kernel with FWHM: 3.0 pixels
  Initial source count: 460
  Rejected 1 sources outside FWHM range [1.1, 100.0]
  Rejected 46 low-SNR sources (SNR < 3.0)
  Estimated FWHM: 3.93 pixels (sigma = 3.23 pixels)
  Rejected 55 sources with FLAGS > 2
  Filtering completed in 0.003 s (retained 358 of 460 initial sources)
  Filtered from 460 to 358 point sources
  Found 358 point sources, robust FWHM 3.88 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)

──────────────────────────────────────────────────────────────────────
+                     Background: initial pass                     +
──────────────────────────────────────────────────────────────────────
  [Background: sky & RMS]
  NaN pixels: 0 (0.00%)

04:56:57  Background regime=sparse  bright_frac=0.013  large_scale_ratio=0.193
  Background mesh: FWHM=3.88 px scale=10.0 box=(65, 65) filter=3
  Source mask contains 123726 pixels (11.80% of the image) after 2 iteration(s)
  Masked fraction (total): 11.80%
  box_size=(65, 65)  filter_size=3
  Global stats: mean=-1.106e+00 med=-1.540e+00 std=2.317e+01

04:56:58  Background RMS statistics: median=13.631, mean=15.294, std=3.904, floor=1.363

──────────────────────────────────────────────────────────────────────
+                      Background estimation                       +
──────────────────────────────────────────────────────────────────────
  Attempt: 1 | Box: (65, 65) | Filter: 3 | Exclude: 90.0%
  Background median=4.081e+00 RMS=1.529e+01
  Preliminary FWHM: 3.9 pixels
  Undersampled mode: False (FWHM=3.88 px, threshold=2.50 px)

──────────────────────────────────────────────────────────────────────
+                WCS: check header and plate solve                 +
──────────────────────────────────────────────────────────────────────
  Pre-existing WCS found in header
  Loaded 2 variable sources from input_yaml.
  Variable sources within image boundaries (1):
  [TNS check: Transient]
  TNS RA/Dec: 299.040671, -48.636211
  Expected pixel position: (529.99, 560.40)

──────────────────────────────────────────────────────────────────────
+        Background: masked pass (variable sources, SIMBAD)        +
──────────────────────────────────────────────────────────────────────
  [Background: sky & RMS]
  NaN pixels: 0 (0.00%)
  Background regime=sparse  bright_frac=0.013  large_scale_ratio=0.193
  Background mesh: FWHM=3.88 px scale=10.0 box=(65, 65) filter=3
  Source mask contains 123726 pixels (11.80% of the image) after 2 iteration(s)
  Masked fraction (total): 11.80%
  box_size=(65, 65)  filter_size=3
  Global stats: mean=-1.106e+00 med=-1.540e+00 std=2.317e+01

04:56:59  Background RMS statistics: median=13.631, mean=15.294, std=3.904, floor=1.363

──────────────────────────────────────────────────────────────────────
+                      Background estimation                       +
──────────────────────────────────────────────────────────────────────
  Attempt: 1 | Box: (65, 65) | Filter: 3 | Exclude: 90.0%
  Background median=4.081e+00 RMS=1.529e+01

──────────────────────────────────────────────────────────────────────
+                         Target position                          +
──────────────────────────────────────────────────────────────────────
  [299.04067125 -48.63621125]
  Target summary:
  Name: Transient
  Image size: 1024 x 1024 px
  Sky: RA 299.040671 deg, Dec -48.636211 deg
  Pixel: (529.99, 560.40)
  Offset from image center: dx=+18.49 px, dy=+48.90 px
  Bounds: within bounds (min edge margin 462.60 px)
  [299.04067125 -48.63621125]
  [299.04067125 -48.63621125]

──────────────────────────────────────────────────────────────────────
+         Calibration stage: image, background, and weight         +
──────────────────────────────────────────────────────────────────────
  Reusing cached background results (fpath unchanged)

──────────────────────────────────────────────────────────────────────
+                  Reference photometric catalog                   +
──────────────────────────────────────────────────────────────────────
  [Catalog: sequence sources in field]
  Existing SKYMAPPER catalog found for Transient
/home/liangrd/optical_data/EP260518a/TRT/catalog_queries/skymapper/transient/Transient_r_10.0arcmins_skymapper_target_ra_299.040671_dec_-48.636211.csv
  Cleaning 736 sources
  Excluding 23 sources with no i band information
  713 sources in output catalog
  Border filtering: removed 483 sources outside border, 230 sources remaining

04:57:04 - WARNING - Border filtering removed 67.7% of sources; skipping border filter to preserve catalog sources

──────────────────────────────────────────────────────────────────────
+               Source detection on calibrated image               +
──────────────────────────────────────────────────────────────────────
  [SExtractor: EP260518a_TRT_20260523_AUS_Ic_stack_bgsub_reproject_wmean_APT.fits (default)]
  Using FWHM = 3.0 pixels to construct the SExtractor convolution kernel
  Creating convolution kernel with FWHM: 3.0 pixels
  Initial source count: 391
  Rejected 1 sources outside FWHM range [1.1, 100.0]
  Rejected 3 low-SNR sources (SNR < 3.0)
  Estimated FWHM: 3.90 pixels (sigma = 2.54 pixels)
  Rejected 1 sources within 7.80 pixels of masked regions
  Rejected 42 sources with FLAGS > 2
  Filtering completed in 0.058 s (retained 344 of 391 initial sources)
  Filtered from 391 to 344 point sources
  Found 344 point sources, robust FWHM 3.85 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
  [SExtractor: EP260518a_TRT_20260523_AUS_Ic_stack_bgsub_reproject_wmean_APT.fits (default)]
  Using FWHM = 3.9 pixels to construct the SExtractor convolution kernel
  Creating convolution kernel with FWHM: 3.9 pixels
  Initial source count: 359
  Rejected 1 sources outside FWHM range [1.1, 100.0]
  Rejected 2 low-SNR sources (SNR < 3.0)
  Estimated FWHM: 3.91 pixels (sigma = 2.62 pixels)
  Rejected 1 sources within 7.83 pixels of masked regions
  Rejected 43 sources with FLAGS > 2
  Filtering completed in 0.045 s (retained 312 of 359 initial sources)
  Filtered from 359 to 312 point sources
  Found 312 point sources, robust FWHM 3.86 px; scale = 15.0 (FWHM x 3.00 from source_detection / config)
  No cosmic ray pixels found. Skipping source exclusion.
  Cleaned 312 sources to 281 with isolation distance [15]
  [Recentering 281 sources]
  Boxsize: 15 px, Border: 18 px (annulus outer=17.2, undersampled=False)
  Recentering 275 sources within border
  275 sources have valid cutouts
  Using center-of-mass centroiding (FWHM >= 3 px)
  Median pixel correction: 0.0 px
  Recentered 275 sources

──────────────────────────────────────────────────────────────────────
+       Aperture, optimum radius, and PSF on sequence stars        +
──────────────────────────────────────────────────────────────────────

04:57:05  Excluded 32 sources based on quality cuts (kept 243/275).
  Number of sources: 60
  [Optimum aperture: 60 sources]
  Optimum-radius CoG mode: empirical (moffat_beta=4.765)
  Using 60 sources with stable profiles for optimum-radius and PSF selection.
  Returning 30 sources, optimum radius: 1.75 * FWHM, scale: 15.5
  Aperture radius: 7.00 [pixels] (optimum_radius=1.75 FWHM)
  Computing aperture correction using 30 isolated sources at radius 7.00 pixels
  Aperture correction: -0.062 +/- 0.018
  Aperture correction (AP to total): -0.062 +/- 0.018 mag (stored for later; set apply_aperture_correction: true to apply in pipeline)
  Found 713 sources in field
  [Recentering 713 sources]
  Boxsize: 7 px, Border: 18 px (annulus outer=17.6, undersampled=False)
  Recentering 223 sources within border
  223 sources have valid cutouts
  Using center-of-mass centroiding (FWHM >= 3 px)
  Median pixel correction: 0.0 px
  Recentered 223 sources
  [Aperture photometry: 223 field sources]

04:57:06  Instrumental magnitude of 217 sources measured
  Downsampling skipped: 223 sources (<= 300 target).
  Matched 208/223 catalog sources to SExtractor FWHM
  Building PSF from aligned image (psf_build_from_aligned=True).
  Building ePSF from 30 sources
  FWHM=3.67 pix  recenter=centroid_com  oversample=1x
  Initial sources: 30
  Sources after cuts: 30
  Using 30/30 PSF candidates after spatial downselection
  [robust_extract_stars] Extracted 30 cutouts
  Rejected 3 PSF stars via FFT outlier filtering
  PSF build FWHM: input=3.86 px, used=3.67 px; normalisation radius=7.00 px (same as photometry aperture_radius); oversample=x1
  [PSF: ePSF build details]
  make_template_psf: False
  candidates: initial=30, after_cuts=30, used_after_uniform=30
  selection cuts: min_candidates=8, threshold_limit=5.0, SNR_limit=[5.0, 1000000.0], min_keep_frac_after_cut=0.60, saturate_frac=0.90
  geometry: fwhm_input=3.86px, fwhm_used=3.67px, fwhm_arcsec=2.15", pixel_scale=0.587 arcsec/px, build_sampling_boost=1.00, oversample=x1,
    recenter=centroid_com, cen_box=9px, fit_box=9px, cutout=37px
  normalization: aperture_radius=7.00px (same as photometry)
  epsf builder: sigma_clip=4.00, sigma_clip_maxiters=15, maxiters=10, smoothing_kernel=quartic
  fft rejection: enabled=True, n_sigma=4.00, min_frac_keep=0.25, min_stars=10
  PSF build windows: fit_box=2.50*FWHM (base 2.50, min 2.50 arcsec) -> 9 px, cutout=10.00*FWHM (base 10.00, min 9.00 arcsec) -> 37 px, sigma_clip=4.00
  (15 iters)
  ePSF init kernel: moffat_beta=4.765, gamma=4.63768 px, size=37x37
  ePSF build: converged=True, iterations=4, final_center_accuracy=0.0004672 px

04:57:07  PSF sources roundness: 0.03 +/- 0.01
  [PSF photometry: 223 sources]
  PSF fit bounds config:
  fitting_xy_bounds: 1 arcsec
  pixel_scale: 0.587 arcsec/px
  base_xy_bounds: 1.7 px
    effective per tier (bright/faint/very-faint)=1.7/1.7/1.7 px
  Fit shapes:
  bright: (11, 11)
  faint: (9, 9)
  very-faint: (9, 9)
  xy_bounds: 1.7 px
  undersampled: False
  Fitting 199 bright sources (LSQ)

04:57:08  Fitting 11 faint sources (LSQ)
  Fitting 13 very faint sources (LSQ)
  Fitted 223 sources in 0.80s
  Saved WCS vs PSF offset plot:
  /home/liangrd/optical_data/EP260518a/TRT_REDUCED/EP260518a_TRT_20260523_AUS_Ic_stack_bgsub_reproject_wmean/WCS_vs_PSF_Offset_EP260518a_TRT_20260523_AUS_Ic_stack_bgsub_reproject_wmean_APT.png
  WCS vs PSF offset statistics:
  Median: (0.025, -0.018) px
  RMS: (0.136, 0.136) px

──────────────────────────────────────────────────────────────────────
+                    Zeropoint and color terms                     +
──────────────────────────────────────────────────────────────────────
  [Zeropoint: clean sequence stars]
  Removing 1 sources outside magnitude range 11.00-22.00 mag
  Removing 1 sources with detection threshold < 3.0
  Removing 1 sources with snr < 3.0
  221 sources remaining after quality cuts
  [Linearity: saturation check (221 sources)]
  Removing 5 sources with threshold < 5
  Selected 31 high S/N sources (SNR >= 100) for linearity fit
  Post-RANSAC sigma clipping removed 3 additional outliers
  Constrained fit results:  Zeropoint = 20.068 +/- 0.024
  Linearity range (0.5-95% flux percentiles): 25.5 - 615.6

04:57:09  Returning 28 sources for zeropoint fitting
  Catalog linearity check: 28 linear sources, ZP=20.068 +/- 0.024
  Color term correction disabled (photometry.apply_colorterms=False).
  Fitting zeropoints vs m_inst.

04:57:09 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 10;
tau: [22.73031072 20.52818036]

04:57:09 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 20;
tau: [28.94461204 26.06314233]

04:57:09 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 30;
tau: [31.48598531 31.02628257]

04:57:09 - WARNING - ZP MCMC low ESS: n_eff ≈ 45 (chain 1554, tau ≈ 34.6)
  MCMC (robust): ZP=20.0591 ± 0.0025, f_out=0.261 (21/28 inliers, n_walkers=14, n_steps=2000)
  [AP] ZP=20.059 +/- 0.002

04:57:10 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 10;
tau: [15.31630733 27.58955681]

04:57:10 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 2 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 20;
tau: [21.02143851 30.36792988]

04:57:10 - WARNING - The chain is shorter than 50 times the integrated autocorrelation time for 1 parameter(s). Use this estimate with caution and run a longer chain!
N/50 = 30;
tau: [24.9869697  31.72688163]

04:57:10 - WARNING - ZP MCMC low ESS: n_eff ≈ 49 (chain 1638, tau ≈ 33.2)

04:57:10  MCMC (robust): ZP=20.1136 ± 0.0023, f_out=0.188 (23/28 inliers, n_walkers=14, n_steps=2000)
  [PSF] ZP=20.114 +/- 0.002
  [fit_zeropoint] Done in 1.878s

04:57:11 - WARNING - Source check plot: WCS axes failed (WCSAxes has insufficient coords (n=0)), using pixel coordinates only

04:57:12  Background mesh: FWHM=3.86 px scale=4.0 box=(15, 15) filter=3
  Local background: box_size=(15, 15)  filter_size=3  mesh_scale=0.8  exclude_inner_radius=0 px
  Source mask contains 1130 pixels (3.07% of the image) after 2 iteration(s)
  Source mask contains 225423 pixels (21.50% of the image) after 2 iteration(s)
  Background mesh: FWHM=3.86 px scale=10.0 box=(65, 65) filter=3
  Background RMS statistics: median=13.450, mean=15.069, std=3.737, floor=1.345

──────────────────────────────────────────────────────────────────────
+                      Background estimation                       +
──────────────────────────────────────────────────────────────────────
  Attempt: 1 | Box: (65, 65) | Filter: 3 | Exclude: 90.0%
  Target cutout: keeping uniform bias level 31.9943 in measurement image (shifted mean enabled).

──────────────────────────────────────────────────────────────────────
+                   Target photometry: Transient                   +
──────────────────────────────────────────────────────────────────────
  Transient's expected location: x = 529.993 pixels, y = 560.395 pixels
  Target AP: subtracting annulus median as measured (allowing negative local background).

04:57:13  Target PSF fitting bound: 1.000 arcsec (1.70 px at 0.587 arcsec/px)
  [PSF photometry: 1 sources]
  PSF fit bounds config:
  fitting_xy_bounds: 1 arcsec
  pixel_scale: 0.587 arcsec/px
  base_xy_bounds: 1.7 px
    effective per tier (bright/faint/very-faint)=1.7/1.7/1.7 px
  Fit shapes:
  bright: (17, 17)
  faint: (13, 13)
  very-faint: (13, 13)
  xy_bounds: 1.7 px
  undersampled: False
  Target-fit shape scaling:
  bright/faint/very-faint: 3/2.5/2.5 * FWHM
  fit_sampling_boost: 1
  target_boost: 1.5
  pixel_scale: 0.587 arcsec/px
  Target PSF: after bootstrap - flux_all[0]=3.19e+03, x_all[0]=27, y_all[0]=26, valid=True
  Target PSF: using aperture-matched local background annulus (r_in=10.00 px, r_out=18.00 px, estimator=median).
  Fitting 1 bright sources (LSQ)
  LSQ retry for 1/1 problematic fits (fit_shape (17, 17) -> (19, 19), xy_bounds 1.70 -> 1.19).
  Fitted 1 sources in 0.04s
/home/liangrd/autophot/psf.py:4863: UserWarning: Legend does not support handles for PatchCollection instances.
See: https://matplotlib.org/stable/tutorials/intermediate/legend_guide.html#implementing-a-custom-legend-handler
  ax1.legend(loc="upper left")
  Target fitting issues: ['near_bound']
  Target reduced chi2: 6.4e-01
  Target cfit: -6.5e-03
  Target qfit: 3.1e+00 (qfit of zero indicates a good fit)
  Transient fitted position: x = 530.950 +/- 0.210, y = 561.589 +/- 0.210
  Target SNR (aperture): 13.1
  Target SNR (PSF): 11.0
  Target threshold: 4.1 x background standard deviation
  Target detectability: 100.0 %
  Target location measured with FWHM: 11.3 px
  POSITION OFFSET ANALYSIS:
    Expected pixel position: (529.993, 560.395) px
    Fitted pixel position:   (530.950, 561.589) px
    Pixel offset: dx = +0.957 px, dy = +1.193 px
    Total pixel offset: 1.530 px
    Fitting uncertainty: 0.210, 0.210 px

04:57:14    Sky offset: dRA = -0.854", dDec = -0.274"
    Total separation: 0.897 +/- 0.174 arcsec

──────────────────────────────────────────────────────────────────────
+           Calibrated magnitudes (AP and PSF on target)           +
──────────────────────────────────────────────────────────────────────
  Instrumental AP i-band magnitude: -1.501 +/- 0.080 [mag]
  Calibrated AP i-band magnitude: 18.558 +/- 0.080 [mag]
  Instrumental PSF i-band magnitude: -0.704 +/- 0.099 [mag]
  Calibrated PSF i-band magnitude: 19.409 +/- 0.099 [mag]

──────────────────────────────────────────────────────────────────────
+            Limiting magnitude (injection) near target            +
──────────────────────────────────────────────────────────────────────
  limiting_magnitude.recovery_method auto -> PSF (transient path: PSF)
  Limiting magnitude config:
  beta_limit: 0.5 (~3.00 sigma; n=3 beta formalism)
  detection_limit: None
  completeness_target: 0.50
    recovery_method=PSF
  Performing artificial source injection (beta_limit=0.500, snr_gate=off)
  Calculating injection limits for S/N thresholds: [3.0, 5.0]
  Calculating limiting magnitude for S/N >= 3.0
  Injected limiting magnitude: sigma-based initial guess unavailable (N=0); using -5.00
  Found 1437 valid candidate sites for injection
  inject m= -5.000 | 100.0%  (100/100 detected)

04:57:15  inject m= -4.500 | 100.0%  (100/100 detected)
  inject m= -4.000 | 100.0%  (100/100 detected)

04:57:16  inject m= -3.500 | 100.0%  (100/100 detected)
  inject m= -3.000 | 100.0%  (100/100 detected)

04:57:17  inject m= -2.500 | 100.0%  (100/100 detected)
  inject m= -2.000 | 100.0%  (100/100 detected)

04:57:18  inject m= -1.500 | 100.0%  (100/100 detected)
  inject m= -1.000 | 100.0%  (100/100 detected)

04:57:19  inject m= -0.500 | 100.0%  (100/100 detected)
  inject m= +0.000 |  91.0%  (91/100 detected)

04:57:20  inject m= +0.500 |  31.0%  (31/100 detected)
  inject m= +0.250 |  61.0%  (61/100 detected)

04:57:21  inject m= +0.375 |  43.0%  (43/100 detected)
  inject m= +0.312 |  51.0%  (51/100 detected)

04:57:22  inject m= +0.344 |  48.0%  (48/100 detected)
  inject m= +0.328 |  48.0%  (48/100 detected)
      Bisection converged: m50=0.3177 (bracket width=0.0156 mag)
  Limiting magnitude: inst=0.318  apparent=20.431  ZP=20.114  method=PSF  completeness=50%  trials=17  [8.7s]
  S/N 3.0 limiting magnitude: 0.318
  Calculating limiting magnitude for S/N >= 5.0
  Injected limiting magnitude: sigma-based initial guess unavailable (N=0); using -5.00
  Found 1401 valid candidate sites for injection


[3/3] [OK]    /home/liangrd/optical_data/EP260518a/TRT/EP260518a_TRT_20260523_AUS_Ic_stack_bgsub_reproject_wmean.fits
[Collect photometry: /home/liangrd/optical_data/EP260518a/TRT_REDUCED]
Photometry pipeline completed in 125.555 seconds.
Results saved to: /home/liangrd/optical_data/EP260518a/TRT_REDUCED/lightcurve_output.csv

In [3]:
config.keys()

dict_keys(['fits_dir', 'ignore_no_telescop', 'skip_file_check', 'outdir_name', 'select_filter', 'selected_filters', 'global_verbose_level', 'target_name', 'target_ra', 'target_dec', 'nCPU', 'restart', 'wdir', 'rng_seed', 'use_header_radec', 'save_cutout_plot', 'fpath', 'write_dir', 'imageFilter', 'exposure_time', 'gain', 'read_noise', 'pixel_scale', 'fwhm', 'fwhm_max_sigma_px', 'science_fwhm', 'scale', 'saturate', 'aperture_correction', 'aperture_correction_err', 'preprocessing', 'photometry', 'wcs', 'catalog', 'zeropoint', 'cosmic_rays', 'fitting', 'source_detection', 'limiting_magnitude', 'alignment', 'template_subtraction', 'background', 'templates', 'error', 'psf', 'target_photometry'])

In [4]:
config['catalog']

{'use_catalog': {'griz': 'skymapper', 'u': 'skymapper', 'UBVRI': 'apass'},
 'catalog_custom_fpath': None,
 'transmission_curve_map': None,
 'curve_map_svo': None,
 'catalog_radius': 0.25,
 'gaia_xp_radius_deg': 0.1667,
 'gaia_xp_max_sources': 5000,
 'gaia_xp_order_by': 'brightness',
 'gaia_xp_show_progress': False,
 'gaia_curve_map_max_sources': 100,
 'gaia_curve_map_order_by': 'distance',
 'gaia_nearest_prefetch_factor': 50,
 'gaia_nearest_prefetch_min': 200,
 'gaia_nearest_prefetch_max': 10000,
 'gaia_archive_query_pause_before_sec': 1.0,
 'gaia_archive_query_pause_after_sec': 1.0,
 'gaia_xp_batch_size': 200,
 'gaia_xp_batch_pause_sec': 1.0,
 'gaia_archive_max_retries': 3,
 'gaia_archive_retry_base_delay_sec': 2.0,
 'gaia_xp_generate_error_correction': True,
 'gaia_xp_generate_truncation': False,
 'gaia_xp_photometric_systems': ['SDSS_Std', 'JKC_Std'],
 'include_IR_sequence_data': False,
 'MASTcasjobs_wsid': None,
 'MASTcasjobs_pwd': None}

In [15]:
import requests
import pandas as pd
import numpy as np
                        
ra = 149.9025
dec = -3.3073
radius_deg = 0.1
                        
# Direct MAST API call for Pan-STARRS
url = url = "https://catalogs.mast.stsci.edu/api/v0.1/panstarrs/dr2/mean"
params = {
    "ra": ra,
    "dec": dec,
    "radius": radius_deg,
    "pagesize": 10000,
    "format": "json"
    }
                        
response = requests.get(url, params=params, timeout=60)
response.raise_for_status()
data = response.json()

                        
if not data:
    electedCatalog = pd.DataFrame()
else:
# Convert to DataFrame, handling None strings
    cols = [data['info'][i]['name'] for i in range(len(data['info']))]
    selectedCatalog = pd.DataFrame(data['data'],columns=cols)

# Replace all forms of None/null with np.nan
    for col in selectedCatalog.columns:
        if selectedCatalog[col].dtype == object:
                                    selectedCatalog[col] = selectedCatalog[col].replace(
                                        ['None', 'none', 'NONE', 'null', 'NULL', 'nan', 'NaN'], np.nan
                                    )
    # Convert numeric columns
    for col in selectedCatalog.columns:
        if col not in ['objName', 'objAltName1', 'objAltName2', 'objAltName3']:
            try:
                selectedCatalog[col] = pd.to_numeric(selectedCatalog[col], errors='coerce')
            except Exception:
                pass                      
                # except Exception as api_exc:
                #         logger.warning(f"Direct Pan-STARRS API failed ({api_exc}), using empty catalog")
                #         selectedCatalog = pd.DataFrame()
                    
# Replace all common null representations
selectedCatalog = selectedCatalog.replace([-999, -999.0, "None", "none", "NONE", "null", "NULL"], np.nan)
columns = [
                        "raMean",
                        "decMean",
                        "raMeanErr",
                        "decMeanErr",
                        "gMeanPSFMag",
                        "gMeanPSFMagErr",
                        "rMeanPSFMag",
                        "rMeanPSFMagErr",
                        "iMeanPSFMag",
                        "iMeanPSFMagErr",
                        "zMeanPSFMag",
                        "zMeanPSFMagErr",
                        "yMeanPSFMag",
                        "yMeanPSFMagErr",
                    ]
selectedCatalog = selectedCatalog[columns]

In [17]:
selectedCatalog

,raMean,decMean,raMeanErr,decMeanErr,gMeanPSFMag,gMeanPSFMagErr,rMeanPSFMag,rMeanPSFMagErr,iMeanPSFMag,iMeanPSFMagErr,zMeanPSFMag,zMeanPSFMagErr,yMeanPSFMag,yMeanPSFMagErr
0,149.867420,-3.400961,0.02027,0.02027,NaN,NaN,NaN,NaN,18.491199,0.013639,NaN,NaN,NaN,NaN
1,149.903243,-3.337126,0.15781,0.15781,NaN,NaN,21.327101,0.427746,NaN,NaN,NaN,NaN,NaN,NaN
2,149.903353,-3.334899,0.01553,0.01553,NaN,NaN,NaN,NaN,NaN,NaN,16.557899,0.004028,NaN,NaN
3,149.904030,-3.334530,0.01776,0.01776,NaN,NaN,NaN,NaN,NaN,NaN,17.524099,0.009503,NaN,NaN
4,149.904596,-3.338761,0.28444,0.28444,NaN,NaN,NaN,NaN,21.210501,0.284047,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,149.956071,-3.321201,0.01618,0.01618,17.238001,0.005908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,149.956445,-3.318800,0.21728,0.21728,NaN,NaN,NaN,NaN,NaN,NaN,20.944700,0.216764,NaN,NaN
9997,149.956955,-3.320192,0.25385,0.25385,NaN,NaN,NaN,NaN,17.620199,0.253411,NaN,NaN,NaN,NaN
9998,149.956955,-3.323005,0.23360,0.23360,NaN,NaN,NaN,NaN,18.852501,0.233115,NaN,NaN,NaN,NaN
9999,149.957183,-3.321400,0.01640,0.01640,17.403500,0.006541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
cols = [data['info'][i]['name'] for i in range(len(data['info']))]
cols

['objName',
 'objAltName1',
 'objAltName2',
 'objAltName3',
 'objID',
 'uniquePspsOBid',
 'ippObjID',
 'surveyID',
 'htmID',
 'zoneID',
 'tessID',
 'projectionID',
 'skyCellID',
 'randomID',
 'batchID',
 'dvoRegionID',
 'processingVersion',
 'objInfoFlag',
 'astrometryCorrectionFlag',
 'qualityFlag',
 'raStack',
 'decStack',
 'raStackErr',
 'decStackErr',
 'raMean',
 'decMean',
 'raMeanErr',
 'decMeanErr',
 'pmra',
 'pmdec',
 'pmraErr',
 'pmdecErr',
 'epochMean',
 'posMeanChisq',
 'cx',
 'cy',
 'cz',
 'lambda',
 'beta',
 'l',
 'b',
 'nStackObjectRows',
 'nStackDetections',
 'nDetections',
 'ng',
 'nr',
 'ni',
 'nz',
 'ny',
 'gQfPerfect',
 'gMeanPSFMag',
 'gMeanPSFMagErr',
 'gMeanPSFMagStd',
 'gMeanPSFMagNpt',
 'gMeanPSFMagMin',
 'gMeanPSFMagMax',
 'gMeanKronMag',
 'gMeanKronMagErr',
 'gMeanKronMagStd',
 'gMeanKronMagNpt',
 'gMeanApMag',
 'gMeanApMagErr',
 'gMeanApMagStd',
 'gMeanApMagNpt',
 'gFlags',
 'rQfPerfect',
 'rMeanPSFMag',
 'rMeanPSFMagErr',
 'rMeanPSFMagStd',
 'rMeanPSFMagNpt',
 'rMeanPSFMagMin',
 'rMeanPSFMagMax',
 'rMeanKronMag',
 'rMeanKronMagErr',
 'rMeanKronMagStd',
 'rMeanKronMagNpt',
 'rMeanApMag',
 'rMeanApMagErr',
 'rMeanApMagStd',
 'rMeanApMagNpt',
 'rFlags',
 'iQfPerfect',
 'iMeanPSFMag',
 'iMeanPSFMagErr',
 'iMeanPSFMagStd',
 'iMeanPSFMagNpt',
 'iMeanPSFMagMin',
 'iMeanPSFMagMax',
 'iMeanKronMag',
 'iMeanKronMagErr',
 'iMeanKronMagStd',
 'iMeanKronMagNpt',
 'iMeanApMag',
 'iMeanApMagErr',
 'iMeanApMagStd',
 'iMeanApMagNpt',
 'iFlags',
 'zQfPerfect',
 'zMeanPSFMag',
 'zMeanPSFMagErr',
 'zMeanPSFMagStd',
 'zMeanPSFMagNpt',
 'zMeanPSFMagMin',
 'zMeanPSFMagMax',
 'zMeanKronMag',
 'zMeanKronMagErr',
 'zMeanKronMagStd',
 'zMeanKronMagNpt',
 'zMeanApMag',
 'zMeanApMagErr',
 'zMeanApMagStd',
 'zMeanApMagNpt',
 'zFlags',
 'yQfPerfect',
 'yMeanPSFMag',
 'yMeanPSFMagErr',
 'yMeanPSFMagStd',
 'yMeanPSFMagNpt',
 'yMeanPSFMagMin',
 'yMeanPSFMagMax',
 'yMeanKronMag',
 'yMeanKronMagErr',
 'yMeanKronMagStd',
 'yMeanKronMagNpt',
 'yMeanApMag',
 'yMeanApMagErr',
 'yMeanApMagStd',
 'yMeanApMagNpt',
 'yFlags',
 'distance']

In [14]:
pd.DataFrame(data['data'],columns=cols)

,objName,objAltName1,objAltName2,objAltName3,objID,uniquePspsOBid,ippObjID,surveyID,htmID,zoneID,...,yMeanKronMag,yMeanKronMagErr,yMeanKronMagStd,yMeanKronMagNpt,yMeanApMag,yMeanApMagErr,yMeanApMagStd,yMeanApMagNpt,yFlags,distance
0,PSO J149.8674-03.4010,-999,-999,-999,103911498673939288,3604974000100663,378077381232954,0,10554534216377,10391,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.099994
1,PSO J149.8726-03.4018,-999,-999,-999,103911498725808282,3604974000101295,378077381233586,0,10554534036893,10391,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.099088
2,PSO J149.8727-03.4006,-999,-999,-999,103911498727599787,3604974000125933,378077381260093,0,10554534050922,10391,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,16416,0.097880
3,PSO J149.8742-03.4015,-999,-999,-999,103911498742068654,3604974000046462,378077381178751,0,10554534050264,10391,...,-999.0000,-999.000000,-999.00000,0,26.0639,0.400649,-999.000000,1,4120,0.098313
4,PSO J149.8761-03.4027,-999,-999,-999,103911498761477130,3604974000126007,378077381260167,0,10554534041958,10391,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,16416,0.098992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,PSO J149.9857-03.3167,-999,-999,-999,104021499856960362,3604974000114400,378077381246691,0,10554621099854,10402,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.083610
9996,PSO J149.9861-03.3146,-999,-999,-999,104021499860982908,3604974000127986,378077381262146,0,10554621094614,10402,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,16416,0.083785
9997,PSO J149.9861-03.3156,-999,-999,-999,104021499861381731,3604974000114458,378077381246749,0,10554621096217,10402,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.083917
9998,PSO J149.9863-03.3116,-999,-999,-999,104021499862526446,3604974000057378,378077381189668,0,10554621038905,10402,...,-999.0000,-999.000000,-999.00000,0,-999.0000,-999.000000,-999.000000,0,0,0.083723
9999,PSO J149.9865-03.3113,-999,-999,-999,104021499865426807,3604974000057402,378077381189692,0,10554621042334,10402,...,16.3578,0.016665,0.04203,15,16.2768,0.009616,0.026111,15,115000,0.084008

In [ ]:
#!/usr/bin/env python3
"""
Example AutoPhOT driver script.
"""
import os
from autophot import AutomatedPhotometry, prepare_template_directory

# Load default configuration
config = AutomatedPhotometry.load()
config["nCPU"] = 4  # Parallel processing

# Paths
config["outdir_name"] = "REDUCED"
config["wdir"] = "/home/liangrd/optical_data/EP260131a/NTT"
config["fits_dir"] = FITS_DIR

# Target coordinates
config["target_name"] = "EP260131a"
config["target_ra"] = 149.9025
config["target_dec"] = -3.3073

# Photometric catalogs by filter
config["catalog"]["use_catalog"] = {
    "griz": "pan_starrs",
    "u": "gaia", 
    "UBVRI": "apass",
}

# Processing options
config["cosmic_rays"]["remove_cmrays"] = False
config["wcs"]["redo_wcs"] = True

# Enable template subtraction
config["template_subtraction"]["do_subtraction"] = False
# config["template_subtraction"]["method"] = "sfft"
# config["template_subtraction"]["alignment_method"] = "swarp"  # SCAMP+SWarp onto science grid (recommended)

# Create template directories
prepare_template_directory(
    fits_dir=config["fits_dir"],
    include_legacy_p_folders=False,
    confirm_before_continue=True,
)

# Run photometry
output = AutomatedPhotometry.run_photometry(default_input=config, do_photometry=True)

# Generate plots and tables
from lightcurve import plot_lightcurve, generate_photometry_table
plot_lightcurve(output, snr_limit=3, method="PSF")
generate_photometry_table(output, snr_limit=3, method="PSF")

— Default input: /home/liangrd/autophot/databases/default_input.yml —

Configuration loaded in 0.059 seconds.



— Template directory prepared: /home/liangrd/optical_data/EP260131a/NTT/templates —

Template folder summary: created=13 existing=0 filters=U,B,V,R,I,u,g,r,i,z,J,H,K

KeyError: 'ps1'